framework:
  name: selenium_framework
  proxies:
    - name: proxyrack
    - name: iproyal/us
    - name: iproyal/lithuania
    - name: 123proxy
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
    undetected_driver: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 3000
    loading_delay: 8
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.allegro.pl/listing?string={}&order=n
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .opbox-listing article div>h2>a[href*="/oferta/"]
      regex: allegro.pl\/(.*)$
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .opbox-listing article div>h2>a[href*="/oferta/"]
      regex: allegro.pl\/(.*)$
    listing_container_css_selector: div.opbox-listing article>div
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: div>h2>a[href*="/oferta/"]
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[aria-label*="aktualna cena"]'
      replace_old: z\xc5\x82
      replace_new: PLN
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: a[href*="/oferta/"] ul li img
      attribute_name: src
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: 'a[rel="next"]'
    action_before_search_pages_browsing_module:
      - name: click_action_module_and_scroll
        after_pause_time: 4
        css_selector: '[data-role="accept-consent"]'
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.allegro.pl/{}
    loading_delay: 7
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: meta[property="og:title"]
      attribute_name: content
    description_retriever_module:
      name: get_attribute_value
      css_selector: '[data-box-name="Description"]'
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: div[aria-label^="cena "]
      replace_old: z\xc5\x82
      replace_new: PLN
      attribute_name: textContent
    stock_retriever_module:
      name: get_attribute_value
      css_selector: '#cta-buttons-box div>div>div:last-child'
      regex: (\d+)
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: a[data-analytics-interaction-value="allSellersItemsLink"]
      attribute_name: href
      regex: uzytkownik/([^/]+)
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a[data-analytics-interaction-value="allSellersItemsLink"]
      attribute_name: href
      regex: .+uzytkownik/([^/]+)
    ships_from_retriever_module:
      name: get_key_value_list_from_different_elements
      clickable_css_selectors:
        - a[data-analytics-interaction-label="shipping_info"]
      key_css_selectors:
        - div[class="opbox-showoffer-delivery"] select#select option
      value_css_selectors:
        - div[class="opbox-showoffer-delivery"] select#select option
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: div[data-box-name="showoffer.gallery"]
      clickable_css_selector_2: div[data-role="app-container"] div[role="presentation"] > div > div > button:last-child
      picture_css_selector: div[data-box-name="showoffer.gallery"] img[src*="/original/"][role="presentation"]
      regex: (.+)
      attribute_name: src
      loading_delay: 3
      escape_popup_on_end: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        after_pause_time: 2
        before_pause_time: 4
        css_selector: button[data-role="accept-consent"]
      - name: click_action_module
        after_pause_time: 2
        before_pause_time: 4
        css_selector: a[data-analytics-interaction-value="modalClose_crossButton"]
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: 'https://allegro.pl/uzytkownik/{}'
    loading_delay: 12
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: option[value*="/uzytkownik/"]
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img._3fa59_YdF1Y, img._3fa59_Av84s
      attribute_name: src
      loading_delay: 5
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      clickable_css_selectors:
        - a[href*="/oceny"]
      key_css_selectors:
        - div[data-role="ratings"] div div:nth-of-type(1) div p
        - div[data-role="ratings"] div div:nth-of-type(2) div p
        - div[data-role="ratings"] div div:nth-of-type(3) div p
        - h1[data-role="recommends-percentage"]
        - img[alt="thumb up"]
        - img[alt="thumb down"]
        - div[data-role="account-info"] div p:nth-of-type(1)
      value_css_selectors:
        - div[data-role="ratings"] div div:nth-of-type(1) div div span
        - div[data-role="ratings"] div div:nth-of-type(2) div div span
        - div[data-role="ratings"] div div:nth-of-type(3) div div span
        - h1[data-role="recommends-percentage"]
        - img[alt="thumb up"] ~ p
        - img[alt="thumb down"] ~ p
        - div[data-role="account-info"] div p:nth-of-type(2)
      key_regex:
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
      value_regex:
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
      key_attributes:
        - textContent
        - textContent
        - textContent
        - data-role
        - alt
        - alt
        - textContent
      value_attributes:
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector:
          - '[data-role="accept-consent"]'
          - a[href*="/sklep"]
  archiving_options:
    click_on_elements:
      - button[data-role="accept-consent"]
