framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 3000
    take_screenshots: true
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://arena.pl/listing?search={}
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: '#c-mp button'
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div[class*="listGrid"] div[class*="containerWrapper"]  div[class*="contentWrapper"] a[class*="MuiLink"]
      regex: arena.pl\/(.*)
      load_more_results_module:
          name: click_on_next_page_module
          css_selector: nav[role="navigation"] a:last-of-type button
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div[class*="listGrid"] div[class*="containerWrapper"]  div[class*="contentWrapper"] a[class*="MuiLink"]
      regex: arena.pl\/(.*)
    listing_container_css_selector: div[class*="listGrid"] div[class*="containerWrapper"]
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: nav[role="navigation"] a:last-of-type button
    title_retriever_module:
      name: get_attribute_value
      css_selector: '#name'
    price_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="priceBox"]
      replace_old: zł
      replace_new: PLN
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div#sellerWrapper > p
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img[class*="imageBase"]
      attribute_name: src
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://arena.pl/{}
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: h1[class*="title"]
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div[id="description"]
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="priceContainer"] div[class*="priceBox"]
      attribute_name: textContent
      replace_old: zł
      replace_new: PLN
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: '#seller div[class*="sellerContainerSpecial"] p:nth-child(2)'
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: '#seller > div > a'
      attribute_name: href
    stock_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="ActionWrapper"] p[class*="caption"]
      attribute_name: textContent
      regex: (\d+)
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: ul[class*="react-multi-carousel-track "] li:first-of-type
      clickable_css_selector_2: .slick-slider button[class*="arrowCenterRight"]
      picture_css_selector: .slick-list .slick-active img[class*="mainImage"]
      attribute_name: src
      regex: (.+)
      escape_popup_on_end: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: 
          - '#c-mp button'
          - div[class*="1uvnrx3"] button.MuiButton-contained
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: 
          - '#c-mp button'
          - div[aria-label="seller tabs"]:first-of-type a:last-of-type
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="sellerContainerWrapper"] p[class*="name"]
    description_retriever_module:
      name: get_attribute_value
      css_selector: div[id="information"]
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div[class*="sellerContainerWrapper"] img
      attribute_name: src