include: craigslist.org.yaml
framework: 
    search_pages_browsing_module:
        search_page_urls_builder_module:
            search_page_url_templates:
                - 'https://bangladesh.craigslist.org/search/sss?query={}'
                - 'https://beijing.craigslist.org/search/sss?query={}'
                - 'https://chengdu.craigslist.org/search/sss?query={}'
                - 'https://chongqing.craigslist.org/search/sss?query={}'
                - 'https://dalian.craigslist.org/search/sss?query={}'
                - 'https://guangzhou.craigslist.org/search/sss?query={}'
                - 'https://hangzhou.craigslist.org/search/sss?query={}'
                - 'https://nanjing.craigslist.org/search/sss?query={}'
                - 'https://shanghai.craigslist.org/search/sss?query={}'
                - 'https://shenyang.craigslist.org/search/sss?query={}'
                - 'https://shenzhen.craigslist.org/search/sss?query={}'
                - 'https://wuhan.craigslist.org/search/sss?query={}'
                - 'https://xian.craigslist.org/search/sss?query={}'
                - 'https://micronesia.craigslist.org/search/sss?query={}'
                - 'https://hongkong.craigslist.org/search/sss?query={}'
                - 'https://ahmedabad.craigslist.org/search/sss?query={}'
                - 'https://bangalore.craigslist.org/search/sss?query={}'
                - 'https://bhubaneswar.craigslist.org/search/sss?query={}'
                - 'https://chandigarh.craigslist.org/search/sss?query={}'
                - 'https://chennai.craigslist.org/search/sss?query={}'
                - 'https://delhi.craigslist.org/search/sss?query={}'
                - 'https://goa.craigslist.org/search/sss?query={}'
                - 'https://hyderabad.craigslist.org/search/sss?query={}'
                - 'https://indore.craigslist.org/search/sss?query={}'
                - 'https://jaipur.craigslist.org/search/sss?query={}'
                - 'https://kerala.craigslist.org/search/sss?query={}'
                - 'https://kolkata.craigslist.org/search/sss?query={}'
                - 'https://lucknow.craigslist.org/search/sss?query={}'
                - 'https://mumbai.craigslist.org/search/sss?query={}'
                - 'https://pune.craigslist.org/search/sss?query={}'
                - 'https://surat.craigslist.org/search/sss?query={}'
                - 'https://jakarta.craigslist.org/search/sss?query={}'
                - 'https://tehran.craigslist.org/search/sss?query={}'
                - 'https://baghdad.craigslist.org/search/sss?query={}'
                - 'https://haifa.craigslist.org/search/sss?query={}'
                - 'https://jerusalem.craigslist.org/search/sss?query={}'
                - 'https://telaviv.craigslist.org/search/sss?query={}'
                - 'https://ramallah.craigslist.org/search/sss?query={}'
                - 'https://fukuoka.craigslist.org/search/sss?query={}'
                - 'https://hiroshima.craigslist.org/search/sss?query={}'
                - 'https://nagoya.craigslist.org/search/sss?query={}'
                - 'https://okinawa.craigslist.org/search/sss?query={}'
                - 'https://osaka.craigslist.org/search/sss?query={}'
                - 'https://sapporo.craigslist.org/search/sss?query={}'
                - 'https://sendai.craigslist.org/search/sss?query={}'
                - 'https://tokyo.craigslist.org/search/sss?query={}'
                - 'https://seoul.craigslist.org/search/sss?query={}'
                - 'https://kuwait.craigslist.org/search/sss?query={}'
                - 'https://beirut.craigslist.org/search/sss?query={}'
                - 'https://malaysia.craigslist.org/search/sss?query={}'
                - 'https://pakistan.craigslist.org/search/sss?query={}'
                - 'https://bacolod.craigslist.org/search/sss?query={}'
                - 'https://naga.craigslist.org/search/sss?query={}'
                - 'https://cdo.craigslist.org/search/sss?query={}'
                - 'https://cebu.craigslist.org/search/sss?query={}'
                - 'https://davaocity.craigslist.org/search/sss?query={}'
                - 'https://iloilo.craigslist.org/search/sss?query={}'
                - 'https://manila.craigslist.org/search/sss?query={}'
                - 'https://pampanga.craigslist.org/search/sss?query={}'
                - 'https://zamboanga.craigslist.org/search/sss?query={}'
                - 'https://singapore.craigslist.org/search/sss?query={}'
                - 'https://taipei.craigslist.org/search/sss?query={}'
                - 'https://bangkok.craigslist.org/search/sss?query={}'
                - 'https://dubai.craigslist.org/search/sss?query={}'
                - 'https://vietnam.craigslist.org/search/sss?query={}'
