framework:
  name: selenium_framework
  proxies:
    - name: proxyrack
    - name: iproyal/us
    - name: iproyal/lithuania
    - name: 123proxy
    - name: proxys.io/mobile/shared/ru
    - name: proxys.io/mobile/dedicated/ru
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 3000
    scroll_down_after_get_new_page: true
    loading_delay: 3
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.avito.ru/rossiya?q={}&s=104
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: a[data-marker="item-title"]
      regex: avito.ru\/(.*)$
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div[itemtype*="/Product"] header a
      regex: avito.ru\/(.*)$
      load_more_results_module:
        name: load_more_by_scrolling_module
        css_selector: '[data-marker="pagination-button/next"], div[role="group"] ~
          button'
    listing_container_css_selector: div[data-marker="item"]
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: a[data-marker="item-title"]
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: '[data-marker="item-price"]'
      replace_old: \xe2\x82\xbd
      replace_new: RUB
      trim_text: true
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="item-sellerInfo"]
      attribute_name: textContent
    location_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="geo-address"]
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img[itemprop="image"]
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: '[data-marker="pagination-button/next"], div[role="group"] ~ button'
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.avito.ru/{}
    take_screenshot: true
    loading_delay: 2
    title_retriever_module:
      name: get_attribute_value
      css_selector: .title-info-title-text
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: '[itemprop="description"]'
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="item-price-main"] span span'
      replace_old: \xe2\x82\xbd
      replace_new: ' RUB'
      attribute_name: textContent
      trim_text: true
    location_retriever_module:
      name: get_attribute_value
      css_selector: div[itemprop="address"]
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="seller-info-name"]>a'
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: '[class*="seller-info-name"]>a'
      attribute_name: href
    ships_from_retriever_module:
      name: get_key_value_list
      key_css_selector: div[itemprop="address"]
      value_css_selector: div[itemprop="address"]
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: div[class*="image-frame-wrapper"] img
      clickable_css_selector_2: '[data-marker="extended-gallery-frame/control-right"]'
      picture_css_selector: div[class*="styles-extended-img"] img
      regex: (.*)
      attribute_name: src
      loading_delay: 4
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: img[data-marker="avatar"], span[data-marker="avatar"] img
      attribute_name: alt
    description_retriever_module:
      name: get_attribute_value
      css_selector: section[class*="Widgets-text"]
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img[data-marker="avatar"], span[data-marker="avatar"] img
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      key_css_selectors:
        - div[class*="RatingLine-score"]
        - '[data-marker*="rate-detail"]'
        - span[data-marker="favorite-seller-counters"]
        - span[data-marker="registered"]
        - div[data-marker="badge-title-35"]
        - section[class*="Widgets-badgebar"] div div div:nth-of-type(1) div[data-marker*="badge-title"]
        - div[data-marker="badge-title-30"]
        - section[class*="Widgets-badgebar"] div div div:nth-of-type(3) div[data-marker*="badge-title"]
        - section[class*="Widgets-badgebar"] div div div:nth-of-type(4) div[data-marker*="badge-title"]
        - section[class*="Widgets-badgebar"] div div div:nth-of-type(5) div[data-marker*="badge-title"]
        - section[class*="Widgets-badgebar"] div div div:nth-of-type(6) div[data-marker*="badge-title"]
        - section[class*="Widgets-badgebar"] div div div:nth-of-type(7) div[data-marker*="badge-title"]
        - section[class*="Widgets-badgebar"] div div div:nth-of-type(8) div[data-marker*="badge-title"]
        - section[class*="Widgets-badgebar"] div div div:nth-of-type(9) div[data-marker*="badge-title"]
        - section[class*="Widgets-badgebar"] div div div:nth-of-type(10) div[data-marker*="badge-title"]
        - section[class*="Widgets-geo"]
      value_css_selectors:
        - div[class*="RatingLine-score"]
        - '[data-marker*="rate-detail"]'
        - span[data-marker="favorite-seller-counters"]
        - span[data-marker="registered"]
        - div[data-marker="badge-title-35"]
        - section[class*="Widgets-badgebar"] div div div:nth-of-type(1) div[data-marker*="badge-title"]
        - div[data-marker="badge-title-30"]
        - section[class*="Widgets-badgebar"] div div div:nth-of-type(3) div[data-marker*="badge-title"]
        - section[class*="Widgets-badgebar"] div div div:nth-of-type(4) div[data-marker*="badge-title"]
        - section[class*="Widgets-badgebar"] div div div:nth-of-type(5) div[data-marker*="badge-title"]
        - section[class*="Widgets-badgebar"] div div div:nth-of-type(6) div[data-marker*="badge-title"]
        - section[class*="Widgets-badgebar"] div div div:nth-of-type(7) div[data-marker*="badge-title"]
        - section[class*="Widgets-badgebar"] div div div:nth-of-type(8) div[data-marker*="badge-title"]
        - section[class*="Widgets-badgebar"] div div div:nth-of-type(9) div[data-marker*="badge-title"]
        - section[class*="Widgets-badgebar"] div div div:nth-of-type(10) div[data-marker*="badge-title"]
        - section[class*="Widgets-geo"] span[class*="desktop"]
      key_regex:
        - Rating
        - rate
        - seller-counters
        - registered
        - (title-\d+)
        - (title-\d+)
        - (title-\d+)
        - (title-\d+)
        - (title-\d+)
        - (title-\d+)
        - (title-\d+)
        - (title-\d+)
        - (title-\d+)
        - (title-\d+)
        - (title-\d+)
        - geo
      value_regex:
        - (.+)
        - (.+)
        - (.+)
        - (—Å .+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
      key_attributes:
        - class
        - class
        - data-marker
        - data-marker
        - data-marker
        - data-marker
        - data-marker
        - data-marker
        - data-marker
        - data-marker
        - data-marker
        - data-marker
        - data-marker
        - data-marker
        - data-marker
        - class
      value_attributes:
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector:
          - a[class*="showMoreButton"]
