framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    max_posts_to_browse: 3000
    loading_delay: 3
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.bestbuy.com/site/searchpage.jsp?&sp=-displaydate%20skuidsaas&st={}
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: div:not(.hidden)>.country-selection>a.us-link
        stop_css_selector: .sku-item-list>li.sku-item
        loading_timeout: 2
        after_pause_time: 4
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .sku-item-list>li.sku-item .sku-title>a
      regex: bestbuy.com\/site\/.+skuId\=(\d+)
      post_url_cleaning_module:
        query_string_to_keep:
          - skuId
    listing_container_css_selector: .sku-item-list>li.sku-item
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: '.sku-title>a'
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .sku-list-item-price .priceView-customer-price>span:first-child
      replace_old: \$
      replace_new: USD
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: a.image-link>img
      attribute_name: src
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: a.sku-list-page-next
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.bestbuy.com/site/{}.p
    take_screenshot: true
    loading_delay: 1
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: div:not(.hidden)>.country-selection>a.us-link
        stop_css_selector: .sku-title>h1
        loading_timeout: 2
        after_pause_time: 4
    title_retriever_module:
      name: get_attribute_value
      css_selector: .sku-title>h1
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .long-description-container>div
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[data-sticky-media-gallery] .priceView-customer-price>span:first-child'
      replace_old: \$
      replace_new: USD
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_by_clicking_thumbnails
      clickable_css_selector_1: .shop-media-gallery .primary-image-selected button
      clickable_css_selector: .shop-media-gallery-modal .scroll-area>div>ol>li>div>button
      picture_css_selector: .shop-media-gallery-modal .primary-media-wrapper>div img
      escape_popup_on_end: true
      attribute_name: src
      regex: (.+)
      loading_delay: 3