include: carousell.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://ca.carousell.com/search/{}?sort_by=3
        - https://ca.carousell.com/search/{}
    post_identifiers_retriever_module:
      regex: ca\.carousell\.com\/p\/(.+)
    poster_post_identifiers_retriever_module:
      regex: ca\.carousell\.com\/p\/(.+)
    price_retriever_module:
      replace_old: C\$
      replace_new: CAD
  post_information_retriever_module:
    post_url_template: https://ca.carousell.com/p/{}
    vendor_retriever_module:
      regex: https://ca\.carousell\.com/u/(.+)/$
    price_retriever_module:
      replace_old: C\$
      replace_new: CAD