include: carousell.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.carousell.com.hk/search/{}?sort_by=3
        - https://www.carousell.com.hk/search/{}
    post_identifiers_retriever_module:
      regex: www\.carousell\.com\.hk\/p\/(.+)
    poster_post_identifiers_retriever_module:
      regex: www\.carousell\.com\.hk\/p\/(.+)
    price_retriever_module:
      replace_old: HK\$
      replace_new: HKD
  post_information_retriever_module:
    post_url_template: https://www.carousell.com.hk/p/{}
    vendor_retriever_module:
      regex: https://www\.carousell\.com\.hk/u/(.+)/$
    price_retriever_module:
      replace_old: HK\$
      replace_new: HKD