include: carrefour-me.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.carrefourksa.com/mafsau/en/v4/search?keyword={}
    post_identifiers_retriever_module:
      regex: carrefourksa.com\/mafsau\/(.+)
  post_information_retriever_module:
    post_url_template: https://www.carrefourksa.com/mafsau/{}