framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 3000
    loading_delay: 1
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://carrefour.ro/catalogsearch/result/?q={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .products>.product .productItem-name>a
      regex: carrefour.ro\/produse\/(.+)
    listing_container_css_selector: .products>.product
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .productItem-name>a
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .products>.product .price-final
      replace_old: (.+)
      replace_new: \g<1> RON
      attribute_name: 'data-price-amount'
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img.product-image-photo
      attribute_name: src
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: .pages .pages-item-next>a
      loading_delay: 4
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: 'button#onetrust-accept-btn-handler'
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://carrefour.ro/produse/{}
    take_screenshot: true
    loading_delay: 3
    title_retriever_module:
      name: get_attribute_value
      css_selector: .product-info-main .page-title
    description_retriever_module:
      name: get_attribute_value
      css_selector: '#content-description>div'
    price_retriever_module:
      name: get_attribute_value
      css_selector: .product-info-main .price-final_price  span[itemprop="price"]
      replace_old: (.+)
      replace_new: \g<1> RON
      attribute_name: 'data-price-amount'
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_2: '.gallery-wrapper .gallery-for .slick-next'
      picture_css_selector: '.gallery-wrapper .gallery-for .slick-active>img'
      attribute_name: src
      regex: (.+)
      loading_delay: 1
      escape_popup_on_end: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: button#onetrust-accept-btn-handler