framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 3000
    loading_delay: 2
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://drive.carrefour.be/nl/search?text={}
        - https://drive.carrefour.be/fr/search?text={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .product__listing>.product-item .product-name>a
      regex: carrefour.be\/(.+)
    listing_container_css_selector: .product__listing>.product-item
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .product-name>a
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .priceinfo>div.baseprice
      replace_old: \€
      replace_new: EUR
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .product-img-field>div>a img
      attribute_name: src
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: ul.pagination>li.pagination-next>a
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: 'button#onetrust-accept-btn-handler'
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://drive.carrefour.be/{}
    take_screenshot: true
    loading_delay: 3
    title_retriever_module:
      name: get_attribute_value
      css_selector: .pdp-titleSection .prod-title
    description_retriever_module:
      name: get_attribute_value
      css_selector: div.proddesc-sec
    price_retriever_module:
      name: get_attribute_value
      css_selector: div.pdp-priceSection .prod-price-sec>.prod-price>span
      replace_old: \€
      replace_new: EUR
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: '.pdp-left-section-carousel #image-gallery>div.active:not(.clone)'
      clickable_css_selector_2: '#myModal>.modal-dialog a.lSNext>span'
      picture_css_selector: '#myModal>.modal-dialog div.lslide.active source:first-child'
      attribute_name: srcset
      regex: (.+)
      escape_popup_on_end: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: button#onetrust-accept-btn-handler