include: cdon.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://cdon.dk/catalog/search?q={}
    post_identifiers_retriever_module:
      regex: (?<=cdon.dk\/)(.+)$
    price_retriever_module:
      replace_old: kr
      replace_new: DKK
  post_information_retriever_module:
    post_url_template: https://cdon.se/{}
    price_retriever_module:
      replace_old: kr
      replace_new: SEK