framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 3000
    loading_delay: 1
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.conforama.it/catalogsearch/result/?q={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '.product-items>li.product-item .image-container>a'
      regex: conforama.it\/(.+)
    listing_container_css_selector: '.product-items>li.product-item'
    title_retriever_module:
      name: get_multiple_text_content_and_concatenate
      attribute_name: textContent
      css_selectors:
        - .product-item-details>strong
      has_multiple_items_in_same_selector: true
      replace_old: \n
      replace_new: ' '
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .product-item-details div.price-final_price span.price
      replace_old: '\€'
      replace_new: 'EUR'
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .image-container img.product-image-photo
      attribute_name: src
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: .pages>ul>li>a.next
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector:
          - 'button.iubenda-cs-accept-btn'
          - '#bio_ep_close'
  post_information_retriever_module:
    name: post_information_retriever_with_creation_of_a_new_driver_for_each_post_module
    post_url_template: https://www.conforama.it/{}
    take_screenshot: true
    loading_delay: 1
    title_retriever_module:
      name: get_attribute_value
      css_selector: .product-info-main>.title-addition-wrapper
    description_retriever_module:
      name: get_attribute_value
      css_selector: '#description div.value'
      loading_timeout: 0.1
    price_retriever_module:
      name: get_attribute_value
      css_selector: .product-info-main [data-price-type="finalPrice"]>span
      replace_old: '\€'
      replace_new: 'EUR'
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .mc-delivTop>*
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .mc-delivTop>a
      attribute_name: href
      loading_timeout: 0.1
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: .fotorama__stage__shaft>div.fotorama__active
      clickable_css_selector_2: '.fotorama__stage>.fotorama__arr--next'
      picture_css_selector: '.fotorama__stage__shaft>.fotorama__stage__frame.fotorama__active'
      attribute_name: href
      regex: (.+)
      escape_popup_on_end: true
      loading_delay: 2
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector:
          - 'button.iubenda-cs-accept-btn'
          - '#bio_ep_close'