include: daraz.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.daraz.com.bd/catalog/?q={}
    poster_post_identifiers_retriever_module:
      regex: daraz.com.bd\/products\/.*(i\d+\-s\d+).html
    post_identifiers_retriever_module:
      regex: daraz.com.bd\/products\/.*(i\d+\-s\d+).html
    price_retriever_module:
      replace_old: \৳
      replace_new: BDT
  post_information_retriever_module:
    post_url_template: https://www.daraz.com.bd/products/{}.html
    price_retriever_module:
      replace_old: \৳
      replace_new: BDT
  poster_information_retriever_module:
    poster_url_template: https://www.daraz.com.bd/shop/{}