include: depop.yaml
framework:
  driver_initialization_module:
    cookies:
      properties:
        location: au
  search_pages_browsing_module:
    price_retriever_module:
      replace_old: A\$
      replace_new: AUD
  post_information_retriever_module:
    price_retriever_module:
      replace_old: A\$
      replace_new: AUD
