framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
    override_user_agent: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 3000
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.donedeal.ie/all?words={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: ul[class*="Listings__List"]>li[class*="Desktop"]>a
      regex: donedeal.ie\/(.*)$
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: ul[class*="Listings__List"]>li[class*="Desktop"]>a , li>a.card__link
      regex: donedeal.ie\/(.*)$
    listing_container_css_selector: ul[class*="Listings__List"]>li[class*="Desktop"]
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: p[class*="Card__Title"]
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: '[class*="Card__PriceLabelWrapper"]+p'
      replace_old: \€
      replace_new: 'EUR '
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="Card__Header"]>div>div>p'
      attribute_name: textContent
    location_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="Card__KeyInfoList"]>li:nth-child(2)'
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[class*="Card__ImageContainer"]>div>picture>img'
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: button[data-testid="go-to-next-page"] , button.next
      scroll_down_before_click: true
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: button[data-tracking="cc-accept"]
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.donedeal.ie/{}
    take_screenshot: true
    loading_delay: 4
    title_retriever_module:
      name: get_attribute_value
      css_selector: h1[class*="Title"]
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      clickable_css_selector: div[data-testid="see-more-text"]
      css_selector: p[class*="InfoPanel__StyledText"]
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: p[class*="Price__CurrentPrice"]
      replace_old: \€
      replace_new: 'EUR '
      attribute_name: textContent
    location_retriever_module:
      name: get_attribute_value
      css_selector: div[data-testid="title-box"] ul[class*="InfoTitle__SubtitleList"]>li:last-child
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div[data-testid="side-seller-panel"] p[class*="Title"]
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a[data-testid="view-all-ads"]
      attribute_name: href
      post_url_cleaning_module:
        skip_query_string_cleaning: true
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: button[class*="GalleryUiElements__Next"]
      clickable_css_selector_2: div.ReactModal__Overlay button[class*="GalleryUiElements__Next"]
      picture_css_selector: img[class*="GallerySlide__Img"]
      regex: (.+)
      attribute_name: src
      loading_delay: 3
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: button[data-tracking="cc-accept"]
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: h1.dealer-showroom-title>span
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div.dealer-showroom-content-about-text
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div.dealer-showroom-logo>img
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      key_css_selectors:
        - .dealer-address-container
        - .dealer-address-container a[href*="map"]
      value_css_selectors:
        - .dealer-address-container
        - .dealer-address-container a[href*="map"]
      key_regex:
        - (.+)
        - (.+)
      value_regex:
        - (.+)
        - (.+)
      key_attributes:
        - itemprop
        - textContent
      value_attributes:
        - textContent
        - href
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: button[data-tracking="cc-accept"]
