framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    max_posts_to_browse: 3000
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.dx.com/s/{}?cateId=0&sortBy=NW
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '#proList .product-list-item p.title a'
      regex: dx.com/p/(.+)
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: '[class="next"]'
    listing_container_css_selector: '#proList .product-list-item'
    title_retriever_module:
      name: get_attribute_value
      css_selector: p.title
    price_retriever_module:
      name: get_attribute_value
      css_selector: .sale-price
      replace_old: US \$
      replace_new: USD
    pictures_retriever_module:
      name: get_pictures_from_attribute_with_replace_regex
      css_selector: .product-img img
      attribute_name: src
      replace_old_regex: (_\d+x\d+)
      replace_new: ''
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.dx.com/p/{}
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: h1.pinfo-title
    description_retriever_module:
      name: get_attribute_value
      css_selector: '#productDescript'
    price_retriever_module:
      name: get_attribute_value
      css_selector: span.sale-price
      replace_old: US[^\$]+\$
      replace_new: USD
    ships_to_retriever_module:
      name: get_key_value_list
      clickable_css_selector: span.logistics-country
      key_css_selector: ul.country-menu-drop li[key] a
      value_css_selector: ul.country-menu-drop li[key] a
    pictures_retriever_module:
      name: get_pictures_from_attribute_with_replace_regex
      css_selector: ul.product-small-images li img
      attribute_name: src
      replace_old_regex: (_\d+x\d+)
      replace_new: ''
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: a[data-id="#productDescript"]
