include: emag.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.emag.bg/search/{}?ref=effective_search
    poster_post_identifiers_retriever_module:
      regex: emag.bg\/(.+)$
    post_identifiers_retriever_module:
      regex: emag.bg\/(.+)$
    price_retriever_module:
      replace_old: \xd0\xbb\xd0\xb2.
      replace_new: BGN
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.emag.bg/{}
    price_retriever_module:
      replace_old: \xd0\xbb\xd0\xb2.
      replace_new: BGN