include: craigslist.org.yaml
framework: 
    search_pages_browsing_module:
        search_page_urls_builder_module:
            search_page_url_templates:
                - 'https://vienna.craigslist.org/search/sss?query={}'
                - 'https://brussels.craigslist.org/search/sss?query={}'
                - 'https://bulgaria.craigslist.org/search/sss?query={}'
                - 'https://zagreb.craigslist.org/search/sss?query={}'
                - 'https://prague.craigslist.org/search/sss?query={}'
                - 'https://copenhagen.craigslist.org/search/sss?query={}'
                - 'https://helsinki.craigslist.org/search/sss?query={}'
                - 'https://bordeaux.craigslist.org/search/sss?query={}'
                - 'https://rennes.craigslist.org/search/sss?query={}'
                - 'https://grenoble.craigslist.org/search/sss?query={}'
                - 'https://lille.craigslist.org/search/sss?query={}'
                - 'https://loire.craigslist.org/search/sss?query={}'
                - 'https://lyon.craigslist.org/search/sss?query={}'
                - 'https://marseilles.craigslist.org/search/sss?query={}'
                - 'https://montpellier.craigslist.org/search/sss?query={}'
                - 'https://cotedazur.craigslist.org/search/sss?query={}'
                - 'https://rouen.craigslist.org/search/sss?query={}'
                - 'https://paris.craigslist.org/search/sss?query={}'
                - 'https://strasbourg.craigslist.org/search/sss?query={}'
                - 'https://toulouse.craigslist.org/search/sss?query={}'
                - 'https://berlin.craigslist.org/search/sss?query={}'
                - 'https://bremen.craigslist.org/search/sss?query={}'
                - 'https://cologne.craigslist.org/search/sss?query={}'
                - 'https://dresden.craigslist.org/search/sss?query={}'
                - 'https://dusseldorf.craigslist.org/search/sss?query={}'
                - 'https://essen.craigslist.org/search/sss?query={}'
                - 'https://frankfurt.craigslist.org/search/sss?query={}'
                - 'https://hamburg.craigslist.org/search/sss?query={}'
                - 'https://hannover.craigslist.org/search/sss?query={}'
                - 'https://heidelberg.craigslist.org/search/sss?query={}'
                - 'https://kaiserslautern.craigslist.org/search/sss?query={}'
                - 'https://leipzig.craigslist.org/search/sss?query={}'
                - 'https://munich.craigslist.org/search/sss?query={}'
                - 'https://nuremberg.craigslist.org/search/sss?query={}'
                - 'https://stuttgart.craigslist.org/search/sss?query={}'
                - 'https://athens.craigslist.org/search/sss?query={}'
                - 'https://budapest.craigslist.org/search/sss?query={}'
                - 'https://reykjavik.craigslist.org/search/sss?query={}'
                - 'https://dublin.craigslist.org/search/sss?query={}'
                - 'https://bologna.craigslist.org/search/sss?query={}'
                - 'https://florence.craigslist.org/search/sss?query={}'
                - 'https://genoa.craigslist.org/search/sss?query={}'
                - 'https://milan.craigslist.org/search/sss?query={}'
                - 'https://naples.craigslist.org/search/sss?query={}'
                - 'https://perugia.craigslist.org/search/sss?query={}'
                - 'https://rome.craigslist.org/search/sss?query={}'
                - 'https://sardinia.craigslist.org/search/sss?query={}'
                - 'https://sicily.craigslist.org/search/sss?query={}'
                - 'https://torino.craigslist.org/search/sss?query={}'
                - 'https://venice.craigslist.org/search/sss?query={}'
                - 'https://luxembourg.craigslist.org/search/sss?query={}'
                - 'https://amsterdam.craigslist.org/search/sss?query={}'
                - 'https://oslo.craigslist.org/search/sss?query={}'
                - 'https://warsaw.craigslist.org/search/sss?query={}'
                - 'https://faro.craigslist.org/search/sss?query={}'
                - 'https://lisbon.craigslist.org/search/sss?query={}'
                - 'https://porto.craigslist.org/search/sss?query={}'
                - 'https://bucharest.craigslist.org/search/sss?query={}'
                - 'https://moscow.craigslist.org/search/sss?query={}'
                - 'https://stpetersburg.craigslist.org/search/sss?query={}'
                - 'https://alicante.craigslist.org/search/sss?query={}'
                - 'https://baleares.craigslist.org/search/sss?query={}'
                - 'https://barcelona.craigslist.org/search/sss?query={}'
                - 'https://bilbao.craigslist.org/search/sss?query={}'
                - 'https://cadiz.craigslist.org/search/sss?query={}'
                - 'https://canarias.craigslist.org/search/sss?query={}'
                - 'https://granada.craigslist.org/search/sss?query={}'
                - 'https://madrid.craigslist.org/search/sss?query={}'
                - 'https://malaga.craigslist.org/search/sss?query={}'
                - 'https://sevilla.craigslist.org/search/sss?query={}'
                - 'https://valencia.craigslist.org/search/sss?query={}'
                - 'https://stockholm.craigslist.org/search/sss?query={}'
                - 'https://basel.craigslist.org/search/sss?query={}'
                - 'https://bern.craigslist.org/search/sss?query={}'
                - 'https://geneva.craigslist.org/search/sss?query={}'
                - 'https://lausanne.craigslist.org/search/sss?query={}'
                - 'https://zurich.craigslist.org/search/sss?query={}'
                - 'https://istanbul.craigslist.org/search/sss?query={}'
                - 'https://ukraine.craigslist.org/search/sss?query={}'
                - 'https://aberdeen.craigslist.org/search/sss?query={}'
                - 'https://bath.craigslist.org/search/sss?query={}'
                - 'https://belfast.craigslist.org/search/sss?query={}'
                - 'https://birmingham.craigslist.org/search/sss?query={}'
                - 'https://brighton.craigslist.org/search/sss?query={}'
                - 'https://bristol.craigslist.org/search/sss?query={}'
                - 'https://cambridge.craigslist.org/search/sss?query={}'
                - 'https://cardiff.craigslist.org/search/sss?query={}'
                - 'https://coventry.craigslist.org/search/sss?query={}'
                - 'https://derby.craigslist.org/search/sss?query={}'
                - 'https://devon.craigslist.org/search/sss?query={}'
                - 'https://dundee.craigslist.org/search/sss?query={}'
                - 'https://norwich.craigslist.org/search/sss?query={}'
                - 'https://eastmids.craigslist.org/search/sss?query={}'
                - 'https://edinburgh.craigslist.org/search/sss?query={}'
                - 'https://essex.craigslist.org/search/sss?query={}'
                - 'https://glasgow.craigslist.org/search/sss?query={}'
                - 'https://hampshire.craigslist.org/search/sss?query={}'
                - 'https://kent.craigslist.org/search/sss?query={}'
                - 'https://leeds.craigslist.org/search/sss?query={}'
                - 'https://liverpool.craigslist.org/search/sss?query={}'
                - 'https://london.craigslist.org/search/sss?query={}'
                - 'https://manchester.craigslist.org/search/sss?query={}'
                - 'https://newcastle.craigslist.org/search/sss?query={}'
                - 'https://nottingham.craigslist.org/search/sss?query={}'
                - 'https://oxford.craigslist.org/search/sss?query={}'
                - 'https://sheffield.craigslist.org/search/sss?query={}'