framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 3000
    take_screenshots: true
    loading_delay: 3
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.flanco.ro/catalogsearch/result/?q={}
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: '#cc-wrapper a.x-agree'
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: ol.product-items li.product-item .product-item-name a
      regex: flanco.ro/(.*)
    listing_container_css_selector: ol.product-items li.product-item
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: '.columns > #product-pagination ul.pages-items li:last-of-type'
    title_retriever_module:
      name: get_attribute_value
      css_selector: .product-item-name a
    price_retriever_module:
      name: get_attribute_value
      css_selector: .price-final_price :is(.special-price, .singlePrice) span.price
      replace_old: lei
      replace_new: RON
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .product-item-photo img
      attribute_name: src
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.flanco.ro/{}
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: h1.page-title
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: .additional-content .description
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: .product-info-main .price-final_price :is(.special-price, .singlePrice) span.price
      attribute_name: textContent
      replace_old: lei
      replace_new: RON
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: div#gallery figure#productImage:first-of-type img
      clickable_css_selector_2: button[class*="arrow--right"]
      picture_css_selector: .pswp__item img.pswp__img:last-of-type
      attribute_name: src
      regex: (.+)
      loading_delay: 1.5
      escape_popup_on_end: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: '#cc-wrapper a.x-agree'