include: fruugo.yaml
framework:
    search_pages_browsing_module:
      search_page_urls_builder_module:
        search_page_url_templates:
          - https://www.fruugobahrain.com/search/?q={}&language=en
      poster_post_identifiers_retriever_module:
        regex: fruugobahrain.com\/(.+)$
      post_identifiers_retriever_module:
        regex: fruugobahrain.com\/(.+)$
    post_information_retriever_module:
      name: classic_post_information_retriever_module
      post_url_template: https://www.fruugobahrain.com/{}?language=en