include: fruugo.yaml
framework:
    search_pages_browsing_module:
      search_page_urls_builder_module:
        search_page_url_templates:
          - https://www.fruugo.us/search/?q={}
      poster_post_identifiers_retriever_module:
        regex: fruugo.us\/(.+)$
      post_identifiers_retriever_module:
        regex: fruugo.us\/(.+)$
      price_retriever_module:
        replace_old: \$
        replace_new: USD
    post_information_retriever_module:
      post_url_template: https://www.fruugo.us/{}
      price_retriever_module:
        replace_old: \$
        replace_new: USD