include: fruugo.yaml
framework:
    search_pages_browsing_module:
      search_page_urls_builder_module:
        search_page_url_templates:
          - https://www.fruugo.ca/search/?q={}
      poster_post_identifiers_retriever_module:
        regex: fruugo.ca\/(.+)$
      post_identifiers_retriever_module:
        regex: fruugo.ca\/(.+)$
      price_retriever_module:
        replace_old: \$
        replace_new: CAD
    post_information_retriever_module:
      name: classic_post_information_retriever_module
      post_url_template: https://www.fruugo.ca/{}
      price_retriever_module:
        replace_old: \$
        replace_new: CAD