include: fruugo.yaml
framework:
    search_pages_browsing_module:
      search_page_urls_builder_module:
        search_page_url_templates:
          - https://www.fruugochina.com/search/?q={}&language=en
      poster_post_identifiers_retriever_module:
        regex: fruugochina.com\/(.+)$
      post_identifiers_retriever_module:
        regex: fruugochina.com\/(.+)$
      price_retriever_module:
        replace_old: CN\¥
        replace_new: CNY
    post_information_retriever_module:
      name: classic_post_information_retriever_module
      post_url_template: https://www.fruugochina.com/{}?language=en
      price_retriever_module:
        replace_old: CN\¥
        replace_new: CNY