include: fruugo.yaml
framework:
    search_pages_browsing_module:
      search_page_urls_builder_module:
        search_page_url_templates:
          - https://www.fruugo.co.za/search/?q={}&language=en
      poster_post_identifiers_retriever_module:
        regex: fruugo.co.za\/(.+)$
      post_identifiers_retriever_module:
        regex: fruugo.co.za\/(.+)$
      price_retriever_module:
        replace_old: R
        replace_new: ZAR
    post_information_retriever_module:
      name: classic_post_information_retriever_module
      post_url_template: https://www.fruugo.co.za/{}?language=en
      price_retriever_module:
        replace_old: R
        replace_new: ZAR