include: qoo10.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://global.shopclues.com/s/?keyword={}
    post_identifiers_retriever_module:
      regex: shopclues.com\/item\/(.+)$
    price_retriever_module:
      replace_old: \₹
      replace_new: INR
    poster_post_identifiers_retriever_module:
      regex: \.com\/item\/(.+)$
      action_before_poster_post_identifiers_module:
      - name: click_action_module
        css_selector: a#btn_allitem
        after_pause_time: 3
      price_retriever_module:
        replace_old: \₹
        replace_new: INR