framework:
  name: selenium_framework
  proxies:
    - name: proxyrack
    - name: iproyal/us
    - name: iproyal/lithuania
    - name: 123proxy
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    max_posts_to_browse: 3000
    loading_delay: 4
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.gumtree.co.za/search?search_category=all&q={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '#srpAds .related-item div.title>a'
      regex: gumtree.co.za\/(.+)$
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '#sellerAds .related-item div.title>a'
      regex: gumtree.co.za\/(.+)$
    listing_container_css_selector: '#srpAds .related-item , #sellerAds .related-item'
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: div.title>a
    price_retriever_module:
      name: get_attribute_value
      css_selector: div.price>span
      replace_old: R
      replace_new: ZAR
    location_retriever_module:
      name: get_attribute_value
      css_selector: .location>span:first-of-type
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div.img-container img
      attribute_name: src
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: '#pagination a.icon-pagination-right'
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: button.confirm
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.gumtree.co.za/{}
    take_screenshot: true
    loading_delay: 3
    title_retriever_module:
      name: get_attribute_value
      css_selector: div.ad-info div.title
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div.ad-info div.description-content
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: div.ad-info div.price .ad-price
      replace_old: R
      replace_new: ZAR
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div.seller-name
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a.seller-link
      attribute_name: href
    location_retriever_module:
      name: get_attribute_value
      css_selector: div.ad-info div.location
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: div.vip-gallery>div.revip-img-gallery div.gallery-img:first-child
      clickable_css_selector_2: '#vip-gallery>div.vip-img-carousel div.next'
      loading_delay: 2.5
      picture_css_selector: div.vip-img-carousel div.gallery-area  picture>img[class=" lazyloaded"]
      attribute_name: src
      regex: (.+)
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: button.confirm
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: https://www.gumtree.co.za/u-seller-listings/{}
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: div.seller-name
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute_with_replace
      css_selector: div.seller-profile>div
      attribute_name: style
      regex: url\((.+)\)
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      key_css_selectors:
        - div[class="stats-info"]
        - div.seller-stats>div.stats-info:nth-child(1)
        - div.seller-stats>div.stats-info:nth-child(2)
        - div.seller-badge
      value_css_selectors:
        - div[class="stats-info"]
        - div.seller-stats>div.stats-info:nth-child(1)
        - div.seller-stats>div.stats-info:nth-child(2)
        - div.seller-badge>div>div
      key_regex:
        - (.+?)\d
        - (.+?)\d
        - (.+?)\d
        - badge
      value_regex:
        - (\d+.*)
        - \d+
        - \d+
        - .+
      key_attributes:
        - textContent
        - textContent
        - textContent
        - class
      value_attributes:
        - textContent
        - textContent
        - textContent
        - textContent
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: button.confirm
