framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 3000
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.gunbroker.com/All/search?Keywords={}&Sort=13
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: 
          - button#onetrust-accept-btn-handler
          - button#ltkpopup-age-proceed
        after_pause_time: 1
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div.listing div.search-title a
      regex: gunbroker.com\/item\/(.*)
      action_before_poster_post_identifiers_module:
        - name: click_action_module
          css_selector: 
            - button#onetrust-accept-btn-handler
            - button#ltkpopup-age-proceed
            - div.ltkpopup-no-thanks button
            - a#seller-items-for-sale
      load_more_results_module:
        name: click_on_next_page_module
        css_selector: div#resultsPagination a.nextPage
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div.listing div.search-title a
      regex: gunbroker.com\/item\/(.*)
    listing_container_css_selector: div#resultsSection div.listing 
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: div#resultsPagination a.nextPage
    title_retriever_module:
      name: get_attribute_value
      css_selector: div.search-title a
    price_retriever_module:
      name: get_attribute_value
      css_selector: div.auction-wrap a
      replace_old: \$
      replace_new: 'USD '
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div.listing-seller > div > span:first-of-type a
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: div.listing-seller > div > span:first-of-type a
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div.listing-image
      attribute_name: style
      regex: 'url\(\"(.+)\"'
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.gunbroker.com/item/{}
    title_retriever_module:
      name: get_attribute_value
      css_selector: h1#divTitle
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div#item-description div.item-description-container
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: .buy-box-wrapper div.item-info-wrapper:nth-of-type(2) div.value
      attribute_name: textContent
      replace_old: \$
      replace_new: 'USD '
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div.seller-details span.user-name
      attribute_name: textContent
      exclude_children: true
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: div.seller-details span.user-name a
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: a#view-larger-images span
      clickable_css_selector_2: div#carousel-modal-view-item a[data-slide="next"]
      picture_css_selector: div#carousel-modal-view-item div.active img
      attribute_name: src
      regex: (.+)
      escape_popup_on_end: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: 
          - button#onetrust-accept-btn-handler
          - button#ltkpopup-age-proceed
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: div.feedback-overview span.user-name
      attribute_name: textContent
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: 
          - button#onetrust-accept-btn-handler
          - button#ltkpopup-age-proceed