framework:
  name: selenium_framework
  proxies:
    - name: proxyrack
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    max_posts_to_browse: 3000
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: a.btnMoreLink
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://shopping.interpark.com/shopSearch.do?page=1&q={}&sort=date-desc
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: 'ul.default li.item a'
      regex: shopping.interpark.com/product/productInfo.do\?prdNo\=(\d+)
      post_url_cleaning_module:
        query_string_to_keep:
          - prdNo
      listing_container_css_selector: 'ul.default li.item'
      title_retriever_module:
        name: get_attribute_value
        css_selector: p.name
      price_retriever_module:
        name: get_attribute_value
        css_selector: span.salePrice
        regex: '[^\d\,\.]+([\d\,\.]+.+)'
        trim_text: true
        replace_old: '\xec\x9b\x90.*'
        replace_new: KRW
      pictures_retriever_module:
        name: get_pictures_from_attribute
        css_selector: .productImg img
        attribute_name: src
      load_more_results_module:
        name: load_more_by_scrolling_module
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: 'ul#normalList li.goods div a'
      regex: shopping.interpark.com/product/productInfo.do\?prdNo\=(\d+)
      post_url_cleaning_module:
        query_string_to_keep:
          - prdNo
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: a.next
    listing_container_css_selector: 'ul#normalList li.goods'
    title_retriever_module:
      name: get_attribute_value
      css_selector: a.name
    price_retriever_module:
      name: get_attribute_value
      css_selector: span.won
      replace_old: ([^\d\,\.]+\xec\x9b\x90.*)
      replace_new: KRW
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: span.cname
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: span.cname a
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .imgBox img
      attribute_name: src
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://shopping.interpark.com/product/productInfo.do?prdNo={}
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: '#productName'
    description_retriever_module:
      name: get_attribute_value
      css_selector: '#tab1'
    price_retriever_module:
      name: get_attribute_value
      css_selector: span.salePrice
      regex: '[^\d\,\.]+([\d\,\.]+.+)'
      trim_text: true
      replace_old: '\xec\x9b\x90.*'
      replace_new: KRW
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .sellerName a
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .sellerName a
      attribute_name: href
      regex: store.interpark.com/(.+)
    ships_from_retriever_module:
      name: get_key_value_list
      key_css_selector: .originMark span.guideText
      value_css_selector: .originMark span.guideText
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_2: a.bx-next
      picture_css_selector: '.viewImage li:not(li[style*="display: none"]) img'
      regex: (.+)
      attribute_name: src
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: 'https://store.interpark.com/{}'
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .storeName h1
    description_retriever_module:
      name: get_attribute_value
      css_selector: p.sellerGreeting
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[class="storeIcon"] img'
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      key_css_selectors:
        - .sellerIcon
        - .sellerService ul li:nth-of-type(1)
        - .sellerService ul li:nth-of-type(2)
      value_css_selectors:
        - .sellerIcon
        - .sellerService ul li:nth-of-type(1) span
        - .sellerService ul li:nth-of-type(2) span
      key_regex:
        - (.+)
        - '[^\d]+'
        - '[^\d]+'
      value_regex:
        - (.+)
        - (.+)
        - (.+)
      key_attributes:
        - class
        - textContent
        - textContent
      value_attributes:
        - textContent
        - textContent
        - textContent
