include: jiji.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://jiji.com.gh/search?query={}&sort=new
    post_identifiers_retriever_module:
      regex: jiji.com.gh\/(.+)
    poster_post_identifiers_retriever_module:
      regex: jiji.com.gh\/(.+)
    price_retriever_module:
      replace_old: \₵
      replace_new: S
  post_information_retriever_module:
    post_url_template: https://jiji.com.gh/{}
    price_retriever_module:
      replace_old: \₵
      replace_new: S