framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    max_posts_to_browse: 3000
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://kream.co.kr/search?keyword={}&sort=date_released
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '.product_card a'
      regex: kream.co.kr/products/(.+)
    load_more_results_module:
      name: load_more_by_scrolling_module
    listing_container_css_selector: '.product_card'
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[class="name"]'
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[class="amount"]'
      replace_old: \xec\x9b\x90
      replace_new: KRW
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[class*="product_img"] img'
      attribute_name: src
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://kream.co.kr/products/{}
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: .main_title_box [class="title"]
    price_retriever_module:
      name: get_attribute_value
      css_selector: .detail_price .amount
      replace_old: \xec\x9b\x90
      replace_new: KRW
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .slide_item picture.product_img img
      attribute_name: src
