framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    undetected_driver: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 3000
    loading_delay: 8
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '#productList>.pl-product a.pl-product-link'
      action_before_poster_post_identifiers_module:
        - name: click_action_module
          css_selector: 'a.vendorHeader_linkShop'
          after_pause_time: 3
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '#productList>.pl-product a.pl-product-link'
    listing_container_css_selector: '#productList>.pl-product'
    title_retriever_module:
      name: get_multiple_text_content_and_concatenate
      attribute_name: textContent
      css_selectors:
        - div.product-brand
        - div.product-title
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .product-price-container
      trim_text: true
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img.pl-image
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: .pl-pagination-element#next
      loading_delay: 4
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    take_screenshot: true
    loading_delay: 3
    title_retriever_module:
      name: get_multiple_text_content_and_concatenate
      attribute_name: textContent
      css_selectors:
        - .pdp-title-zone .pdp-brand
        - .pdp-title-zone .pdp-title
    description_retriever_module:
      name: get_attribute_value
      css_selector: div#mainProductDescription
      exclude_children: true
    price_retriever_module:
      name: get_attribute_value
      css_selector: .price-block .price
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .name-vendor
      loading_timeout: 0.1
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .name-vendor>a
      attribute_name: href
      loading_timeout: 0.1
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: '.mainMedia_imageContainer img'
      clickable_css_selector_2: '#zoomContainer.popin .pdp-zoom-next'
      picture_css_selector: '#zoomContainer.popin>img'
      attribute_name: src
      regex: (.+)
      loading_delay: 2
      escape_popup_on_end: true
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: button#popin_tc_privacy_button_2
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .vendorHeader_informations_name
    description_retriever_module:
      name: get_attribute_value
      css_selector: .vendorHeader_description
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '.vendorHeader_zoneImg>img'
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: '#tab1content .vendorTabs_container_information>p>strong , #vendor-data .vendorHeader_informations>p'
      value_css_selector: '#tab1content .vendorTabs_container_information>p , #vendor-data .vendorHeader_informations>p>span'
      value_regex: '\:(.+)'
      key_regex: '(.+)\:'