include: laredoute.yaml
framework:
  proxies:
    - name: iproyal/us
    - name: iproyal/lithuania
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.laredoute.com/psrch/psrch.aspx?kwrd={}
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector:
          - .glControls>input[data-action="Close"]
          - button#popin_tc_privacy_button_2
        after_pause_time: 2
    poster_post_identifiers_retriever_module:
      regex: laredoute.com\/ppdp\/(.+).aspx
    post_identifiers_retriever_module:
      regex: laredoute.com\/ppdp\/(.+).aspx
    price_retriever_module:
      replace_old: \$
      replace_new:  USD
  post_information_retriever_module:
    post_url_template: https://www.laredoute.com/ppdp/{}.aspx
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector:
          - .glControls>input[data-action="Close"]
          - button#popin_tc_privacy_button_2
        after_pause_time: 2
    price_retriever_module:
      replace_old: \$
      replace_new: USD