include: lazada.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.lazada.sg/catalog/?q={}
    post_identifiers_retriever_module:
      regex: lazada\.sg\/products\/(.+)$
    poster_post_identifiers_retriever_module:
      regex: lazada\.sg/products\/(.*)$
    price_retriever_module:
      replace_old: \$
      replace_new: SGD
  post_information_retriever_module:
    post_url_template: https://www.lazada.sg/products/{}
    price_retriever_module:
      replace_old: \$
      replace_new: SGD
