include: lazada.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.lazada.com.my/catalog/?q={}
    post_identifiers_retriever_module:
      regex: lazada\.com\.my/products/(.+).html
    poster_post_identifiers_retriever_module:
      regex: lazada\.com\.my/products/(.+).html
    price_retriever_module:
      replace_old: RM
      replace_new: MYR
  post_information_retriever_module:
    post_url_template: https://www.lazada.com.my/products/{}.html
    price_retriever_module:
      replace_old: RM
      replace_new: MYR
