include: lazada.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.lazada.co.th/catalog/?q={}
    post_identifiers_retriever_module:
      regex: lazada\.co\.th/products/(.+).html
    poster_post_identifiers_retriever_module:
      regex: lazada\.co\.th/products/(.+).html
    price_retriever_module:
      replace_old: \xe0\xb8\xbf
      replace_new: THB
  post_information_retriever_module:
    post_url_template: https://www.lazada.co.th/products/{}.html
    price_retriever_module:
      replace_old: \xe0\xb8\xbf
      replace_new: THB
