framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    max_posts_to_browse: 3000
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.lfmall.co.kr/p2/search/result?searchWord={}
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: '#recentSort'
        before_pause_time: 2
        after_pause_time: 2
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: ul#productListUl li a.prd-info
      regex: lfmall.co.kr/product.do\?(.+)
      post_url_cleaning_module:
        query_string_to_keep:
          - PROD_CD
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: ul#productListUl li a.prd-info
      regex: lfmall.co.kr/product.do\?(.+)
      post_url_cleaning_module:
        query_string_to_keep:
          - PROD_CD
    listing_container_css_selector: 'ul#productListUl li'
    title_retriever_module:
      name: get_attribute_value
      css_selector: a.prd-info .name
    price_retriever_module:
      name: get_attribute_value
      css_selector: span.discount
      replace_old: \xe2\x82\xbd
      replace_new: RUB
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .roll-img img
      attribute_name: src
    load_more_results_module:
      name: load_more_by_scrolling_module
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.lfmall.co.kr/product.do?cmd=getProductDetail&{}
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: .prt-descript h2
    description_retriever_module:
      name: get_attribute_value
      css_selector: .detail_info
    price_retriever_module:
      name: get_attribute_value
      css_selector: .current_price
      replace_old: \xec\x9b\x90
      replace_new: KRW
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .brand a
      attribute_name: innerHTML
      regex: </span>(.+)
    poster_link_retriever_module:
      name: get_attribute_value
      css_selector: .brand a
      attribute_name: href
      regex: lfmall.co.kr/p2/display/brandGroup\?id=(\d+\&productSaleType=\d+\&brandId\=[^\&]+)
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .main_img .swiper-slide img
      attribute_name: src
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: 'https://www.lfmall.co.kr/p2/display/brandGroup?id={}'
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .tmpl-brand-header
    description_retriever_module:
      name: get_attribute_value
      css_selector: '#brandContent'
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img#brandImg
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      key_css_selectors:
        - .brand-more-info span.brand-star-rating
      value_css_selectors:
        - .brand-more-info span.brand-star-rating
      key_regex:
        - rating
      value_regex:
        - (.+)
      key_attributes:
        - class
      value_attributes:
        - textContent
