include: linio.yaml
framework:
  search_pages_browsing_module:
    max_posts_to_browse: 2000
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.linio.com.co/search?q={}
    poster_post_identifiers_retriever_module:
      regex: linio.com.co\/p\/(.*)$
    post_identifiers_retriever_module:
      regex: linio.com.co\/p\/(.*)$
    price_retriever_module:
      replace_old: \$
      replace_new: 'USD '
  post_information_retriever_module:
    post_url_template: https://www.linio.com.co/p/{}
    price_retriever_module:
      replace_old: \$
      replace_new: 'USD '
