framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    max_posts_to_browse: 3000
    loading_delay: 4
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.lotteon.com/search/search/search.ecn?render=search&platform=pc&q={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .srchResultProductArea ul>li.s-goods-grid__item>div
      attribute_name: data-object
      regex: pd\_id\=(.+?)\&
    listing_container_css_selector: .srchResultProductArea ul>li.s-goods-grid__item>div
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .s-goods-title
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .s-goods-price__final>span:last-child
      replace_old: (.+)
      replace_new: \g<1> KRW
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .s-goods__thumbnail img
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: a.srchPaginationNext
      loading_delay: 3
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '[dataid="d_seller_productList"]>.dataItem>div>ul>li'
      attribute_name: data-pd-no
      listing_container_css_selector: '[dataid="d_seller_productList"]>.dataItem>div>ul>li'
      title_retriever_module:
        name: get_attribute_value
        attribute_name: textContent
        css_selector: .title
      price_retriever_module:
        name: get_attribute_value
        attribute_name: textContent
        css_selector: .price>div>.final
        replace_old: (.+)
        replace_new: \g<1> KRW
        exclude_children: true
      pictures_retriever_module:
        name: get_pictures_from_attribute
        css_selector: .thumb>a>img
        attribute_name: src
      load_more_results_module:
        name: click_on_next_page_module
        css_selector: .paginationWrap>div>a.next
        scroll_pause_time: 3
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: 'https://www.lotteon.com/p/product/{}'
    loading_delay: 3
    title_retriever_module:
      name: get_attribute_value
      css_selector: .productDetailTop h2
    price_retriever_module:
      name: get_attribute_value
      css_selector: .productDetailTop .priceInfo>.price>span:last-of-type
      attribute_name: textContent
      replace_old: (.+)
      replace_new: \g<1> KRW
      exclude_children: true
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .sellerInfo .nameBox>strong
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_json_value
      css_selector: '#metaData'
      attribute_name: value
      output_string: 'https://www.lotteon.com/p/display/seller/sellerShop/{jsons[0]["product"]["basicInfo"]["trNo"]}'
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_2: .productVisualThumbs .swiper-slide-active+div>div
      picture_css_selector: .largeImgSlide .swiper-slide-active>div>img
      attribute_name: src
      regex: (.+)
      loading_delay: 2
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    loading_delay: 3
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .sellerStoreZoneInfo .title>a
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div#info ul li img
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      clickable_css_selector: .sellerStoreZoneInfo button.btnSellerInfo
      key_css_selector: .sellerInfoPop>.sellerInfoDetail>ul>li>strong:first-child
      value_css_selector: .sellerInfoPop>.sellerInfoDetail>ul>li>*:not(strong)
      clickable_css_is_always_present: true
