include: mall.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.mall.sk/hladaj?s={}
    poster_post_identifiers_retriever_module:
      regex: mall.sk\/(.+)$
    post_identifiers_retriever_module:
      regex: mall.sk\/(.+)$
    price_retriever_module:
      replace_old: \€
      replace_new: EUR
  post_information_retriever_module:
    post_url_template: https://www.mall.sk/{}
    price_retriever_module:
      css_selector: .detail__main-data .the-price-section
      replace_old: \€
      replace_new: EUR
      exclude_children: false
    vendor_retriever_module:
      css_selector: div.info-box-note-marketplace-redesign__title>*
    poster_link_retriever_module:
      css_selector: div.info-box-note-marketplace-redesign__title>a