framework:
  name: selenium_framework
  proxies:
    - name: iproyal/us
    - name: iproyal/lithuania
    - name: proxys.io/mobile/shared/ru
    - name: proxys.io/mobile/dedicated/ru
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 2000
    loading_delay: 5
    take_screenshots: true
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://market.yandex.ru/search?text={}
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '#searchResults [data-baobab-name="productSnippet"]>div>div>div>a'
      regex: market.yandex.ru\/(.+)
      listing_container_css_selector: '#searchResults [data-baobab-name="productSnippet"]'
      title_retriever_module:
        name: get_attribute_value
        attribute_name: textContent
        css_selector: '[data-baobab-name="title"]>span'
      price_retriever_module:
        name: get_attribute_value
        attribute_name: textContent
        css_selector: '[data-auto="price"]'
        replace_old: \₽
        replace_new: RUB
        trim_text: true
      pictures_retriever_module:
        name: get_pictures_from_attribute
        css_selector: '[data-baobab-name="picture"] img'
        attribute_name: src
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: article[data-autotest-id="product-snippet"] [data-auto="snippet-title-header"]>a
      regex: market.yandex.ru\/(.+)
    listing_container_css_selector: article[data-autotest-id="product-snippet"]
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: '[data-auto="snippet-title-header"]>a'
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: 'h3[data-auto="price-block"]'
      replace_old: \₽
      replace_new: RUB
      trim_text: true
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: '[data-auto="shop-info-container"] [data-zone-name="shop-name"]'
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[data-zone-name="picture"] img'
      attribute_name: src
    load_more_results_module:
      name: load_more_by_scrolling_one_scroll_at_a_time
      css_selector: '[data-auto="pagination-next"]'
      loading_delay: 5
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://market.yandex.ru/{}
    loading_delay: 2
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[data-zone-name="productCardTitle"] h1[data-baobab-name="title"]'
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div[data-auto="full-description-text"]
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[data-zone-name="cpa-offer"] [data-auto="price-block"] , [data-zone-name="cpa-offer"] [data-auto="mainPrice"]'
      replace_old: \₽
      replace_new: RUB
      trim_text: true
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: '[data-zone-name="cpa-offer"] [data-zone-name="shop-name"]>a , [data-zone-name="cpa-offer"] div[data-autotest-shopid] a[data-zone-name="offerLink"]'
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: '[data-zone-name="cpa-offer"] [data-zone-name="shop-name"]>a , [data-zone-name="cpa-offer"] div[data-autotest-shopid] [data-zone-name="offerLink"]'
      attribute_name: href
      post_url_cleaning_module:
        query_string_to_keep:
          - businessId
      replace_old: '.+businessId\=(.+)'
      replace_new: 'https://market.yandex.ru/business--/\g<1>'
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector: ul[data-auto="gallery-nav"]>li>div>img:not([alt=""][title=""])
      clickable_css_selector_1: '#ProductImageGallery>div [data-zone-name="image"] img[data-auto="gallery-photo"]'
      clickable_css_selector_2: '[data-auto="gallery-modal"] [data-auto="next"][role="button"]'
      picture_css_selector: '[data-auto="gallery-modal"] img[data-auto="gallery-modal-photo"]'
      attribute_name: src
      regex: (.+)
      loading_delay: 2
      escape_popup_on_end: true
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: '[data-zone-name="Footer"] h2'
      attribute_name: textContent
