framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 3000
    scroll_down_after_get_new_page: true
    loading_delay: 4
    take_screenshots: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://mediamarkt.lu/search?q={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .list-view-items>li.grid__item>.product-card>a
      regex: mediamarkt.lu\/products\/(.+)
    listing_container_css_selector: .list-view-items>li.grid__item>.product-card
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .product-card__title
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .price-item--sale
      replace_old: (.+)
      replace_new: \g<1> EUR
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img.grid-view-item__image
      attribute_name: srcset
      regex: '.+\ (.+?)\ '
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: '#pagination>.next'
      loading_delay: 4
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.mediamarkt.lu/products/{}
    loading_delay: 3
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: .product-single__title
    description_retriever_module:
      name: get_attribute_value
      css_selector: .product-description
    price_retriever_module:
      name: get_attribute_value
      css_selector: .product__price .price-item--sale
      replace_old: (.+)
      replace_new: \g<1> EUR
    pictures_retriever_module:
      name: get_pictures_from_attribute_with_replace_regex
      css_selector: '.product-single__media-wrapper>div>img'
      attribute_name: srcset
      replace_old_regex: '.+\ (.+?)\ .*'
      replace_new: 'https:\g<1>'