include: mercadolibre.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://listado.mercadolibre.com.mx/{}
    price_retriever_module:
      replace_old: \$\n
      replace_new: MXN
  post_information_retriever_module:
    post_url_template: '{}'
    vendor_retriever_module:
      regex: .+[\.l][em][\"x][/>]([^\"<]+)