include: mercadolibre.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://listado.mercadolibre.com.ec/{}
    price_retriever_module:
      replace_old: U\$S
      replace_new: USD
  post_information_retriever_module:
    vendor_retriever_module:
      regex: .+[\.l][ee][\"c][/>]([^\"<]+)
