include: mercadolibre.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://listado.mercadolibre.com.co/{}
    price_retriever_module:
      replace_old: \$
      replace_new: COP
  post_information_retriever_module:
    vendor_retriever_module:
      regex: .+[\.l][ec][\"o][/>]([^\"<]+)
