framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    max_posts_to_browse: 3000
    loading_delay: 2
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: button.evg-btn-dismissal
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.mydeal.com.au/search?q={}
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .grid-item [itemprop="name"] a
      regex: mydeal.com.au\/(.+)$
      action_before_poster_post_identifiers_module:
        - name: click_action_module
          css_selector: 
          - .store-n-reviews>p.link>a
          - button.evg-btn-dismissal
          after_pause_time: 1
      load_more_results_module:
        name: load_more_by_scrolling_module
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .grid-item [itemprop="name"] a
      regex: mydeal.com.au\/(.+)$
    listing_container_css_selector: 'div#divProductsGrid>.grid-item'
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[itemprop="name"] a'
      attribute_name: title
    price_retriever_module:
      name: get_attribute_value
      css_selector: span.priceSpan>span.numericSpan
      replace_old: '\$'
      replace_new: 'AUD'
      trim_text: true
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div.image-wrapper>a>img
      attribute_name: src
    load_more_results_module:
      name: load_more_by_click
      css_selector: .ViewMoreWrapper a
      scroll_pause_time: 0
      loading_delay: 8
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.mydeal.com.au/{}
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: .product-main-info .product-title
    description_retriever_module:
      name: get_attribute_value
      css_selector: .product-description
    price_retriever_module:
      name: get_attribute_value
      css_selector: .product-main-info span.price-other
      replace_old: \$
      replace_new: AUD
      trim_text: true
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .seller-more-info-container .shiping-text>a
      loading_timeout: 0.1
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .seller-more-info-container .shiping-text>a
      loading_timeout: 0.1
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: '#zoom-image-wrapper.zoom-initialised>img'
      clickable_css_selector_2: 'a#fancybox-right'
      picture_css_selector: '#fancybox-wrap #fancybox-content>img'
      attribute_name: src
      regex: (.+)
      escape_popup_on_end: true
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: https://www.mydeal.com.au/seller/{}
    take_screenshot: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: button.evg-btn-dismissal
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .seller-main-info .name-container
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: .seller-main-info .description
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img[alt="background"]
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: .seller-score-value
      value_css_selector: .seller-score-value
      key_css_selector_attribute_name: class
      value_css_selector_attribute_name: textContent
      key_regex: seller\-score