framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 1000
    loading_delay: 2
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://newauction.org/listing/offer/search_{}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .offers_container div.offers__item .title>a
      regex: newauction.org\/offer\/(.*)$
    listing_container_css_selector: .offers_container div.offers__item
    title_retriever_module:
      name: get_attribute_value
      css_selector: .title>a
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: .price>span
      attribute_name: textContent
      replace_old: \грн.
      replace_new: UAH
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .seller_block>div>a
      attribute_name: title
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .seller_block>div>a
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .offer_item_popup_photo
      attribute_name: data-original
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .offers_container div.offers__item .title>a
      regex: newauction.org\/offer\/(.*)$
      action_before_poster_post_identifiers_module:
        - name: click_action_module
          css_selector: .user_wrapper .all_offers>a
          after_pause_time: 4
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: .listing__pager__page:last-child>a
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://newauction.org/offer/{}
    loading_delay: 3
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: .offer__title
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: '#user_field'
      attribute_name: textContent
    price_retriever_module:
      name: get_json_value
      css_selector: script[type="application/ld+json"]
      output_string: '{jsons[0]["offers"]["price"]} {jsons[0]["offers"]["priceCurrency"]}'
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .about_user>a
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .about_user>a
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute_with_replace
      css_selector: .fotorama__nav-wrap .fotorama__loaded--img>img,.fotorama__stage
        div.fotorama__active>img
      attribute_name: src
      replace_old: small
      replace_new: big
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    loading_delay: 3
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .about_user>div>.login
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: .about_me
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .about_user>img.avatar_widget
      attribute_name: data-src_full
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      key_css_selectors:
        - .additional_information>div:nth-child(1)
        - .additional_information>div:nth-child(2)
      value_css_selectors:
        - .additional_information>div:nth-child(1)>span
        - .additional_information>div:nth-child(2)>span
      key_regex:
        - зареєстрований
        - остання активність
      value_regex:
        - (.+)
        - (.+)
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: .user_wrapper .about>a
        after_pause_time: 3
