framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    xvfb: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 3000
    scroll_down_after_get_new_page: true
    loading_delay: 3
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.overstock.com/{},/k,/results.html
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '#products>.productTile a[class*="productTile_link"]'
      regex: overstock.com\/(.+)
    listing_container_css_selector: '#products>.productTile a[class*="productTile_link"]'
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: '[class*="title_wrapper"]>p'
    price_retriever_module:
      name: get_attribute_value
      css_selector: div#currentPrice
      regex: (\$.+)
      replace_old: \$
      replace_new: USD
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img[class*="progressiveImageLoader_img"]
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: '[aria-label="pagination"]>button[aria-label="right arrow"]'
      loading_delay: 6
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector:
          - button.cl-dialog-close
          - div[class*="Banner_countrySelect"]>a
          - div.mod.flag-select ul>li.US>a
          - div#gdpr-container>svg
        after_pause_time: 2
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.overstock.com/{}
    take_screenshot: true
    loading_delay: 3
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector:
          - button.cl-dialog-close
          - div[class*="Banner_countrySelect"]>a
          - div.mod.flag-select ul>li.US>a
          - div#gdpr-container>svg
        after_pause_time: 2
        loading_timeout: 7
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[data-test="product-title"]'
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: 'div#description-height'
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: div[data-testid="current-price"]
      replace_old: \$
      replace_new: USD
      regex: (\$.+)
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: '#page-wrap [data-testid*="marketplace"]'
      attribute_name: textContent
      loading_timeout: 0.1
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: '[data-testid="magnifier wrapper"]>div>img'
      clickable_css_selector_2: '.imageViewerLarge button[aria-label="next image arrow"]'
      picture_css_selector: '.imageViewerLarge [data-testid*="image viewer slide"][aria-hidden="false"] img'
      attribute_name: src
      loading_delay: 1
      regex: (.+)
      escape_popup_on_end: true