framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    max_posts_to_browse: 3000
    loading_delay: 2
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '.td_item a[data-type="goods_url"]'
    listing_container_css_selector: '#div_search_result_list tbody tr'
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: '.td_item a[data-type="goods_url"]'
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .prc>strong
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .lnk_sh>a
      attribute_name: textContent
      exclude_children: true
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .lnk_sh>a
      attribute_name: href
      post_url_cleaning_module:
        skip_query_string_cleaning: true
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .td_thmb img
      attribute_name: src
    load_more_results_module:
      name: load_more_by_click
      css_selector: 'a#btn_more_result'
      undetected_click: true
      scroll_pause_time: 0
      loading_delay: 3
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '#search_result_item_list>li a.tt'
      regex: qoo10\..+\/item\/(.+)$
      listing_container_css_selector: '#search_result_item_list>li'
      title_retriever_module:
        name: get_attribute_value
        attribute_name: textContent
        css_selector: a.tt
      price_retriever_module:
        name: get_attribute_value
        attribute_name: textContent
        css_selector: .prc>strong
      pictures_retriever_module:
        name: get_pictures_from_attribute
        css_selector: .thmb>img
        attribute_name: src
      load_more_results_module:
        name: load_more_by_scrolling_module
        scroll_pause_time: 4
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: 'https://www.qoo10.com/item/{}'
    action_before_retrieving_post_information_module:
    - name: click_action_module
      css_selector:
        - 'button#CommonShipLangCurrencyBtn'
        - 'button#CommonShipLangCurrencyBtn'
        - 'button#ShipToSelector'
        - '#div_layer_ship_to li[data-nation="US"]'
        - '#ShipToLangCurrencySelector>button.btn'
      stop_css_selector: 'button#CommonShipLangCurrencyBtn'
      stop_attribute_name: data-nation_cd
      stop_value: US
      loading_timeout: 5
      after_pause_time: 1
    title_retriever_module:
      name: get_attribute_value
      css_selector: '#goods_name'
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: '#DetailIteminfo .detailArea'
      trim_text: true
    price_retriever_module:
      name: get_attribute_value
      css_selector: .goods-wing .prc
      replace_old: \$
      replace_new: D
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: 'a#shop_link'
      attribute_name: title
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: 'a#shop_link'
      attribute_name: href
      post_url_cleaning_module:
        skip_query_string_cleaning: true
    ships_from_retriever_module:
      name: get_key_value_list
      key_css_selector: .dtl_osship>dl:first-of-type>dd
      value_css_selector: .dtl_osship>dl:first-of-type>dd
    ships_to_retriever_module:
      name: get_key_value_list
      key_css_selector: '.dtl_osship #content_ship_to>li'
      value_css_selector: '.dtl_osship #content_ship_to>li'
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      move_to_element_before_click: true
      clickable_css_selector_1: '.goods-enlarge[style=""] #large-tab , .goods-img__main>.img>img'
      clickable_css_selector_2: '.slide>ul>li.selected+li'
      picture_css_selector: '#gei_bigPhoto>img'
      attribute_name: src
      regex: (.+)
      loading_delay: 3
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: .info_shop>ul>li:first-child>a
        after_pause_time: 2
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: a.name
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: .mshop_dtl .article
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '#div_mshop_bar>a>img'
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: .shp_inf>ul>li>h3
      value_css_selector: .shp_inf>ul>li>div.dtl
