framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    max_posts_to_browse: 3000
    loading_delay: 3
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://search.rakuten.co.jp/search/mall/{}/?s=4
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: a[data-link="item"]
      regex: item.rakuten.co.jp\/(.+)
    listing_container_css_selector: div.searchresultitem
    title_retriever_module:
      name: get_attribute_value
      attribute_name: title
      css_selector: div.title>h2>a
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: div[class*="price-wrapper"]>div[class*="price"]
      replace_old: \xe5\x86\x86
      replace_new: JPY
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div.merchant>a
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: div.merchant>a
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div.image>a>img
      attribute_name: src
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: .dui-pagination a:last-child
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    take_screenshot: true
    post_url_template: https://item.rakuten.co.jp/{}
    loading_delay: 4
    title_retriever_module:
      name: get_attribute_value
      css_selector: meta[itemprop="name"]
      attribute_name: content
      regex: (.+)\｜.+
    description_retriever_module:
      name: get_attribute_value
      css_selector: span.item_desc
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: span[irc="Price"]
      replace_old: \xe5\x86\x86
      replace_new: JPY
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: meta[itemprop="name"]
      attribute_name: content
      regex: .+\｜(.+)
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a[href*="/info.html"]
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: meta[content*="shop.r10s.jp"][content$=".jpg"]
      attribute_name: content
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    loading_delay: 5
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: head title
      attribute_name: textContent
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: '#company_info'
      value_css_selector: .companyInfoPC>blockquote:not(#holiday):first-of-type
