framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 3000
    scroll_down_after_get_new_page: true
    loading_delay: 3
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://satu.kz/search?search_term={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div[data-qaid="product_gallery"] a[data-qaid="product_link"]
      regex: satu\.kz/(.+)
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: a[data-qaid="product_link"]
      regex: satu\.kz/(.+)
    listing_container_css_selector: '[data-qaid="product_block"]'
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[data-qaid="product_name"]'
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[data-qaid="product_price"]'
      attribute_name: textContent
      replace_old: \xd0\xa2\xd0\xb3\.
      replace_new: KZT
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: a.jwtUM:not([title])
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a.jwtUM:not([title])
      attribute_name: href
    location_retriever_module:
      name: get_attribute_value
      css_selector: '[data-qaid="region_title"]'
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: picture[data-qaid="image_link"]>img
      attribute_name: src
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: a[data-qaid="next_page"]
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://satu.kz/{}
    title_retriever_module:
      name: get_attribute_value
      css_selector: h1[data-qaid="product_name"]
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div[data-qaid="attribute_block"]
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[data-qaid="product_price"]'
      replace_old: \xd0\xa2\xd0\xb3\.
      replace_new: KZT
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: a[data-qaid="company_name"]
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a[data-qaid="company_name"]
      attribute_name: href
    ships_to_retriever_module:
      name: get_key_value_list
      clickable_css_selector: div[data-qaid="region_delivery"] button
      key_css_selector: div[data-qaid="region_delivery_popup"] li
      value_css_selector: div[data-qaid="region_delivery_popup"] li
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img[data-qaid="image_thumb"] , img[data-qaid="image_preview"]
      attribute_name: src
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: div[data-qaid="adult_popup"] button[data-qaid="yes"]
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    loading_delay: 5
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: span[data-qaid="company_name"]
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img[data-qaid="company_logo"]
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      clickable_css_selector: '[data-qaid="contacts_btn"]'
      key_css_selector: div[data-qaid="contacts_popup"]>ul>li:last-child >div>ul>li
        a
      value_css_selector: div[data-qaid="contacts_popup"]>ul>li:last-child >div>ul>li
        a
      key_css_selector_attribute_name: data-qaid
