framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 3000
    loading_delay: 10
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.sears.com.mx/resultados/q={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .boxProductosCategory>.cardProduct>a
      regex: sears.com.mx\/producto\/(\d+)\/
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .boxProductosCategory>.cardProduct>a
      regex: sears.com.mx\/producto\/(\d+)\/
    listing_container_css_selector: .boxProductosCategory>.cardProduct
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: '[class*="CardProduct_contDataCard"]>h3'
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="CardProduct_precio1"]'
      attribute_name: textContent
      replace_old: \$
      replace_new: ''
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: :scope>a>picture>img
      attribute_name: src
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: .paginador>ul>li>a.next
      loading_delay: 4
      restart_driver: true
  post_information_retriever_module:
    name: post_information_retriever_with_creation_of_a_new_driver_for_each_post_module
    post_url_template: https://www.sears.com.mx/producto/{}
    take_screenshot: true
    loading_delay: 5
    title_retriever_module:
      name: get_attribute_value
      css_selector: .moduleShopTitle>h1
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div.moduleDescriptionSears
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: .moduleShopPrice .pPrice
      replace_old: \$
      replace_new: ''
      exclude_children: true
      attribute_name: textContent
      loading_timeout: 1
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .vendidoPor>a
      attribute_name: textContent
      loading_timeout: 0.1
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .vendidoPor>a
      attribute_name: href
      loading_timeout: 0.1
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_2: '#contImages .pequeS>div.slick-slider>button.slick-next:not(slick-disabled)'
      picture_css_selector: '#contImages .grandeS>div>.slick-list .slick-active img'
      attribute_name: src
      loading_delay: 3.5
      regex: (.+)
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    loading_delay: 5
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .contOficalStore h1
      attribute_name: textContent