include: shopee.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://shopee.com.my/search?keyword={}&sortBy=ctime
    poster_post_identifiers_retriever_module:
      regex: shopee.com.my\/(.*)$
    post_identifiers_retriever_module:
      regex: shopee.com.my\/(.*)$
    price_retriever_module:
      replace_old: RM
      replace_new: MYR
    action_before_search_pages_browsing_module:
      - name: click_action_module
        before_pause_time: 3
        css_selector: '#modal button'
  post_information_retriever_module:
    post_url_template: https://shopee.com.my/{}
    price_retriever_module:
      replace_old: RM
      replace_new: MYR
    vendor_retriever_module:
      regex: .+my/(.+)\?.+
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: '#modal button'
  poster_information_retriever_module:
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: '#modal button'
