framework:
  name: selenium_framework
  proxies:
    - name: iproyal/us
    - name: iproyal/lithuania
    - name: proxyrack
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    max_posts_to_browse: 3000
    loading_delay: 2
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: 'button[class*="lgpd-message-box__Button"]'
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.shoptime.com.br/busca/{}
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '[class*="src__ColGridItem"] div[class*="inStockCard__Wrapper"]>a'
      regex: shoptime.com.br\/produto\/(.+)$
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '[class*="src__ColGridItem"] div[class*="inStockCard__Wrapper"]>a'
      regex: shoptime.com.br\/produto\/(.+)$
    listing_container_css_selector: '[class*="src__ColGridItem"] div[class*="inStockCard__Wrapper"]>a'
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="product-name__Name"]'
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="price__PromotionalPrice"]'
      replace_old: 'R\$'
      replace_new: 'BRL'
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[class*="src__Picture"]>img'
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: 'ul[class*="src__Items"]>li:last-child>button'
      loading_delay: 2
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.shoptime.com.br/produto/{}
    take_screenshot: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: 'button[class*="lgpd-message-box__Button"]'
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="src__ProductInfo"] h1[class*="src__Title"]'
    description_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="src__ProductInfo"] [class*="product-description__Description"]'
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="src__ProductOffer"] [class*="src__BestPrice"]'
      exclude_children: true
      loading_timeout: 0.1
      replace_old: 'R\$'
      replace_new: 'BRL'
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="src__ProductOffer"] [class*="offers-box__Wrapper"]>p>a'
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: '[class*="src__ProductOffer"] [class*="offers-box__Wrapper"]>p>a'
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: '[class*="main-image__Container"]>div img'
      clickable_css_selector_2: .pswp__ui button.pswp__button--arrow--right
      picture_css_selector: '.product-gallery-zoom .pswp__item>.pswp__zoom-wrap img'
      attribute_name: src
      regex: (.+)
      escape_popup_on_end: true
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: 'https://www.shoptime.com.br/lojista/{}'
    take_screenshot: true
    loading_delay: 2
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: 'button[class*="lgpd-message-box__Button"]'
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="seller-about__ImageContainer"]>img
      attribute_name: alt
    description_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="seller-about__TextContainer"]
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div[class*="seller-about__ImageContainer"]>img
      attribute_name: src