# Domain not available anymore
include: shopee.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://shopee.es/search?keyword={}
    poster_post_identifiers_retriever_module:
      regex: shopee.es\/(.*)$
    post_identifiers_retriever_module:
      regex: shopee.es\/(.*)$
  post_information_retriever_module:
    post_url_template: https://shopee.es/{}
    vendor_retriever_module:
      regex: .+es/(.+)\?.+