framework:
  name: selenium_framework
  proxies:
    - name: proxyrack
    - name: iproyal/us
    - name: iproyal/lithuania
    - name: 123proxy
    - name: proxys.io/mobile/shared/th
    - name: proxys.io/mobile/dedicated/th
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
    undetected_driver: true
    use_tor_proxy: false
    headless: False
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    max_posts_to_browse: 3000
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: .zsav9a button:last-child
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div.shop-search-result-view [data-sqe="link"]
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div[data-sqe="item"] a[data-sqe="link"]
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: '[class="shopee-icon-button shopee-icon-button--right "]'
    listing_container_css_selector: '.shopee-search-item-result__item'
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: div[data-sqe="name"]
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .rVLWG6
    item_sold_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .uEPGHT
      loading_timeout: 0.1
    location_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .zGGwiV
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: 'div:not(.customized-overlay-image) > img'
      attribute_name: src
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    take_screenshot: true
    loading_delay: 3
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: .zsav9a button:last-child
    title_retriever_module:
      name: get_attribute_value
      css_selector: .product-briefing ._44qnta
    description_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="product-detail"]
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: .product-briefing .pqTWkA
    stock_retriever_module:
      name: get_attribute_value
      css_selector: ._6lioXX>div>div:not([style])
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: a[href*="categoryId"]:first-of-type
      attribute_name: href
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a[href*="categoryId"]
      attribute_name: href
    ships_from_retriever_module:
      name: get_key_value_list
      key_css_selector: .dR8kXc:last-child>div
      value_css_selector: .dR8kXc:last-child>div
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: .flex.flex-column>div:first-child
      clickable_css_selector_2: '#modal>div:last-child>div>div>div:first-child>div:last-of-type'
      picture_css_selector: '#modal>div:last-child>div>div>div:first-child>div>picture>img'
      regex: '(.+)'
      attribute_name: src
      skip_video: true
      loading_delay: 2.5
    videos_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_2: '#modal>div:last-child>div>div>div:first-child>div:last-of-type'
      picture_css_selector: '#modal>div:last-child>div>div>div video'
      attribute_name: src
      regex: (.+)
      escape_popup_on_end: true
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: .zsav9a button:last-child
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: h1.section-seller-overview-horizontal__portrait-name
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div.shop-page-shop-description
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img.shopee-avatar__img
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: .section-seller-overview__item-text-name:first-of-type
      value_css_selector: .section-seller-overview__item-text-value:first-of-type
  archiving_options:
    remove_elements:
      - .language-selection
