include: skroutz.yaml
framework:
    search_pages_browsing_module:
      search_page_urls_builder_module:
        search_page_url_templates:
          - https://www.skroutz.eu/search?keyphrase={}
      poster_post_identifiers_retriever_module:
        regex: skroutz.eu/(.+)
      post_identifiers_retriever_module:
        regex: skroutz.eu/(.+)
      action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: ul.country-list li:first-child
        after_pause_time: 2
      - name: click_action_module
        css_selector: button#accept-all
    post_information_retriever_module:
      name: classic_post_information_retriever_module
      post_url_template: https://www.skroutz.eu/{}
      action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: ul.country-list li:first-child
        after_pause_time: 2
      - name: click_action_module
        css_selector: button#accept-all
    poster_information_retriever_module:
      action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: ul.country-list li:first-child
        after_pause_time: 2
      - name: click_action_module
        css_selector: button#accept-all