framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 3000
    loading_delay: 2
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://sourcing.hktdc.com/en/Product-Search/{}/1
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div.css-1dzl4if>div.product-padding>a
      regex: sourcing.hktdc.com\/en\/Product-Detail\/(.+)
      action_before_poster_post_identifiers_module:
        - name: click_action_module
          css_selector: div.tab-bar>div:nth-child(4)>button>a
          after_pause_time: 2
          stop_css_selector: div.css-1dzl4if>div.product-padding>a
      listing_container_css_selector: div.css-1dzl4if>div.product-padding>a
      title_retriever_module:
        name: get_attribute_value
        css_selector: div.name
        exclude_children: true
        loading_timeout: 0.1
      pictures_retriever_module:
        name: get_pictures_from_attribute
        css_selector: .img-container>img
        attribute_name: src
      load_more_results_module:
        name: click_on_next_page_module
        css_selector: .css-1d9fjbt>div.input-group>button:last-of-type
        loading_delay: 2
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .search-result-section  div.product-card>div>a
      regex: sourcing.hktdc.com\/en\/Product-Detail\/(.+)
    listing_container_css_selector: '.search-result-section  div.product-card'
    title_retriever_module:
      name: get_attribute_value
      css_selector: p.product-name
    price_retriever_module:
      name: get_attribute_value
      css_selector: 'span.final-price'
      loading_timeout: 0.1
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .footer-content-container>div>a
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .footer-content-container>div>a
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .img-container>a>img
      attribute_name: src
    load_more_results_module:
      name: load_more_by_scrolling_module
      scroll_pause_time: 2
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://sourcing.hktdc.com/en/Product-Detail/{}
    take_screenshot: true
    loading_delay: 1
    title_retriever_module:
      name: get_attribute_value
      css_selector: div.product-name>span
    description_retriever_module:
      name: get_attribute_value
      css_selector: div.product-Info-outer-container>div>div:last-of-type>.tab-content:first-of-type
    price_retriever_module:
      name: get_attribute_value
      css_selector: 'div.price-section div.price-item'
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div.trust-card__main-card-content>div>div>a
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: div.trust-card__main-card-content>div>div>a
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: div.media-slider-container>div.media-slider-item>img
      clickable_css_selector_2: div.lightbox-container .right-arrow
      picture_css_selector: div.lightbox-container div.image-container>img
      attribute_name: src
      regex: (.+)
      close_button_css_selector: div.lightbox-container .image-container svg
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: 'https://sourcing.hktdc.com/en/Supplier-Store/{}'
    take_screenshot: true
    loading_delay: 1
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector:
          - .profile-dropdown a.tab
          - .profile-dropdown .profile-tab-card>div:first-child
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: '.trust-card__main-card-content h2.trust-card__company-name'
    description_retriever_module:
      name: get_attribute_value
      clickable_css_selector: div.css-nok82k>p>a
      css_selector: div.css-nok82k>p
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .trust-card__main-card-content .trust-card__logo-container img
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: .css-1n76k4a .css-8dm6ln>div.row>div:first-child
      value_css_selector: .css-1n76k4a .css-8dm6ln>div.row>div:last-child