framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 3000
    scroll_down_after_get_new_page: true
    loading_delay: 5
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.target.com/s?searchTerm={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: section[class*="styles__StyledRowWrapper"] div[data-test*="ProductCardWrapper"] a[data-test="product-title"]
      regex: target.com\/p\/(.+)$
    listing_container_css_selector: section[class*="styles__StyledRowWrapper"] div[data-test*="ProductCardWrapper"]
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: a[data-test="product-title"]
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: 'span[data-test="current-price"]'
      replace_old: \$
      replace_new: USD
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: '[data-test="marketplaceSellerName"]'
      loading_timeout: 0.1
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[data-test*="ProductCardImage/primary"]>img'
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: '[data-test="pagination"] button[aria-label="next page"]'
      loading_delay: 3
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: section[class*="styles__StyledRowWrapper"] div[data-test*="ProductCardWrapper"] a[data-test="product-title"]
      regex: target.com\/p\/(.+)$
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.target.com/p/{}
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: h1[data-test="product-title"]
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div[data-test="item-details-description"]
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: '#pageBodyContainer span[data-test="product-price"]'
      replace_old: \$
      replace_new: USD
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: 'a[data-test="targetPlusExtraInfoSection"]>div>div:last-child'
      attribute_name: textContent
      loading_timeout: 0.1
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a[data-test="targetPlusExtraInfoSection"]
      attribute_name: href
      loading_timeout: 0.1
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: '[data-test*="BaseImageGallery"] button:not([aria-hidden="true"])'
      clickable_css_selector_2: '[data-test="image-gallery-modal"] button[aria-label="next page"]'
      picture_css_selector: '[data-test="image-gallery-modal"] button[data-test*="image-gallery-modal-item"]:not([aria-hidden="true"]) img'
      regex: (.+)
      attribute_name: src
      escape_popup_on_end: true
      loading_delay: 3
      skip_video: true
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    loading_delay: 3
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: '#tabContent-tab-About h3'
    description_retriever_module:
      name: get_attribute_value
      css_selector: '#tabContent-tab-About h3+p'
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[data-test="sellerBackgroundImage"] img'
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      clickable_css_selector: 'a#tab-Contact'
      key_css_selector: '[data-test="tab-tabContent-tab-Contact"] h3'
      value_css_selector: '[data-test="tab-tabContent-tab-Contact"] h3+p'
      clickable_css_is_always_present: true
      loading_delay: 2