framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 3000
    scroll_down_after_get_new_page: true
    loading_delay: 4
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://tiki.vn/search?q={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '[data-view-id="product_list_container"]>div>a[data-view-id="product_list_item"]'
      regex: tiki.vn\/.*(p\d+).html
    listing_container_css_selector: '[data-view-id="product_list_container"]>div>a[data-view-id="product_list_item"]'
    title_retriever_module:
      name: get_attribute_value
      css_selector: .info .name
    price_retriever_module:
      name: get_attribute_value
      css_selector: .price-discount>div
      replace_old: \₫
      replace_new: VND
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .thumbnail picture>img
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: .pagination-block>div:last-of-type>a
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .seller-page [class*="ProductRow__Container"]>a[class*="Product__Wrapper"]
      regex: tiki.vn\/.*(p\d+).html
      action_before_poster_post_identifiers_module:
        - name: click_action_module
          css_selector: '[class*="FollowCampaignBanner__Button-"]:first-child'
        - name: click_action_module
          css_selector: '[class*="MenuTab__WrapperTabMenu"]>div:nth-child(2)>div'
          stop_css_selector: '.seller-page [class*="ProductRow__Container"]>a[class*="Product__Wrapper"]'
          after_pause_time: 5
          loading_timeout: 0.5
      listing_container_css_selector: '.seller-page [class*="ProductRow__Container"]>a[class*="Product__Wrapper"]'
      title_retriever_module:
        name: get_attribute_value
        css_selector: '[class*="Product__Info"]>[class*="Product__Name"]'
      price_retriever_module:
        name: get_attribute_value
        css_selector: '[class*="Product__Info"]>[class*="Product__PriceDiscount"]>div>span'
        replace_old: (.+)
        replace_new: '\g<1> VND'
      item_sold_retriever_module:
        name: get_attribute_value
        css_selector: '[class*="Product__ContainerRating"]>.percent'
        regex: \d+
      pictures_retriever_module:
        name: get_pictures_from_attribute
        css_selector: '[class*="Product__Thumbnail"] picture>img'
        attribute_name: src
      load_more_results_module:
        name: load_more_by_click
        css_selector: button[class*="ViewMoreBtn__Wrapper"]
        loading_delay: 3
        scroll_pause_time: 0
  post_information_retriever_module:
    name: post_information_retriever_with_creation_of_a_new_driver_for_each_post_module
    post_url_template: https://tiki.vn/{}.html
    take_screenshot: true
    loading_delay: 3
    title_retriever_module:
      name: get_attribute_value
      css_selector: main h1.title
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="ToggleContent__Wrapper"]>div'
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: main .product-price>div
      replace_old: \₫
      replace_new: VND
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .seller-info>a.overview .seller-name
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .seller-info>a.overview
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector: '[data-view-id="pdp_main_view_photo"]>*:not(.video):last-child>img'
      clickable_css_selector_2: .main-slide-wrapper div.nav-right
      clickable_css_selector_1: .group-images>[data-view-id="pdp_main_view_gallery"] picture>img
      picture_css_selector: .main-slide-container .slide-item>picture>img
      attribute_name: src
      regex: (.+)
      escape_popup_on_end: true
      loading_delay: 2
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector:
          - '[class*="FollowCampaignBanner__Button-"]:first-child'
          - '[class*="MenuTab__WrapperTabMenu"]>div:last-child>div'
        after_pause_time: 3
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: '#seller-info-wrapper>[class*="Header__SellerName"]>h1'
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '#seller-info-wrapper>[class*="Header__Logo"]>img'
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: '[class*="StoreInfo__InfoWrapper"]>div>span:first-child'
      value_css_selector: '[class*="StoreInfo__InfoWrapper"]>div>span:nth-child(2)'