include: vinted.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.vinted.pl/vetements?search_text={}&order=newest_first
    post_identifiers_retriever_module:
      regex: vinted.pl\/(.*)$
    poster_post_identifiers_retriever_module:
      regex: vinted.pl\/(.*)$
    price_retriever_module:
      replace_old: z\ł
      replace_new: PLN
  post_information_retriever_module:
    post_url_template: https://www.vinted.pl/{}
    location_retriever_module:
      title_column_name: LOKALIZACJA