framework:
  name: selenium_framework
  proxies:
    - name: proxyrack
    - name: iproyal/us
    - name: iproyal/lithuania
    - name: 123proxy
    - name: proxys.io/mobile/shared/us
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
    undetected_driver: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    max_posts_to_browse: 3000
    loading_delay: 3
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: section div[data-item-id] a[link-identifier]
      attribute_name: link-identifier
    listing_container_css_selector: 'section div[data-item-id]'
    title_retriever_module:
      name: get_attribute_value
      css_selector: a[link-identifier] span
    price_retriever_module:
      name: get_attribute_value
      css_selector: div[data-automation-id="product-price"] > span
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div[data-testid="list-view"] .relative > div > img
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: a[data-testid="NextPage"], a[data-testid="horizontal-scroller-next"]
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    take_screenshot: true
    loading_delay: 3
    title_retriever_module:
      name: get_attribute_value
      css_selector: h1[itemprop="name"]
    description_retriever_module:
      name: get_attribute_value
      css_selector: section[data-testid="product-description"]
    price_retriever_module:
      name: get_attribute_value
      css_selector: span[itemprop="price"]
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div[data-testid="sold-and-shipped-by"] span.lh-title span, i.ld-Spark ~ span.lh-title
    ships_to_retriever_module:
      name: get_key_value_list
      key_css_selector: button[aria-label*="change store"]
      value_css_selector: button[aria-label*="change store"]
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: div[data-testid="zoom-image"]
      clickable_css_selector_2: button[aria-label*="next media"]
      picture_css_selector: div[data-testid="zoom-image"] img:not(img[src*="Height=612"])
      attribute_name: src
      regex: (.+)
      escape_popup_on_end: true
