framework:
  name: selenium_framework
  proxies:
    - name: proxyrack
    - name: proxys.io/mobile/shared/ru
    - name: proxys.io/mobile/dedicated/ru
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
    undetected_driver: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    max_posts_to_browse: 3000
    loading_delay: 10
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.wildberries.ru/catalog/0/search.aspx?sort=newly&search={}
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .product-card-list article a[class*="card__link"]
      regex: wildberries.ru/catalog/([^/]+)/detail.aspx
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .product-card-list article a[class*="card__link"]
      regex: wildberries.ru/catalog/([^/]+)/detail.aspx
    listing_container_css_selector: '.product-card-list article'
    title_retriever_module:
      name: get_attribute_value
      css_selector: span.product-card__name
      exclude_children: true
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[class="price__lower-price"]'
      replace_old: \xe2\x82\xbd
      replace_new: RUB
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img.j-thumbnail
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: a.pagination-next
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.wildberries.ru/catalog/{}/detail.aspx
    take_screenshot: true
    loading_delay: 10
    title_retriever_module:
      name: get_attribute_value
      css_selector: .product-page__header h1
    description_retriever_module:
      name: get_attribute_value
      css_selector: section.details-section__details
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[class="price-block__final-price"]'
      replace_old: \xe2\x82\xbd
      replace_new: RUB
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: a.seller-info__name
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a.seller-info__name
      attribute_name: href
    ships_from_retriever_module:
      name: get_key_value_list
      key_css_selector: span.delivery__store
      value_css_selector: span.delivery__store
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: .zoom-image-container
      clickable_css_selector_2: button.swiper-button-next
      picture_css_selector: img.j-zoom-image
      attribute_name: src
      regex: (.+)
      skip_video: true
    videos_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_2: .product-page__slider div.videoThumb
      picture_css_selector: '#video video.wb-player__video'
      attribute_name: src
      regex: (.+)
      escape_popup_on_end: true
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: 'https://www.wildberries.ru/seller/{}'
    take_screenshot: true
    loading_delay: 10
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="seller-details__title"]'
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .seller-details__logo img[src*="/shops/"]
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      key_css_selectors:
        - span.address-rate-mini
        - span.seller-details__review
        - .seller-details__parameter div:nth-of-type(1) p.seller-details__parameter-name
        - .seller-details__parameter div:nth-of-type(2) p.seller-details__parameter-name
        - .seller-details__parameter div:nth-of-type(3) p.seller-details__parameter-name
        - .seller-details__parameter div:nth-of-type(3) p.seller-details__parameter-name
        - .seller-details__parameter div:nth-of-type(3) p.seller-details__parameter-name
        - .seller-details__parameter div:nth-of-type(3) p.seller-details__parameter-name
      value_css_selectors:
        - span.address-rate-mini
        - span.seller-details__review
        - .seller-details__parameter div:nth-of-type(1) p.seller-details__parameter-value
        - .seller-details__parameter div:nth-of-type(2) p.seller-details__parameter-value
        - .seller-details__parameter div:nth-of-type(3) p.seller-details__parameter-value
        - .seller-details__parameter div:nth-of-type(3) p.seller-details__parameter-value
        - .seller-details__parameter div:nth-of-type(3) p.seller-details__parameter-value
        - .seller-details__parameter div:nth-of-type(3) p.seller-details__parameter-value
      key_regex:
        - rate
        - \d+(.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
      value_regex:
        - (.+)
        - (\d+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
      key_attributes:
        - class
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
      value_attributes:
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
