framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    max_posts_to_browse: 3000
    scroll_down_after_get_new_page: true
    loading_delay: 6
    take_screenshots: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: .modal button.button--primary
        after_pause_time: 3
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: 'li.listing-content__card>div>a'
    listing_container_css_selector: 'li.listing-content__card>div>a'
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: span.produc-card__name__link
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: '.product-card__price span.price__value'
      replace_old: \€
      replace_new: 'EUR '
      trim_text: true
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .product-card__image-link>img
      attribute_name: src
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: li.numbers-pagination__number--current+li>a
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: .product-header__title span
    description_retriever_module:
      name: get_attribute_value
      css_selector: div[data-highlight-template="about-product"]
      loading_timeout: 0.1
    price_retriever_module:
      name: get_attribute_value
      css_selector: .product-price-info .price__value [itemprop="price"]
      replace_old: \€
      replace_new: EUR
      trim_text: true
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: '.product-price-info__seller>div>*:last-child'
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .product-price-info__seller a
      attribute_name: href
      post_url_cleaning_module:
        skip_query_string_cleaning: true
      loading_timeout: 0.1
    pictures_retriever_module:
      name: get_pictures_by_clicking_thumbnails
      clickable_css_selector: .product-gallery .product-gallery__thumbs>li
      picture_css_selector: '.product-gallery .product-gallery__slide img'
      attribute_name: src
      regex: (.+)
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: .modal button.button--primary
        after_pause_time: 2
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    take_screenshot: true
    loading_delay: 1
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: '.seller-heading__seller-name'
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: img[alt="storeLogo"]
      attribute_name: textContent
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: .seller-heading__seller-specs>li>h3
      value_css_selector: .seller-heading__seller-specs>li>p
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: .modal button.button--primary
        after_pause_time: 2
