framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 10
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://search.11st.co.kr/Search.tmall?kwd={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: li.c-search-list__item>div>a
      regex: 11st.co.kr\/products\/(.*)
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: li.store_product_item>a
      regex: 11st.co.kr\/products\/(.*)
      listing_container_css_selector: li.store_product_item
      load_more_results_module:
        name: click_on_next_page_module
        css_selector: .view_more_bar
      title_retriever_module:
        name: get_attribute_value
        css_selector: strong.store_product_name
      price_retriever_module:
        name: get_attribute_value
        css_selector: span.store_product_new_price
        regex: (\d+.*)
        replace_old: \xec\x9b\x90
        replace_new: ' KRW'
      pictures_retriever_module:
        name: get_pictures_from_attribute
        css_selector: div.store_product_thumb_wrap>img
        attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: nav.c_pagination li.next
    listing_container_css_selector: li.c-search-list__item
    title_retriever_module:
      name: get_attribute_value
      css_selector: div.c-card-item__name>dd
    price_retriever_module:
      name: get_attribute_value
      css_selector: dd[class="c-card-item__price"]
      replace_old: \xec\x9b\x90
      replace_new: ' KRW'
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div.c-card-item__thumb>span>img
      attribute_name: src
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://11st.co.kr/products/{}
    loading_delay: 6
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: h1.title
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: table[class="prdc_detail_table"] tbody
    price_retriever_module:
      name: get_attribute_value
      css_selector: .b_product_info_price .price strong
      attribute_name: textContent
      replace_old: \xec\x9b\x90
      replace_new: ' KRW'
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .c_product_store_title
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .c_product_store_title a
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute_with_replace_regex
      css_selector: '#productImg img, .thumb_inner li img'
      attribute_name: src
      replace_old_regex: \?.+
      replace_new: ''
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    loading_delay: 5
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .store_name>a
      attribute_name: textContent
    payload_retriever_module:
      name: get_key_value_list
      clickable_css_selector: .store_gnb>a
      key_css_selector: .store_info_detail>dt
      value_css_selector: .store_info_detail>dd
