framework:
  name: api_framework
  driver_initialization_module:
    name: classic_api_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://api-gw.onebound.cn/1688/item_search/?key=t_33737592661&secret=20230428&q={SEARCH_QUERY}&start_price=0&end_price=0
        - https://api-gw.onebound.cn/1688/item_search/?key=t_33737592661&secret=20230428&q={SEARCH_QUERY}&start_price=0&end_price=0&sort=_
      image_search_page_url_templates:
        - https://api-gw.onebound.cn/1688/item_search_img/?secret=20230428&key=t_33737592661&imgid={SEARCH_QUERY}&cache=no&lang=zh-CN
    api_request_params:
      method_type: GET
    load_more_results_module:
      name: load_more_by_adding_page
      value: '&page={PAGE_NUMBER}'
    listing_retriever_module:
      name: get_json_obj
      attribute_names:
        - items.item
    post_identifiers_retriever_module:
      name: get_json_value
      attribute_names:
        - num_iid
      post_url_cleaning_module:
        query_string_to_keep:
          - id
      regex:
        (?:https?://(?:item\.1688\.com|detail\.1688\.com|detail\.tmall\.com|www\.1688\.com)/(?:item\.htm\?id=|list/item/offer/)|https?://detail\.1688\.com/offer/)(\d+)
    title_retriever_module:
      name: get_json_value
      attribute_names:
        - title
    price_retriever_module:
      name: get_json_value
      attribute_names:
        - price
      append_text: CNY
    vendor_retriever_module:
      name: get_json_value
      attribute_names:
        - shop_name
    pictures_retriever_module:
      name: get_json_pictures
      attribute_names:
        - pic_url
      replace_old: (?<![:/])(//[\w\.-]+)
      replace_new: https:\1
      is_regex_replace: true
      return_list: true
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://detail.1688.com/offer/{}.html
    endpoint_post_url_template:
      https://api-gw.onebound.cn/1688/item_get/?key=t_33737592661&secret=20230428&num_iid={}
    api_request_params:
      method_type: GET
    title_retriever_module:
      name: get_json_value
      attribute_names:
        - item.title
    description_retriever_module:
      name: get_json_value
      attribute_names:
        - item.desc
      clean_html: true
    price_retriever_module:
      name: get_json_value
      attribute_names:
        - item.orginal_price
      append_text: CNY
    stock_retriever_module:
      name: get_json_value
      attribute_names:
        - item.skus.sku[0].quantity
    vendor_retriever_module:
      name: get_json_value
      attribute_names:
        - item.seller_info.shop_name
    poster_link_retriever_module:
      name: get_json_value
      attribute_names:
        - item.seller_info.zhuy
    videos_retriever_module:
      name: get_json_pictures
      attribute_names:
        - item.video..url
      return_list: true
    pictures_retriever_module:
      name: get_json_pictures
      attribute_names:
        - item.item_imgs..url
      replace_old: //img.
      replace_new: https://img.
      return_list: true
