include: 1a.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.1a.lt/paieska/?q={}
        - https://www.1a.lt/ru/paieska/?q={}
    post_identifiers_retriever_module:
      regex: 1a.lt\/.*p\/(.*)$
  post_information_retriever_module:
    post_url_template: https://www.1a.lt/p/{}