framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 5
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div.ks-new-product-item>div:first-child>a.ks-new-product-name
      attribute_name: href
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: a#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll
    listing_container_css_selector: div[class*=ks-new-product-item]
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: div.ks-new-product-item>div:first-child>a.ks-new-product-name
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: div[class*=sn-product-inner--hover] span[class*=ks-item-price]
      replace_old: \€
      replace_new: EUR
      regex: (.+)\/
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div[class="sn-product-inner ks-gtm-categories"]>a>img
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: a[class=ks-next]
      loading_delay: 2
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: div[class*=product-righter]>h1
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: '#description-anchor div[class*=simple-content]'
      attribute_name: textContent
      replace_old: \n
      replace_new: ''
    price_retriever_module:
      name: get_attribute_value
      css_selector: .product-price-details__block>span.price>span:first-child
      attribute_name: textContent
      replace_old: .+
      replace_new: \g<0> EUR
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[data-fancybox=gallery_v1] img'
      attribute_name: src
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: a#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll
