framework:
  name: selenium_framework
  proxies:
    - name: proxyrack
    - name: iproyal/us
    - name: iproyal/lithuania
    - name: 123proxy
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: button[class*="message-box__Button"]
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.americanas.com.br/busca/{}?sortBy=relevance
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '[class*="src__GridItem"] a[href*="/produto/"]'
      regex: americanas.com.br/produto/(.+)
      listing_container_css_selector: '[class*="src__GridItem"] a[href*="/produto/"]'
      title_retriever_module:
        name: get_attribute_value
        css_selector: '[class*="product-name"]'
      price_retriever_module:
        name: get_attribute_value
        css_selector: '[class*="PromotionalPrice"]'
        replace_old: R\$
        replace_new: BRL
      pictures_retriever_module:
        name: get_pictures_from_attribute
        css_selector: '[class*="card-image"] img'
        attribute_name: src
      load_more_results_module:
        name: click_on_next_page_module
        css_selector: ul[class*="src__Items"] li:last-child button
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '[class*="search-result"] a[href*="/produto/"]'
      regex: americanas.com.br/produto/(.+)
    listing_container_css_selector: '[class*="search-result"] a[href*="/produto/"]'
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="product-name"]'
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="PromotionalPrice"]'
      replace_old: R\$
      replace_new: BRL
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[class*="card-image"] img'
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: ul[class*="src__Items"] li:last-child button
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.americanas.com.br/produto/{}
    take_screenshot: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: button[class*="message-box__Button"]
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="product-title"]'
    description_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="src__Description"]'
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="PriceText"]'
      replace_old: R\$
      replace_new: BRL
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="offers-box"] a[href*="/lojista/"]'
    poster_link_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="offers-box"] a[href*="/lojista/"]'
      attribute_name: href
      regex: americanas.com.br/lojista/(.+)
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: '[class*="_Gallery"] picture'
      clickable_css_selector_2: button[class*="arrow--right"]
      picture_css_selector: '[class*="_zoom"] img'
      regex: (.+)
      attribute_name: src
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: https://www.americanas.com.br/lojista/{}/g/condicao-novo
    take_screenshot: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: button[class*="message-box__Button"]
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="seller-about__Image"] img'
      attribute_name: alt
    description_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="seller-about__Description"]'
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[class*="seller-about__Image"] img'
      attribute_name: src
