include: desertcart.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://bahrain.desertcart.com/search/{}
    post_identifiers_retriever_module:
      regex: bahrain.desertcart.com\/products\/(.*)
  post_information_retriever_module:
    post_url_template: https://bahrain.desertcart.com/products/{}