framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    undetected_driver: true
    xvfb: true
    cloudflare_bypass: true
  proxies:
    - name: proxyrack
      country: IT
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    loading_delay: 8
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.bakeca.it/annunci/tutte-le-categorie/sorting/SBDATA/nope/true/?keyword={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .annuncio-elenco>section>a[data-ref="product"]
      regex: (?<=bakeca.it\/)(.*)
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .annuncio-elenco a
      load_more_results_module:
        name: click_on_next_page_module
        css_selector: .b-succLink
        loading_delay: 3
    listing_container_css_selector: .annuncio-elenco>section
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: a>div>h2
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: a>div>strong
      replace_old: \xe2\x82\xac
      replace_new: EUR
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div .vetrina-elenco>strong
      attribute_name: textContent
      loading_timeout: 0.1
    location_retriever_module:
      name: get_attribute_value
      css_selector: a>div>span>strong
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: a picture>img
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: span[title="Pagina successiva"]>span
      loading_delay: 3
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: button[class*="accept-btn"]
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.bakeca.it/{}
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: ' meta[property="og:title"]'
      attribute_name: content
    description_retriever_module:
      name: get_attribute_value
      css_selector: '#annuncio_descrizione>p'
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: article>section>h1>span
      replace_old: \xe2\x82\xac
      replace_new: EUR
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .inserzionista>a:first-child>h3
      replace_old: Inserzionista
      replace_new: ''
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .inserzionista a:first-child
      attribute_name: href
    ships_from_retriever_module:
      name: get_key_value_list
      key_css_selector: input[name="vhost"]
      key_css_selector_attribute_name: value
      value_css_selector: input[name="vhost"]
      value_css_selector_attribute_name: value
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '#annuncio_foto img'
      attribute_name: src
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: button[class*="accept-btn"]
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    loading_delay: 5
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: h1[class*="titolo"]
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="testo"]
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div[id="img-0"] img, .snapper_item img
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: .b-vetrina-info li strong
      value_css_selector: '.b-vetrina-info li '
      key_regex: '(.+):'
      value_regex: :(.+)
