framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    loading_delay: 3
    action_before_search_pages_browsing_module:
      - name: switch_to_iframe
        css_selector: '#ifr'
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://balaan.co.kr/shop/goods/goods_list.php?sort=new&keyword={}&size=80
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '#goods_list_area li .info_area a'
      regex: balaan.co.kr/.+goodsno=([\d]+)
      post_url_cleaning_module:
        query_string_to_keep:
          - goodsno
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: a.list-goods-link
      regex: balaan.co.kr/.+goodsno=([\d]+)
      post_url_cleaning_module:
        query_string_to_keep:
          - goodsno
      listing_container_css_selector: section.goods_list .item
      title_retriever_module:
        name: get_attribute_value
        css_selector: .goodsnm
      price_retriever_module:
        name: get_attribute_value
        css_selector: .price
        replace_old: \xec\x9b\x90
        replace_new: KRW
      pictures_retriever_module:
        name: get_pictures_from_attribute
        css_selector: a.list-goods-link img
        attribute_name: data-original
      load_more_results_module:
        name: click_on_next_page_module
        css_selector: a.page-link.next
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: '#pagination a.on ~ a'
    listing_container_css_selector: '#goods_list_area li'
    title_retriever_module:
      name: get_attribute_value
      css_selector: p.name
    price_retriever_module:
      name: get_attribute_value
      css_selector: .price
      replace_old: \xec\x9b\x90
      replace_new: KRW
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .thumb img
      attribute_name: src
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://balaan.co.kr/shop/goods/goods_view.php?goodsno={}
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[class="detail-info__spec-header"]'
    description_retriever_module:
      name: get_attribute_value
      css_selector: section.product-detail
    price_retriever_module:
      name: get_attribute_value
      css_selector: '#price'
      replace_old: \xec\x9b\x90
      replace_new: KRW
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: a.link-partner-shop
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a.link-partner-shop
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: ul.detail-info__thembnail-list li img
      attribute_name: src
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    action_before_retrieving_post_information_module:
      - name: switch_to_iframe
        css_selector: '#ifr'
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: '[class="boutique-name"]'
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[class="icon-shop"] img'
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      key_css_selectors:
        - span.partner-cnt
        - span.satisfy-cnt
      value_css_selectors:
        - span.partner-cnt
        - span.satisfy-cnt
      key_regex:
        - (.+)
        - (.+)
      value_regex:
        - (.+)
        - (.+)
      key_attributes:
        - class
        - class
      value_attributes:
        - textContent
        - textContent
