framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    loading_delay: 8
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.bestbuy.ca/en-ca/search?search={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .x-productListItem>div>a
      regex: bestbuy.ca\/en\-ca\/product\/(.+)$
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .x-productListItem>div>a
      regex: bestbuy.ca\/en\-ca\/product\/(.+)$
      action_before_poster_post_identifiers_module:
        - name: click_action_module
          css_selector: '[class*="seeAllProducts"]>a'
          after_pause_time: 10
    listing_container_css_selector: .x-productListItem>div>a
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: '[data-automation="productItemName"]'
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: '[data-automation="product-price"]>span'
      replace_old: \$
      replace_new: CAD
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[data-automation="image-slider-test"] img'
      attribute_name: src
    load_more_results_module:
      name: load_more_by_scrolling_one_scroll_at_a_time
      css_selector: '[class*="loadMoreButtonContainer"]>button'
      scroll_range: 4
      loading_delay: 6
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.bestbuy.ca/en-ca/product/{}
    take_screenshot: true
    loading_delay: 3
    title_retriever_module:
      name: get_attribute_value
      css_selector: h1[class*="productName"]
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: '[class*="productOverviewGridArea"] [class*="description"]'
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="productOfferDetailsGridArea"] [data-automation="product-price"]>div'
      replace_old: \$
      replace_new: CAD
      attribute_name: textContent
      exclude_children: true
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="soldBy"]'
      regex: by (.+)
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: '[class*="soldBy"]>a'
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_by_clicking_thumbnails
      clickable_css_selector_1: '[class*="sliderContainer"] .slick-current img'
      clickable_css_selector: .modal .x-thumbnail-gallery-control>div>div>div:not(.slick-cloned)>div>div
      picture_css_selector: '[data-automation="media-gallery-product-image-slider-modal"]>.slick-initialized
        img[class*="productImage"]'
      escape_popup_on_end: true
      attribute_name: src
      regex: (.+)
      loading_delay: 3
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    loading_delay: 10
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: h1[class*="title"]
      attribute_name: textContent
    payload_retriever_module:
      name: get_key_value_list
      clickable_css_selector: button#customerReviews
      clickable_css_is_always_present: true
      key_css_selector: .bv-secondary-rating-summary-list>div>div:first-child
      value_css_selector: .bv-secondary-rating-summary-list>div>span.bv-table-cell[aria-hidden]
