framework:
  name: selenium_framework
  proxies:
    - name: proxyrack
    - name: iproyal/us
    - name: iproyal/lithuania
    - name: 123proxy
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: button[id="cky-btn-accept"]
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.bobshop.co.za/jsp/tradesearch/TradeSearch.jsp?IncludedKeywords={}&OrderBy=Opening
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div[class*="tradelist-item-container"] > a
      regex: bobshop.co.za/item\/(.*)$
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div[class*="tradelist-item-container"] > a
      regex: bobshop.co.za/item\/(.*)$
      load_more_results_module:
        name: click_on_next_page_module
        css_selector: li.next-link
    listing_container_css_selector: div[class*="tradelist-item-container"]
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: a div[itemprop="name"]
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: a div.tradelist-item-price>span
      replace_old: R
      replace_new: ZAR
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: span.user-summary>span>a
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: span.user-summary>span>a
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: a div.tradelist-item-thumbnail>img
      attribute_name: src
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: div[class="main-content"] div:last-child ul li:last-child a
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.bobshop.co.za/item/{}
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: div.main-content h1
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: '#image_container'
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: span.price-block
      replace_old: R
      replace_new: ZAR
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div.font-weight-semibold> span > span > a
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: div.font-weight-semibold> span > span > a
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div.big-images-box img , div.single-image-box img
      attribute_name: src
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .left-sidebar .alias
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: .left-sidebar .user-store-about-block div:first-child
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .left-sidebar .user-store-logo-container img:first-child
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      clickable_css_selectors:
        - .container .main-content a[href*="/user/"]
      key_css_selectors:
        - .left-sidebar .mb-1 ~ div
        - .left-sidebar .mb-1 + div
      value_css_selectors:
        - .left-sidebar .mb-1 ~ div
        - .left-sidebar .mb-1 + div
      key_regex:
        - Positive Ratings
        - Joined
      value_regex:
        - (.+) Positive
        - Joined (.+)\,
