include: craigslist.yaml
framework: 
    search_pages_browsing_module:
        search_page_urls_builder_module:
            search_page_url_templates:
                - 'https://calgary.craigslist.org/search/sss?query={}'
                - 'https://edmonton.craigslist.org/search/sss?query={}'
                - 'https://ftmcmurray.craigslist.org/search/sss?query={}'
                - 'https://lethbridge.craigslist.org/search/sss?query={}'
                - 'https://hat.craigslist.org/search/sss?query={}'
                - 'https://peace.craigslist.org/search/sss?query={}'
                - 'https://reddeer.craigslist.org/search/sss?query={}'
                - 'https://cariboo.craigslist.org/search/sss?query={}'
                - 'https://comoxvalley.craigslist.org/search/sss?query={}'
                - 'https://abbotsford.craigslist.org/search/sss?query={}'
                - 'https://kamloops.craigslist.org/search/sss?query={}'
                - 'https://kelowna.craigslist.org/search/sss?query={}'
                - 'https://kootenays.craigslist.org/search/sss?query={}'
                - 'https://nanaimo.craigslist.org/search/sss?query={}'
                - 'https://princegeorge.craigslist.org/search/sss?query={}'
                - 'https://skeena.craigslist.org/search/sss?query={}'
                - 'https://sunshine.craigslist.org/search/sss?query={}'
                - 'https://vancouver.craigslist.org/search/sss?query={}'
                - 'https://victoria.craigslist.org/search/sss?query={}'
                - 'https://whistler.craigslist.org/search/sss?query={}'
                - 'https://winnipeg.craigslist.org/search/sss?query={}'
                - 'https://newbrunswick.craigslist.org/search/sss?query={}'
                - 'https://newfoundland.craigslist.org/search/sss?query={}'
                - 'https://territories.craigslist.org/search/sss?query={}'
                - 'https://yellowknife.craigslist.org/search/sss?query={}'
                - 'https://halifax.craigslist.org/search/sss?query={}'
                - 'https://barrie.craigslist.org/search/sss?query={}'
                - 'https://belleville.craigslist.org/search/sss?query={}'
                - 'https://brantford.craigslist.org/search/sss?query={}'
                - 'https://chatham.craigslist.org/search/sss?query={}'
                - 'https://cornwall.craigslist.org/search/sss?query={}'
                - 'https://guelph.craigslist.org/search/sss?query={}'
                - 'https://hamilton.craigslist.org/search/sss?query={}'
                - 'https://kingston.craigslist.org/search/sss?query={}'
                - 'https://kitchener.craigslist.org/search/sss?query={}'
                - 'https://londonon.craigslist.org/search/sss?query={}'
                - 'https://niagara.craigslist.org/search/sss?query={}'
                - 'https://ottawa.craigslist.org/search/sss?query={}'
                - 'https://owensound.craigslist.org/search/sss?query={}'
                - 'https://peterborough.craigslist.org/search/sss?query={}'
                - 'https://sarnia.craigslist.org/search/sss?query={}'
                - 'https://soo.craigslist.org/search/sss?query={}'
                - 'https://sudbury.craigslist.org/search/sss?query={}'
                - 'https://thunderbay.craigslist.org/search/sss?query={}'
                - 'https://toronto.craigslist.org/search/sss?query={}'
                - 'https://windsor.craigslist.org/search/sss?query={}'
                - 'https://pei.craigslist.org/search/sss?query={}'
                - 'https://montreal.craigslist.org/search/sss?query={}'
                - 'https://quebec.craigslist.org/search/sss?query={}'
                - 'https://saguenay.craigslist.org/search/sss?query={}'
                - 'https://sherbrooke.craigslist.org/search/sss?query={}'
                - 'https://troisrivieres.craigslist.org/search/sss?query={}'
                - 'https://regina.craigslist.org/search/sss?query={}'
                - 'https://saskatoon.craigslist.org/search/sss?query={}'
                - 'https://whitehorse.craigslist.org/search/sss?query={}'

    archiving_options: 
        scroll_to_bottom: True
