framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    loading_delay: 2
    search_page_urls_builder_module:
      name: search_page_urls_builder_from_multiple_url_templates_module
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: a[href^="/p/"]
      regex_substitute: (?<=carousell\.com\/p\/).*-
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: a[href^="/p/"]
      regex_substitute: (?<=carousell\.com\/p\/).*-
      load_more_results_module:
        name: load_more_by_click
        css_selector: div > div:nth-of-type(2) + button
    load_more_results_module:
      name: load_more_by_click
      css_selector: div[class*="browse-listings"]>button
    listing_container_css_selector: div[data-testid*="listing-card"]
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: a[href*="/p/"]>p:first-of-type
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: a[href*="/p/"]>p:first-of-type~div>p
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: p[data-testid="listing-card-text-seller-name"]
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a[href*="/u/"]
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute_with_replace
      css_selector: img[src*="_thumbnail"]
      attribute_name: src
      replace_old: _thumbnail
      replace_new: ''
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: meta[property="og:title"]
      attribute_name: content
    description_retriever_module:
      name: get_json_value
      css_selector: script[type="application/ld+json"]
      output_string: '{jsons[0]["description"]}'
    price_retriever_module:
      name: get_attribute_value
      attribute_name: content
      css_selector: meta[name="twitter:data1"]
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: a[href^="/u/"][href$="/"]
      attribute_name: href
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a[href*="/u/"]
      attribute_name: href
      regex: (.+/u/.+/)
    ships_from_retriever_module:
      name: get_key_value_list
      key_css_selector: img[src*="location"] ~ p
      value_css_selector: img[src*="location"] ~ p
    ships_to_retriever_module:
      name: get_key_value_list
      key_css_selector: img[src*="location"] ~ input
      key_css_selector_attribute_name: placeholder
      value_css_selector: img[src*="location"] ~ input
      value_css_selector_attribute_name: placeholder
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div[id*="FieldSetField-Container-field"][class=""]>div>div>div>img[alt]
      attribute_name: src
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    loading_delay: 2
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: title
      regex: (.+).s item
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: div h2 ~ div ~ div ~ div ~ div > p
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img[src*="/photos/profiles/"]
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      key_css_selectors:
        - a[href*="/followers/"]
        - a[href*="/following/"]
        - '#main div div div div div:nth-of-type(2) + p'
        - '#main div div div div div:nth-of-type(2) ~ p'
        - div img[src*="verification"]:nth-of-type(1)
        - div img[src*="verification"]:nth-of-type(2)
        - div img[src*="verification"]:nth-of-type(3)
        - div img[src*="verification"]:nth-of-type(4)
        - div img[src*="verification"]:nth-of-type(5)
        - div img[src*="verification"]:nth-of-type(6)
        - '#main div div div div div:nth-of-type(2) p + div'
        - '#main div div div div div:nth-of-type(2) p ~ div'
      value_css_selectors:
        - a[href*="/followers/"]
        - a[href*="/following/"]
        - '#main div div div div div:nth-of-type(2) + p'
        - '#main div div div div div:nth-of-type(2) ~ p'
        - div img[src*="verification"]:nth-of-type(1)
        - div img[src*="verification"]:nth-of-type(2)
        - div img[src*="verification"]:nth-of-type(3)
        - div img[src*="verification"]:nth-of-type(4)
        - div img[src*="verification"]:nth-of-type(5)
        - div img[src*="verification"]:nth-of-type(6)
        - '#main div div div div div:nth-of-type(2) p'
        - '#main div div div div div:nth-of-type(2) p:nth-of-type(2)'
      key_regex:
        - Followers
        - Following
        - Joined
        - in
        - verification-([^-]+)-
        - verification-([^-]+)-
        - verification-([^-]+)-
        - verification-([^-]+)-
        - verification-([^-]+)-
        - verification-([^-]+)-
        - \d+ (.+)
        - c
      value_regex:
        - (.+) Followers
        - (.+) Following
        - Joined (.+)
        - ([^\<\&]+)
        - verification
        - verification
        - verification
        - verification
        - verification
        - verification
        - (.+)
        - (\d+)
      key_attributes:
        - textContent
        - textContent
        - innerHTML
        - innerHTML
        - src
        - src
        - src
        - src
        - src
        - src
        - aria-label
        - innerHTML
      value_attributes:
        - textContent
        - textContent
        - innerHTML
        - innerHTML
        - src
        - src
        - src
        - src
        - src
        - src
        - textContent
        - textContent
