include: carrefour-me.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.carrefourjordan.com/mafjor/en/v4/search?keyword={}
    post_identifiers_retriever_module:
      regex: carrefourjordan.com\/mafjor\/(.+)
  post_information_retriever_module:
    post_url_template: https://www.carrefourjordan.com/mafjor/{}