include: carrefour-me.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.carrefour.ke/mafken/en/v4/search?keyword=bags
    post_identifiers_retriever_module:
      regex: carrefour.ke\/mafken\/(.+)
  post_information_retriever_module:
    post_url_template: https://www.carrefour.ke/mafken/{}