framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    take_screenshots: true
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.catch.com.au/search?query={}&search_src=topbar&ac=0
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div[class*="wr32q5"] div[data-ts="product-card"] a[data-ts="product-card-link"]
      regex: https://www.catch.com.au\/product\/(.*)
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div[class*="wr32q5"] div[data-ts="product-card"] a[data-ts="product-card-link"]
      regex: https://www.catch.com.au\/product\/(.*)
      action_before_poster_post_identifiers_module:
        - name: click_action_module
          css_selector: a.nav-tabs__item-link[aria-controls="products"]
        - name: click_action_module
          css_selector: a.seller-product-btn
          before_pause_time: 3
    listing_container_css_selector: div[class*="wr32q5"] div[data-ts="product-card"]
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: nav[class*="6ee5lt"]>a:last-child
    title_retriever_module:
      name: get_attribute_value
      css_selector: h2>a
    price_retriever_module:
      name: get_attribute_value
      css_selector: div[data-testid="product-price"] div[data-testid="price-parts"]
      replace_old: \$
      replace_new: 'USD '
      attribute_name: aria-label
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: picture > img
      attribute_name: src
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.catch.com.au/product/{}
    title_retriever_module:
      name: get_attribute_value
      css_selector: h1[data-testid="product-title"]
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div[itemprop="description"]
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: section[class*="eq6937"] div[data-testid="product-price"] div[data-testid="price-parts"]
      attribute_name: aria-label
      replace_old: \$
      replace_new: 'USD '
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: p[data-testid="sold-by"]>a
      attribute_name: textContent
      loading_delay: 0.1
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: p[data-testid="sold-by"]>a
      attribute_name: href
      loading_delay: 0.1
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: div.carousel > div[class*="verticalSlider"] div[aria-label="slide"]:first-child
        img
      clickable_css_selector_2: div[class*="slide-btn-next"]
      picture_css_selector: 'div.fslightbox-container>div:last-child>div:not([style="display:
        none;"], [style*="transform"] ) img'
      attribute_name: src
      regex: (.+)
      escape_popup_on_end: true
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: h1.seller-page-title
      regex: (.+) Profile
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: ul.seller-stats--desktop li.seller-stats__item>span[class*="label"]
      value_css_selector: ul.seller-stats--desktop li.seller-stats__item>span[class*="value"]
