framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    loading_delay: 5
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.chotot.com/mua-ban?q={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div[class*="ListAds_ListAds_"]>ul>div>li>a
      regex: chotot.com\/(.+).htm
    listing_container_css_selector: div[class*="ListAds_ListAds_"]>ul>div>li
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: a h3[class*="_adTitle_"]
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: a p[class*="AdBody_adPriceNormal_"]
      replace_old: \đ
      replace_new: VND
    location_retriever_module:
      name: get_attribute_value
      css_selector: a div[class*="AdItemFooter_wrapper"]>div>span:last-child
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: a div[class*="AdThumbnail_AdThumbnail_"] img
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: div[class*="Paging_Paging_"]>div:last-child>button
      loading_delay: 5
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: li.listItem li>a
      regex: chotot.com\/(.+).htm
      load_more_results_module:
        name: click_on_next_page_module
        css_selector: li.listItem a>span [data-testid="ArrowForwardIosIcon"] , ul>li>[class="last"]
      listing_container_css_selector: li.listItem li
      title_retriever_module:
        name: get_attribute_value
        attribute_name: textContent
        css_selector: a>div>div>div:first-child>h3
      price_retriever_module:
        name: get_attribute_value
        attribute_name: textContent
        css_selector: a>div>div>div>[itemprop="price"]
        replace_old: \đ
        replace_new: VND
      location_retriever_module:
        name: get_attribute_value
        css_selector: :scope>div>div>div:last-child>span
        attribute_name: textContent
      pictures_retriever_module:
        name: get_pictures_from_attribute
        css_selector: a>div>div>div img
        attribute_name: src
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.chotot.com/{}.htm
    take_screenshot: true
    loading_delay: 2
    title_retriever_module:
      name: get_attribute_value
      css_selector: h1[itemprop="name"]
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: p[class*="AdDecription_adBody_"]
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: span[itemprop="price"]
      replace_old: \đ
      replace_new: VND
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="SellerProfile_nameDiv_"]
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a[class*="SellerProfile_sellerWrapper_"]
      attribute_name: href
    location_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="AdParam_address_"]>span
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_2: div[class*="AdImage_adImageWrapper_"]>div>button[aria-label="Next"]
      loading_delay: 2
      picture_css_selector: div[class*="AdImage_adImageWrapper_"] div.slick-active
        span>img
      attribute_name: src
      regex: (.+)
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    loading_delay: 3
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .InfoWrapper>.name
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .AvatarWrapper>div>img
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: div.ExtraInfo>div
      value_css_selector: div.ExtraInfo>div
      key_regex: '(.+)\:'
      value_regex: \:(.+)
