framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    loading_delay: 4
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.conforama.ch/de/search/{}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .cx-product-container div.o-product-list__grid-item a.a-tile__link
      regex: conforama.ch\/de\/(.+)
    listing_container_css_selector: .cx-product-container div.o-product-list__grid-item
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .a-tile__title
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: span.a-price__price
      replace_old: (.+)
      replace_new: EUR \g<1>
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img.a-media__img
      attribute_name: src
    load_more_results_module:
      name: load_more_by_click
      css_selector: .confo-load-more-button>button
      loading_delay: 3
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: .cx-banner-buttons>button.btn-primary
  post_information_retriever_module:
    name: post_information_retriever_with_creation_of_a_new_driver_for_each_post_module
    post_url_template: https://www.conforama.ch/de/{}
    take_screenshot: true
    loading_delay: 1
    title_retriever_module:
      name: get_attribute_value
      css_selector: .confo-product-name
    price_retriever_module:
      name: get_attribute_value
      css_selector: .m-product-summary__price span.a-price__price
      replace_old: (.+)
      replace_new: EUR \g<1>
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: cx-product-images>cx-media>img
      clickable_css_selector_2: .cx-dialog-body .cx-navigate-image>button>[key="chevronRight"]
      picture_css_selector: .cx-dialog-body .cx-main-image-group>cx-media>img
      attribute_name: src
      regex: (.+)
      close_button_css_selector: .cx-dialog-content button.close
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: .cx-banner-buttons>button.btn-primary
