framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: search_page_urls_builder_from_multiple_url_templates_module
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: a[href*="craigslist.org"]
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: a[href*="craigslist.org"]
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: a.button.next
    listing_container_css_selector: div[id*="search-results"] li, ul#search-results
      li
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[class="result-heading"], [class="label"]'
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[class="result-price"], [class="priceinfo"]'
    location_retriever_module:
      name: get_attribute_value
      css_selector: '[class="result-hood"], .meta, [class="nearby"]'
      regex: ([^\xc2\xb7]+$)
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[class="swipe-wrap"] img, .gallery-inner img'
      attribute_name: src
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: '{}'
    loading_delay: 2
    title_retriever_module:
      name: get_attribute_value
      css_selector: 'span.postingtitletext #titletextonly'
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: '#postingbody'
      attribute_name: textContent
    price_retriever_module:
      name: get_json_value
      css_selector: script[type="application/ld+json"]
      output_string: '{jsons[1]["offers"]["price"]} {jsons[1]["offers"]["priceCurrency"]}'
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: p.attrgroup:first-of-type
      regex: manufacturer\:.\<b\>(.+)\<.b\>
      attribute_name: outerHTML
      loading_timeout: 0.1
    poster_link_retriever_module:
      name: get_attribute_value
      css_selector: .otherpostings a
      attribute_name: href
      loading_timeout: 0.1
    ships_from_retriever_module:
      name: get_key_value_list_from_different_elements
      key_css_selectors:
        - '#map'
        - '#map'
      value_css_selectors:
        - '#map'
        - '#map'
      key_attributes:
        - outerHTML
        - outerHTML
      value_attributes:
        - data-latitude
        - data-longitude
      key_regex:
        - latitude
        - longitude
      value_regex:
        - (.+)
        - (.+)
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: .userbody [class="swipe-wrap"] > div[style*="translate(0px,
        0px)"]
      hover_before_click_css_selector: .gallery.big [class="swipe-wrap"] div.slide[style*="translate(0px,
        0px)"]
      clickable_css_selector_2: .gallery.big span.slider-forward.arrow
      picture_css_selector: .gallery.big [class="swipe-wrap"] div.slide[style*="translate(0px,
        0px)"] img
      regex: (.+)
      attribute_name: src
      escape_popup_on_end: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: .b-cookie-hint__button
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    loading_delay: 1
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .b-seller-info__name
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute_with_replace
      css_selector: .b-seller-info-header__avatar
      attribute_name: style
      replace_old: 'background-image: url("'
      replace_new: ''
      replace_tail: '");'
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      key_css_selectors:
        - .b-seller-info__location
        - .b-seller-info-rl>div:first-child>p:last-child
        - .b-seller-info-rl>div:last-child>p:last-child
        - '[class*="feedback-stats__value--positive"]'
        - '[class*="feedback-stats__value--neutral"]'
        - '[class*="feedback-stats__value--negative"]'
      value_css_selectors:
        - .b-seller-info__location
        - .b-seller-info-rl>div:first-child>p:first-child
        - .b-seller-info-rl>div:last-child>p:first-child
        - '[class*="feedback-stats__value--positive"]'
        - '[class*="feedback-stats__value--neutral"]'
        - '[class*="feedback-stats__value--negative"]'
      key_regex:
        - location
        - (.+)
        - (.+)
        - positive
        - neutral
        - negative
      value_regex:
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
      key_attributes:
        - class
        - textContent
        - textContent
        - class
        - class
        - class
      value_attributes:
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
