framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  proxies:
    - name: iproyal/us
    - name: proxys.io/mobile/dedicated/th
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 4
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - http://search.dangdang.com/?key={}&act=input
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: ul.list_aa li[class*="line"] > a
      regex: product.dangdang.com\/(.*)
      listing_container_css_selector: ul.list_aa li[class*="line"]
      load_more_results_module:
        name: go_to_next_page_module
        css_selector: div.paginating a.nex
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div#search_nature_rg li a[name="itemlist-title"]
      regex: product.dangdang.com\/(.*)
    listing_container_css_selector: div#search_nature_rg li
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: div.paginating ul li.next>a
    title_retriever_module:
      name: get_attribute_value
      css_selector:  a[name="itemlist-title"]
    price_retriever_module:
      name: get_attribute_value
      css_selector: p.price span:first-child
      replace_old: \¥
      replace_new: 'CNY '
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: a[name="itemlist-shop-name"]
      loading_timeout: 0.1
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a[name="itemlist-shop-name"]
      attribute_name: href
      loading_timeout: 0.1
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: a.pic img
      attribute_name: src
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: http://product.dangdang.com/{}
    loading_delay: 3
    title_retriever_module:
      name: get_attribute_value
      css_selector: div.name_info h1
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div#detail
    price_retriever_module:
      name: get_attribute_value
      css_selector: p#dd-price
      replace_old: \¥
      replace_new: 'CNY '
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: span.shop-name a
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: span.shop-name a
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute_with_replace
      css_selector: ul#main-img-slider li a
      replace_old: '//'
      replace_new: 'https://'
      attribute_name: 'data-imghref'
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: p.shop_name
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div.shop_logo img
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: ul.shop_info li
      value_css_selector: ul.shop_info li
      key_regex: '(.+)\：'
      value_regex: '\：(.+)'
