include: depop.yaml
framework:
  driver_initialization_module:
    cookies:
      properties:
        location: us
  search_pages_browsing_module:
    price_retriever_module:
      replace_old: \$
      replace_new: USD
  post_information_retriever_module:
    price_retriever_module:
      replace_old: \$
      replace_new: USD
