framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 12
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: button.RedirectModal__close-modal
        loading_delay: 1
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div.SearchPage div.ProductBoxView > a
    listing_container_css_selector: div.SearchPage div.ProductBoxView
    load_more_results_module:
      name: load_more_by_click
      css_selector: button[class*="load-more"]
      loading_delay: 6
      scroll_pause_time: 0
    title_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="title"]
    price_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="discount"] > span:first-child
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img[class*="image"]
      attribute_name: src
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: div.title-text
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div.description
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: .price-box .current-price
      attribute_name: textContent
    stock_retriever_module:
      name: get_attribute_value
      css_selector: div.stock-count
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_by_clicking_thumbnails
      clickable_css_selector: .product-thumbnails>div.product-thumbnails-item
      picture_css_selector: div.image-box img.product-image
      attribute_name: src
      regex: (.+)
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: button.RedirectModal__close-modal
        loading_delay: 1
