include: desertcart.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.desertcart.ph/search/{}
    post_identifiers_retriever_module:
      regex: desertcart.ph\/products\/(.*)
    price_retriever_module:
      replace_old: \₱
      replace_new: 'PHP '
  post_information_retriever_module:
    post_url_template: https://www.desertcart.ph/products/{}
    price_retriever_module:
      replace_old: \₱
      replace_new: 'PHP '