include: desertcart.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.desertcart.ma/search/{}
    post_identifiers_retriever_module:
      regex: desertcart.ma\/products\/(.*)
    price_retriever_module:
      replace_old: \د\.\م\.
      replace_new: MAD
  post_information_retriever_module:
    post_url_template: https://www.desertcart.ma/products/{}
    price_retriever_module:
      replace_old: \د\.\م\.
      replace_new: MAD