framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 5
    action_before_search_pages_browsing_module:
      - name: click_action_module
        after_pause_time: 3
        css_selector: .cJjQzCs7>svg
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.douyin.com/search/{}?enter_from=recommend&source=normal_search
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '[style="display:block"] ul[data-e2e="scroll-list"]>li a[href*="/video/"]'
      regex: douyin.com\/video\/(.+)$
    listing_container_css_selector: '[style="display:block"] ul[data-e2e="scroll-list"]>li'
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: '.swoZuiEM , .video-info-detail span.Nu66P_ba'
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .OhTcPZd3
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .videoImage img
      attribute_name: src
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '[data-e2e="user-post-list"] [data-e2e="scroll-list"]>li>div>a[href*="/video/"]'
      regex: douyin.com\/video\/(.+)$
      listing_container_css_selector: '[data-e2e="user-post-list"] ul[data-e2e="scroll-list"]>li'
      title_retriever_module:
        name: get_attribute_value
        attribute_name: textContent
        css_selector: 'div>a[href*="/video/"]>p'
      pictures_retriever_module:
        name: get_pictures_from_attribute
        css_selector: a img
        attribute_name: src
    load_more_results_module:
      name: load_more_by_scrolling_one_scroll_at_a_time
      scroll_pause_time: 1.5
      scroll_range: 2
      loading_delay: 6
  post_information_retriever_module:
    name: post_information_retriever_with_creation_of_a_new_driver_for_each_post_module
    post_url_template: https://www.douyin.com/video/{}
    take_screenshot: true
    loading_delay: 5
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector:
          - a#verify-bar-close>svg
          - '#login-pannel .dy-account-close'
        after_pause_time: 1
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[data-e2e="detail-video-info"] [class="Nu66P_ba"], h1 [class="Nu66P_ba"]'
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: '[data-e2e="user-info"]>div.CjPRy13J>a'
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: '[data-e2e="user-info"]>div>a'
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[data-e2e="note-container"]>div:last-of-type>div>img'
      attribute_name: src
    videos_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div.video-detail-container .xg-video-container>video>source:last-of-type
      attribute_name: src
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    loading_delay: 5
    take_screenshot: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector:
          - a#verify-bar-close>svg
          - '#login-pannel .dy-account-close'
        after_pause_time: 1
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: '[data-e2e="user-info"] h1 .Nu66P_ba'
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: '[data-e2e="user-info"] p .Nu66P_ba'
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[data-e2e="live-avatar"]>img'
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: '[data-e2e="user-info"]>p:first-of-type>span'
      value_css_selector: '[data-e2e="user-info"]>p:first-of-type>span'
      key_regex: (.+)\：
      value_regex: \：(.+)
