include: dubizzle.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.dubizzle.sa/ads/q-{}/?search%5Border%5D=created_at%3Adesc
    poster_post_identifiers_retriever_module:
      regex: dubizzle.sa/ad/(.+).html
    post_identifiers_retriever_module:
      regex: dubizzle.sa/ad/(.+).html
    price_retriever_module:
      replace_old: \xd8\xb1.\xd8\xb3
      replace_new: SAR
  post_information_retriever_module:
    post_url_template: https://www.dubizzle.sa/ad/{}.html
    price_retriever_module:
      replace_old: \xd8\xb1.\xd8\xb3
      replace_new: SAR
