include: dubizzle.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.dubizzle.com.bh/ads/q-{}/
    post_identifiers_retriever_module:
      regex: (?<=dubizzle.com.bh\/ad\/)(.*)(\.html)
    poster_post_identifiers_retriever_module:
      regex: (?<=dubizzle.com.bh\/ad\/)(.*)(\.html)
  post_information_retriever_module:
    post_url_template: https://www.dubizzle.com.bh/ad/{}.html