include: dubizzle.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.dubizzle.com.om/ads/q-{}/
    post_identifiers_retriever_module:
      regex: (?<=dubizzle.com.om\/ad\/)(.*)(\.html)
    poster_post_identifiers_retriever_module:
      regex: (?<=dubizzle.com.om\/ad\/)(.*)(\.html)
    price_retriever_module:
      replace_old: '  \xd8\xb1. \xd8\xb9'
      replace_new: ' OMR'
  post_information_retriever_module:
    post_url_template: https://www.dubizzle.com.om/ad/{}.html
    price_retriever_module:
      replace_old: '  \xd8\xb1. \xd8\xb9'
      replace_new: ' OMR'