include: dubizzle.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.dubizzle.com.lb/ads/q-{}/?search%5Border%5D=created_at%3Adesc
    poster_post_identifiers_retriever_module:
      regex: dubizzle.com.lb/ad/(.+).html
    post_identifiers_retriever_module:
      regex: dubizzle.com.lb/ad/(.+).html
  post_information_retriever_module:
    post_url_template: https://www.dubizzle.com.lb/ad/{}.html
    vendor_retriever_module:
      css_selector: '[aria-label="Seller description"] a>div>div>span'
    poster_link_retriever_module:
      css_selector: '[aria-label="Seller description"] a'