framework:
  name: selenium_framework
  proxies:
    - name: proxyrack
    - name: iproyal/us
    - name: iproyal/lithuania
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
    undetected_driver: true
    headless: false
    xvfb: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '#srp-river-results a.s-item__link'
      regex: (?<=\/itm\/)(.*)
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .item_title a , a[href*="/itm/"]
      regex: (?<=\/itm\/)(.*)
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: nav[role="navigation"] a[type="next"]
    listing_container_css_selector: ul.srp-results>li.s-item, article.str-item-card
    title_retriever_module:
      name: get_attribute_value
      css_selector: div.s-item__title>span, h3.str-card-title
    price_retriever_module:
      name: get_attribute_value
      css_selector: span.s-item__price, span[class*="-displayPrice"]
    pictures_retriever_module:
      name: get_pictures_from_attribute_with_replace_regex
      css_selector: div.s-item__image-wrapper>img, picture.str-image img
      attribute_name: src
      replace_old_regex: -l\d+\.
      replace_new: -l1600.
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector:
          - '#gdpr-banner-accept'
          - .str-pagination ~ a
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.ebay.com/itm/{}
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: .x-item-title
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: '#viTabs_0_is'
      attribute_name: textContent
    price_retriever_module:
      name: get_json_value
      css_selector: '[data-testid*="structured-data"]>script[type*="json"]'
      output_string: '{jsons[0]["offers"]["price"]} {jsons[0]["offers"]["priceCurrency"]}'
    stock_retriever_module:
      name: get_attribute_value
      css_selector: .d-quantity__availability
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: a[href*="https://www.ebay.com/usr/"] span
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .ux-seller-section a[href*="https://www.ebay.com/usr"]
      attribute_name: href
    location_retriever_module:
      name: get_attribute_value
      css_selector: '#SRPSection'
      attribute_name: textContent
      regex: 'Located in: (.*?)Delivery:'
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: .ux-image-carousel-container
      clickable_css_selector_2: div[data-testid="ux-large-image-carousel"] button.btn-next
      picture_css_selector: div[data-testid="ux-large-image-carousel"] .ux-image-carousel-item.active.image
        img:not([src*="NoImg"])
      regex: (.+)
      attribute_name: src
      skip_video: true
      escape_popup_on_end: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: '#gdpr-banner-accept'
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .str-seller-card__store-name h1
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      clickable_css_selector: '#str-tab-tab1>span'
      css_selector: section.str-about-description__about-intro
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .str-seller-card__store-logo a img
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      clickable_css_selectors:
        - div#str-tab-tab2>span
      key_css_selectors:
        - section.str-about-description__seller-info>span:nth-child(1)>span:nth-child(1)
        - section.str-about-description__seller-info>span:nth-child(2)>span:nth-child(1)
        - div.fdbk-overall-rating__details>div:first-child>span
        - div.fdbk-overall-rating__details>div:nth-child(2)>span
        - div.fdbk-overall-rating__details>div:nth-child(3)>span
        - div.str-seller-card__stats-content div:nth-of-type(1)
        - div.str-seller-card__stats-content div:nth-of-type(2)
        - div.str-seller-card__stats-content div:nth-of-type(3)
      value_css_selectors:
        - section.str-about-description__seller-info>span:nth-child(1)>span:nth-child(2)
        - section.str-about-description__seller-info>span:nth-child(2)>span:nth-child(2)
        - div.fdbk-overall-rating__details>div:nth-child(1)>a>span:first-child
        - div.fdbk-overall-rating__details>div:nth-child(2)>a>span:first-child
        - div.fdbk-overall-rating__details>div:nth-child(3)>a>span:first-child
        - div.str-seller-card__stats-content div:nth-of-type(1)>a>span
        - div.str-seller-card__stats-content div:nth-of-type(2)>span
        - div.str-seller-card__stats-content div:nth-of-type(3)>span
      key_regex:
        - '(.+)\:'
        - '(.+)\:'
        - (.+)
        - (.+)
        - (.+)
        - </span>([^<]+)
        - </span>([^<]+)
        - </span>([^<]+)
      value_regex:
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
      key_attributes:
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - innerHTML
        - innerHTML
        - innerHTML
      value_attributes:
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: '#gdpr-banner-accept'
