framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    take_screenshots: true
    loading_delay: 3
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.ec21.com/ec-market/{}.html
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div.conProduct_gallery li[itemprop="itemListElement"] h2 a[itemprop="url"]
      regex: ec21.com\/product-details\/(.*)
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: ul.product_area li[class*="thd"] dt > a
      regex: ec21.com\/(.*)
      listing_container_css_selector: ul.product_area li[class*="thd"]
      title_retriever_module:
        name: get_attribute_value
        css_selector: dt > a
      price_retriever_module:
        name: get_attribute_value
        css_selector: span.ty_p
        regex: (.*)\\*
        replace_old: US\$
        replace_new: USD
      pictures_retriever_module:
        name: get_pictures_from_attribute
        css_selector: a > img
        attribute_name: src
      action_before_poster_post_identifiers_module:
        - name: click_action_module
          css_selector: '#body_w ul#gnb_menu > li:nth-child(2)'
          after_pause_time: 3
    listing_container_css_selector: div.conProduct_gallery li[itemprop="itemListElement"]
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: div[class*="pageing"] a.bt_nx
    title_retriever_module:
      name: get_attribute_value
      css_selector: h2[itemprop="name"] a
    price_retriever_module:
      name: get_attribute_value
      css_selector: span[itemprop="price"]
      replace_old: .+
      replace_new: \g<0> USD
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: li[itemprop="manufacturer"] a
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: li[itemprop="manufacturer"] a
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div.galleryImg > a > img
      attribute_name: src
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.ec21.com/product-details/{}
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: h1[itemprop="name"]
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div[itemprop="description"]
      attribute_name: textContent
      trim_text: true
    price_retriever_module:
      name: get_attribute_value
      css_selector: span[itemprop="pricecurrency"]
      replace_old: US\$
      replace_new: 'USD '
      trim_text: true
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div.supplierInfo > ul > li:first-child a
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: div.supplierInfo > ul > li:first-child a
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_by_clicking_thumbnails
      clickable_css_selector: li.videoClick img
      picture_css_selector: img[id="clickImage"]
      regex: (.+)
      attribute_name: src
      loading_delay: 2
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: ul.script_box3:first-of-type li:first-of-type span.txt
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div.par_g
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div#thumb_view img
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: ul.script_box3 li span.title
      value_css_selector: ul.script_box3 li span.txt
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: img#mainImg
