framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 2
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: ul#product-list-grid>li.product-item>a
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: ul#product-list-grid>li.product-item>a
    listing_container_css_selector: ul#product-list-grid>li.product-item
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .product-details>h2
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .product-details>a.product-category
      attribute_name: textContent
      loading_timeout: 0.1
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .product-details>a.product-category
      attribute_name: href
      loading_timeout: 0.1
    price_retriever_module:
      name: get_attribute_value
      css_selector: div>.btn-inverse
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .product-image>img
      attribute_name: src
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: .pagination-controls>li>a[data-original-title="Next Page"]
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.ecrater.com/p/{}
    take_screenshot: true
    loading_delay: 3
    title_retriever_module:
      name: get_attribute_value
      css_selector: '#product-title>h1'
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div#expandedDetailsContent
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: '#product-title .btn-inverse'
      replace_old: \$
      replace_new: USD
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: '#seller-contact a.seller-username'
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: '#seller-contact a.seller-username'
      attribute_name: href
    stock_retriever_module:
      name: get_attribute_value
      css_selector: '#product-quantity'
      attribute_name: textContent
    ships_to_retriever_module:
      name: get_key_value_list
      clickable_css_selector: '#product-details a[data-url*="check-shipping"]'
      key_css_selector: '#shipping-rates .controls>select>option'
      value_css_selector: '#shipping-rates .controls>select>option'
      loading_delay: 2
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: '#product-image-container a#product-image'
      clickable_css_selector_2: '#image-zoom.modal .modal-navigation a.next>span'
      picture_css_selector: '#image-zoom.modal .modal-body>img'
      close_button_css_selector: .modal-header>button.close
      attribute_name: src
      regex: (.+)
      loading_delay: 2
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    poster_url_replace_old_regex: ^((?!\/filter\.php).)*$
    poster_url_replace_new: /filter.php
    loading_delay: 2
    take_screenshot: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: '#header div.logo'
        after_pause_time: 2
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: '#page-header-title>h1>span'
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: '#sidebar #about'
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div.logo>a>img
      attribute_name: src
