include: emag.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.emag.ro/search/{}?ref=effective_search
    poster_post_identifiers_retriever_module:
      regex: emag.ro\/(.+)$
    post_identifiers_retriever_module:
      regex: emag.ro\/(.+)$
    price_retriever_module:
      replace_old: Lei
      replace_new: RON
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.emag.ro/{}
    price_retriever_module:
      replace_old: Lei
      replace_new: RON