include: emag.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.emag.hu/search/{}?ref=effective_search
    poster_post_identifiers_retriever_module:
      regex: emag.hu\/(.+)$
    post_identifiers_retriever_module:
      regex: emag.hu\/(.+)$
    price_retriever_module:
      replace_old: Ft
      replace_new: HUF
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.emag.hu/{}
    price_retriever_module:
      replace_old: Ft
      replace_new: HUF