framework:
  name: selenium_framework_from_specified_urls
  driver_initialization_module:
    name: classic_selenium_initialization_module
    headless: true
    load_images: true
  login_module:
    name: classic_login_module
    login_page_url: https://www.facebook.com
    cookies_css_selector: '[title="Allow essential and optional cookies"]'
    username_css_selector: '[id="email"]'
    password_css_selector: '[id="pass"]'
    submit_css_selector: '[name="login"]'
    username: antoine.bellami@navee.co
    password: thebeastbynavee!
  post_url_cleaning_module:
    skip_query_string_cleaning: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.facebook.com/hashtag/{}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .v1Nh3 > a
      regex: p\/(.*)\/$
    load_more_results_module:
      name: load_more_by_scrolling_module
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.facebook.com/{}
    loading_delay: 5
    take_screenshot: true
    record_redirection_url: false
    description_retriever_module:
      name: get_attribute_value
      css_selector: '[id*="jsc_c_"] > div > div > span, div.xkhd6sd.x1g2khh7.x4uap5.xyinxu5
        > span'
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: '[id*="jsc_c_"] > span > strong:nth-child(1) > span > a > span
        > span, [id*="jsc_c_"] > span > a, span.xt0psk2 > a[tabindex="0"]'
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img.x1ey2m1c, img.x85a59c
      attribute_name: src
    only_send_business_accounts_posts: false
    save_posts_in_specific_scraper_database: false
