framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: search_only_browsing_module
    scroll_down_after_get_new_page: true
    loading_delay: 4
    post_url_template: '{}'
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://feebee.com.tw/s/?q={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: ol#list_view>li.items>span.items_container>a:first-child
      post_url_cleaning_module:
        skip_query_string_cleaning: true
    listing_container_css_selector: ol#list_view>li.items
    title_retriever_module:
      name: get_attribute_value
      attribute_name: title
      css_selector: span.items_container>a:first-child
    price_retriever_module:
      name: get_attribute_value
      attribute_name: aria-label
      css_selector: span.price[aria-label]
      replace_old: NT\$
      replace_new: TWD
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .img_container img
      attribute_name: data-src
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: .pagination>li>a.page_next
  archiving_options:
    scroll_sleep: 0.005
    remove_elements:
      - a#cookieChoiceDismiss
