include: fruugo.yaml
framework:
    search_pages_browsing_module:
      search_page_urls_builder_module:
        search_page_url_templates:
          - https://www.fruugo.se/search/?q={}&language=en
      poster_post_identifiers_retriever_module:
        regex: fruugo.se\/(.+)$
      post_identifiers_retriever_module:
        regex: fruugo.se\/(.+)$
      price_retriever_module:
        replace_old: kr
        replace_new: SEK
    post_information_retriever_module:
      name: classic_post_information_retriever_module
      post_url_template: https://www.fruugo.se/{}?language=en
      price_retriever_module:
        replace_old: kr
        replace_new: SEK