include: fruugo.yaml
framework:
    search_pages_browsing_module:
      search_page_urls_builder_module:
        search_page_url_templates:
          - https://www.fruugo.co.nz/search/?q={}
      poster_post_identifiers_retriever_module:
        regex: fruugo.co.nz\/(.+)$
      post_identifiers_retriever_module:
        regex: fruugo.co.nz\/(.+)$
      price_retriever_module:
        replace_old: \$
        replace_new: NZD
    post_information_retriever_module:
      name: classic_post_information_retriever_module
      post_url_template: https://www.fruugo.co.nz/{}
      price_retriever_module:
        replace_old: \$
        replace_new: NZD