include: fruugo.yaml
framework:
    search_pages_browsing_module:
      search_page_urls_builder_module:
        search_page_url_templates:
          - https://www.fruugo.cz/search/?q={}&language=en
      poster_post_identifiers_retriever_module:
        regex: fruugo.cz\/(.+)$
      post_identifiers_retriever_module:
        regex: fruugo.cz\/(.+)$
      price_retriever_module:
        replace_old: K\č
        replace_new: CZK
    post_information_retriever_module:
      name: classic_post_information_retriever_module
      post_url_template: https://www.fruugo.cz/{}?language=en
      price_retriever_module:
        replace_old: K\č
        replace_new: CZK