framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 2
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://globaltradeplaza.com/search-products?keyword={}
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .main-gallery div.item a
      regex: globaltradeplaza.com\/product\/(.*)
      action_before_poster_post_identifiers_module:
        - name: click_action_module
          css_selector: li#showcase
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div#showProducts div.t-box div.info div.col-12:first-of-type h6
        a
      regex: globaltradeplaza.com\/product\/(.*)
    listing_container_css_selector: div#showProducts div.t-box
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: div#react-paginate li:last-of-type a
    title_retriever_module:
      name: get_attribute_value
      css_selector: div.info div.col-12:first-of-type h6 a
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .company-info h6 a
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .company-info h6 a
      attribute_name: href
    price_retriever_module:
      name: get_attribute_value
      css_selector: ul.attributes li:last-of-type
      replace_old: Price -
      replace_new: USD
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img.product-img
      attribute_name: src
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://globaltradeplaza.com/product/{}
    title_retriever_module:
      name: get_attribute_value
      css_selector: h1.name
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: p#description
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: span.price
      attribute_name: textContent
      replace_old: \$
      replace_new: USD
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: p#company_name
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a.supplier_redirection
      attribute_name: href
    ships_from_retriever_module:
      name: get_key_value_list
      key_css_selector: div.info .table-ul li:nth-of-type(2) span:first-child
      value_css_selector: div.info .table-ul li:nth-of-type(2) span.dispatch
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_2: button[class*="arrow--right"]
      picture_css_selector: .products-info div.react-multi-carousel-list li[class*="item--active"]
        img
      regex: (.+)
      attribute_name: src
      loading_delay: 1
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: span.company_name
    description_retriever_module:
      name: get_attribute_value
      css_selector: p.description
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img#company_logo
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: div.user-info div.tile h6
      value_css_selector: div.user-info div.tile p
