framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
    override_user_agent: true
    cloudflare_bypass: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    loading_delay: 5
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.gumtree.com/search?search_category=all&q={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: a[data-q="search-result-anchor"]
      regex: gumtree.com\/p\/(.*)$
    listing_container_css_selector: a[data-q="search-result-anchor"]
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: div.css-1de61eh
    price_retriever_module:
      name: get_attribute_value
      css_selector: div[data-testid="price"]
      attribute_name: textContent
      replace_old: \£
      replace_new: GBP
    location_retriever_module:
      name: get_attribute_value
      css_selector: div.css-30gart
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .listing-tile-thumbnail-image>img
      attribute_name: src
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: .pagination a.pagination-link--next
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .live-ads-profile>.primary-listings>li a.listing-link
      regex: gumtree.com\/p\/(.*)$
      listing_container_css_selector: .live-ads-profile>.primary-listings>li a.listing-link
      title_retriever_module:
        name: get_attribute_value
        attribute_name: textContent
        css_selector: .listing-title
      price_retriever_module:
        name: get_attribute_value
        css_selector: .listing-price
        attribute_name: textContent
        replace_old: \£
        replace_new: GBP
      location_retriever_module:
        name: get_attribute_value
        css_selector: .listing-location
        attribute_name: textContent
      pictures_retriever_module:
        name: get_pictures_from_attribute
        css_selector: .listing-thumbnail>img
        attribute_name: src
      load_more_results_module:
        name: go_to_next_page_module
        css_selector: li.pagination-next>a
  post_information_retriever_module:
    name: post_information_retriever_with_creation_of_a_new_driver_for_each_post_module
    post_url_template: https://www.gumtree.com/p/{}
    take_screenshot: true
    loading_delay: 5
    title_retriever_module:
      name: get_attribute_value
      css_selector: h1.e1pt9h6u6
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: '[itemprop="description"]'
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[data-q="ad-price"]'
      replace_old: \xc2\xa3
      replace_new: GBP
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: h2.seller-rating-block-name
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: '[href*="/profile/"]'
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: .image-carousel li:first-child img
      clickable_css_selector_2: .dialog-content [data-q="carouselNext"] span
      loading_delay: 1
      picture_css_selector: .dialog-content li[class*="carousel-item active"] img
      attribute_name: src
      regex: (.+)
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: '#onetrust-accept-btn-handler'
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: h2.profile-title
      attribute_name: textContent
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      key_css_selectors:
        - .seller-stats-item:nth-of-type(1) p
        - .seller-stats-item:nth-of-type(2) p
        - .seller-stats-item:nth-of-type(3) p
        - .live-ads-profile>h2
      value_css_selectors:
        - .seller-stats-item:nth-of-type(1) p strong
        - .seller-stats-item:nth-of-type(2) p strong
        - .seller-stats-item:nth-of-type(3) p strong
        - .live-ads-profile>h2
      key_regex:
        - Posting for
        - Replies in about
        - Response rate
        - live ads
      value_regex:
        - (.+)
        - (.+)
        - (.+)
        - s.(\d+).live
      key_attributes:
        - textContent
        - textContent
        - textContent
        - textContent
      value_attributes:
        - textContent
        - textContent
        - textContent
        - textContent
