framework:
  name: selenium_framework
  proxies:
    - name: proxyrack
    - name: horocn
    - name: proxys.io/mobile/dedicated/th
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
    start_maximized: true
    load_images: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    loading_delay: 8
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: li[class*="gl-item"] div[class*="p-name"]>a
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
    listing_container_css_selector: li[class*="gl-item"]
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: div[class*="p-name"]>a
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="p-shop"] a:first-child
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      attribute_name: href
      css_selector: div[class*="p-shop"] a:first-child
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div[class*="p-img"] img
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: '[class*="pn-next"]'
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    loading_delay: 5
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: .sku-name
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: '[data-tab="item"] .p-parameter'
      attribute_name: textContent
    price_retriever_module:
      name: get_multiple_text_content_and_concatenate
      css_selectors:
        - span[class="p-price"] span
      replace_new: CNY
      has_multiple_items_in_same_selector: true
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .shopName, .item .name a
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .shopName, .item .name a
      attribute_name: href
    ships_from_retriever_module:
      name: get_key_value_list
      key_css_selector: '#summary-service'
      key_regex: \xe4\xbb\x8e(\D+)\xe5\x8f\x91\xe8\xb4\xa7
      value_css_selector: '#summary-service'
      value_regex: \xe4\xbb\x8e(\D+)\xe5\x8f\x91\xe8\xb4\xa7
    pictures_retriever_module:
      name: get_pictures_from_attribute_with_replace
      css_selector: '#preview img'
      replace_old: jfs/
      replace_new: https://img14.360buyimg.com/n0/jfs/
      attribute_name: data-url
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    loading_delay: 5
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: head>title
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div[module-name="new_shop_signs"] img
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: tbody#jRatingTotal_table>tr>td:first-child , div.worldwide-menu-link
        ul.panel-bottom>li>span>span.label
      value_css_selector: tbody#jRatingTotal_table>tr>td:nth-child(2) , div.worldwide-menu-link
        ul.panel-bottom>li>span span.value
