include: jiji.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://jiji.ng/search?query={}&sort=new
    post_identifiers_retriever_module:
      regex: jiji.ng\/(.+)
    poster_post_identifiers_retriever_module:
      regex: jiji.ng\/(.+)
    price_retriever_module:
      replace_old: \₦
      replace_new: NGN
  post_information_retriever_module:
    post_url_template: https://jiji.ng/{}
    price_retriever_module:
      replace_old: \₦
      replace_new: NGN