include: jiji.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://jiji.co.ke/search?query={}&sort=new
    post_identifiers_retriever_module:
      regex: jiji.co.ke\/(.+)
    poster_post_identifiers_retriever_module:
      regex: jiji.co.ke\/(.+)
    price_retriever_module:
      replace_old: KSh
      replace_new: KES
  post_information_retriever_module:
    post_url_template: https://jiji.co.ke/{}
    price_retriever_module:
      replace_old: KSh
      replace_new: KES