include: jiji.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://jiji.co.tz/search?query={}&sort=new
    post_identifiers_retriever_module:
      regex: jiji.co.tz\/(.+)
    poster_post_identifiers_retriever_module:
      regex: jiji.co.tz\/(.+)
    price_retriever_module:
      replace_old: TSh
      replace_new: TZS
  post_information_retriever_module:
    post_url_template: https://jiji.co.tz/{}
    price_retriever_module:
      replace_old: TSh
      replace_new: TZS