framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 6
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: a.b-list-advert-base
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .b-advert-listing-tile-item>a
    listing_container_css_selector: a.b-list-advert-base
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: div.qa-advert-title
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: a.b-list-advert-base div.qa-advert-price
    location_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: span.b-list-advert__region__text
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div.b-list-advert-base__img>picture>source
      attribute_name: srcset
    load_more_results_module:
      name: load_more_by_scrolling_module
      scroll_pause_time: 2
      scroll_range: 10
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    loading_delay: 5
    title_retriever_module:
      name: get_attribute_value
      css_selector: h1.b-advert-title
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: .qa-description-text
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: .qa-advert-price-view-title
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .b-seller-block__name
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a.b-seller-block__avatar__wrapper
      attribute_name: href
    ships_from_retriever_module:
      name: get_key_value_list
      key_css_selector: .b-advert-info-statistics__inner .b-advert-info-statistics:last-child
      value_css_selector: .b-advert-info-statistics__inner .b-advert-info-statistics:last-child
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: .VueCarousel-slide:first-child picture img
      clickable_css_selector_2: .qa-carousel-expand .b-carousel-arrow--right svg
      picture_css_selector: img.b-carousel-expand-image
      attribute_name: src
      loading_delay: 3
      regex: (.+)
      escape_popup_on_end: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: .b-cookie-hint__button
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    loading_delay: 1
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .b-seller-info-block__name>span
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: .b-seller-tile-info-block__text>span
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .b-seller-info-block__photo-wrapper img
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      key_css_selectors:
        - .b-seller-address-block__head-text
        - .b-seller-info-tiles>div:last-child
      value_css_selectors:
        - .b-seller-address-block__head-text
        - .b-seller-info-tiles>div:last-child
      key_regex:
        - address
        - on Jiji
      value_regex:
        - (.+)
        - (.+) on Jiji
      key_attributes:
        - class
        - textContent
      value_attributes:
        - textContent
        - textContent
