include: jiji.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://jiji.ug/search?query={}&sort=new
    post_identifiers_retriever_module:
      regex: (?<=https:\/\/jiji.ug\/)(.*)
    poster_post_identifiers_retriever_module:
      regex: (?<=https:\/\/jiji.ug\/)(.*)
    price_retriever_module:
      replace_old: USh
      replace_new: UGX
  post_information_retriever_module:
    post_url_template: https://www.jiji.ug/{}
    price_retriever_module:
      replace_old: USh
      replace_new: UGX