framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    headless: false
    start_maximized: true
    xvfb: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 12
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://jp.mercari.com/search?keyword=power
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '[data-testid="listing-item-grid"] li>a'
      regex: jp.mercari.com\/item\/(.+)
      load_more_results_module:
        name: load_more_by_click
        css_selector: '#main>.no-border>div .merButton>button'
        loading_delay: 5
        undetected_click: true
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '[data-testid="search-item-grid"] li>div>a'
      regex: jp.mercari.com\/item\/(.+)
    listing_container_css_selector: '[data-testid="search-item-grid"] li>div>a , [data-testid="listing-item-grid"]
      li>a'
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: span[data-testid="thumbnail-item-name"]
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: span.merPrice
      replace_old: \¥
      replace_new: JPY
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .merItemThumbnail picture>img
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: '[data-testid="pagination-next-button"]>button'
      undetected_click: true
      loading_delay: 12
    action_before_search_pages_browsing_module:
      - name: refresh_page
        stop_css_selector: '[data-testid="search-item-grid"] li>div>a , [data-testid="listing-item-grid"]
          li>a'
        after_pause_time: 10
  post_information_retriever_module:
    name: post_information_retriever_with_creation_of_a_new_driver_for_each_post_module
    post_url_template: https://jp.mercari.com/item/{}
    take_screenshot: true
    loading_delay: 4
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[data-testid="item-detail-container"] .merHeading h1'
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: '[data-testid="description"]'
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: div[data-testid="price"]
      replace_old: \¥
      replace_new: JPY
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: '[data-testid="seller-link"]>div>div>p.merText'
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a[data-location="item_details:seller_info"]
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_2: '[data-testid="carousel"] .slick-arrow.slick-next'
      picture_css_selector: '[data-testid="carousel"] .slick-current picture>img'
      attribute_name: src
      loading_delay: 1
      regex: (.+)
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: https://jp.mercari.com/user/profile/{}
    take_screenshot: true
    loading_delay: 2
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: '[data-testid="profile-info"] .merHeading h1'
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: '[data-partner-id="profile-show-more"] .merText'
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .merAvatar picture>img
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: div.user-info-supplement>a>div>span:last-of-type
      value_css_selector: div.user-info-supplement>a>div>span:first-of-type
