include: jumia.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.jumia.dz/catalog/?q={}
    poster_post_identifiers_retriever_module:
      regex: jumia.dz\/(.+).html
    post_identifiers_retriever_module:
      regex: jumia.dz\/(.+).html
    price_retriever_module:
      replace_old: DA
      replace_new: DZD
  post_information_retriever_module:
    post_url_template: https://www.jumia.dz/{}.html