framework:
  name: selenium_framework
  proxies:
    - name: proxys.io/mobile/shared/us 
    - name: 123proxy
    - name: iproyal/us
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
    cookies:
      url: https://kaspi.kz/shop/
      properties:
        kaspi.storefront.cookie.city: '710000000'
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://kaspi.kz/shop/search/?text={}&q=&sort=relevance&filteredByCategory=false&sc=
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .search-result div[data-list-id="SP"] > a
      regex: kaspi.kz\/shop\/p\/(.*)
    listing_container_css_selector: .search-result div[data-list-id="SP"]
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: .pagination li:last-of-type
    title_retriever_module:
      name: get_attribute_value
      css_selector: a.item-card__name-link
    price_retriever_module:
      name: get_attribute_value
      css_selector: span[class*="prices-price"]
      replace_old: \₸
      replace_new: KZT
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img.item-card__image
      attribute_name: src
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://kaspi.kz/shop/p/{}
    title_retriever_module:
      name: get_attribute_value
      css_selector: h1.item__heading
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div.item__description-text
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: div.item__price-once
      attribute_name: textContent
      replace_old: \₸
      replace_new: KZT
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div.sellers-table tr:first-child td[class*="table__cell"]>a
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: div.sellers-table tr:first-child td[class*="table__cell"]>a
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: 'div.bx-viewport li[style*="display: block;"]'
      clickable_css_selector_2: .lightbox button[class*="arrow--right"]
      picture_css_selector: .lightbox img
      attribute_name: src
      regex: (.+)
      close_button_css_selector: .lightbox button[class*="close"]
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: h3.merchant-profile__title
      regex: (.+)\s
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      key_css_selectors:
        - p[class*="register-date"]
        - li[data-tab="reviews"]
        - span[class*="contact-text"]
      value_css_selectors:
        - p[class*="register-date"]
        - li[data-tab="reviews"]
        - span[class*="contact-text"]
      key_regex:
        - В Kaspi Магазине с
        - Отзывы
        - contact
      value_regex:
        - В Kaspi Магазине с (.+)
        - \d+
        - (.+)
      key_attributes:
        - textContent
        - textContent
        - class
