framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://kloomba.com/market/?q={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .content__main a.catalog_card__link
      regex: kloomba.com\/o\/(.*)$
    listing_container_css_selector: .content__main a.catalog_card__link
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: div.catalog_card__title
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: div.catalog_card__price
      replace_old: \xe2\x82\xb4
      replace_new: UAH
      trim_text: true
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div.catalog_card__img>img
      attribute_name: data-src
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: a.catalog_card__link
      regex: kloomba.com\/o\/(.*)$
      load_more_results_module:
        name: go_to_next_page_module
        css_selector: '#kl-market-pager-secondary .active+li a'
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: .pagination__item-next a
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://kloomba.com/o/{}
    take_screenshot: true
    title_retriever_module:
      name: get_json_value
      css_selector: script[type="application/ld+json"]
      output_string: '{jsons[0]["name"]}'
    description_retriever_module:
      name: get_json_value
      css_selector: script[type="application/ld+json"]
      output_string: '{jsons[0]["description"]}'
    price_retriever_module:
      name: get_json_value
      css_selector: script[type="application/ld+json"]
      output_string: '{jsons[0]["offers"]["price"]} {jsons[0]["offers"]["priceCurrency"]}'
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .product__seller__profile__name
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .product__seller__profile__name
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute_with_replace
      css_selector: .product__image_thumb__img
      attribute_name: data-src
      replace_old: /s/
      replace_new: /b/
      loading_delay: 1
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .shop__head__seller__info__name
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      clickable_css_selector: .shop__main__nav a[href*="/shop-info"]
      css_selector: .shop__about__content
      loading_delay: 1
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute_with_replace
      css_selector: .avatar__img
      attribute_name: data-src
      replace_old: //
      replace_new: https://
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      loading_delay: 1
      clickable_css_selectors:
        - .shop__main__nav a[href*="/opinions/"]
      key_css_selectors:
        - .shop__head__panel__info__block:nth-of-type(1) :last-child
        - .shop__head__panel__info__block:nth-of-type(2) :last-child
        - .shop__head__panel__info__block:nth-of-type(3) :last-child
        - .shop__reviews__head__type__positive span:first-of-type
        - .shop__reviews__head__type a[href*="negative"]>span:first-of-type
        - .shop__stats__list>div:nth-of-type(1) :first-child
        - .shop__stats__list>div:nth-of-type(2) :first-child
        - .shop__stats__list>div:nth-of-type(3) :first-child
        - .shop__stats__list>div:nth-of-type(4) :first-child
      value_css_selectors:
        - .shop__head__panel__info__block:nth-of-type(1) :first-child
        - .shop__head__panel__info__block:nth-of-type(2) :first-child
        - .shop__head__panel__info__block:nth-of-type(3) :first-child
        - .shop__reviews__head__type__positive span:last-of-type
        - .shop__reviews__head__type a[href*="negative"]>span:last-of-type
        - .shop__stats__list>div:nth-of-type(1) :last-child
        - .shop__stats__list>div:nth-of-type(2) :last-child
        - .shop__stats__list>div:nth-of-type(3) :last-child
        - .shop__stats__list>div:nth-of-type(4) :last-child
      key_regex:
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
      value_regex:
        - (.+)
        - (.+)
        - (.+)
        - (\d+)
        - (\d+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
      key_attributes:
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
      value_attributes:
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
