include: lazada.yaml
framework:
  proxies:
    - name: proxys.io/mobile/dedicated/th
    - name: proxyrack
      country: ID
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.lazada.co.id/catalog/?q={}
    post_identifiers_retriever_module:
      regex: lazada\.co\.id/products/(.+).html
    poster_post_identifiers_retriever_module:
      regex: lazada\.co\.id/products/(.+).html
    price_retriever_module:
      replace_old: Rp
      replace_new: IDR
  post_information_retriever_module:
    post_url_template: https://www.lazada.co.id/products/{}.html
    price_retriever_module:
      replace_old: Rp
      replace_new: IDR
