include: lazada.yaml
framework:
  proxies:
    - name: proxys.io/mobile/dedicated/th
    - name: proxyrack
      country: VN
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.lazada.vn/catalog/?q={}
    post_identifiers_retriever_module:
      regex: lazada\.vn/products/(.+).html
    poster_post_identifiers_retriever_module:
      regex: lazada\.vn/products/(.+).html
    price_retriever_module:
      replace_old: \xe2\x82\xab
      replace_new: VND
  post_information_retriever_module:
    post_url_template: https://www.lazada.vn/products/{}.html
    price_retriever_module:
      replace_old: \xe2\x82\xab
      replace_new: VND
