framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 3
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.lfmall.co.kr/app/search/result/{}?order=recent
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '[class*="SearchProductList_prdList__"]>div.SearchProductItem
        img[class*="ProductThumbImage_baseImg"]'
      regex: .+\/(.+)\_
      attribute_name: src
    listing_container_css_selector: '[class*="SearchProductList_prdList__"]>div.SearchProductItem'
    title_retriever_module:
      name: get_attribute_value
      css_selector: a.productThumbName
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="ProductThumbPrice_lastPrice"]'
      replace_old: (.+)
      replace_new: \g<1> KRW
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img[class*="ProductThumbImage_baseImg"]
      attribute_name: src
    load_more_results_module:
      name: load_more_by_scrolling_one_scroll_at_a_time
      scroll_range: 6
      scroll_pause_time: 0.2
      loading_delay: 3
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.lfmall.co.kr/app/product/{}
    take_screenshot: true
    loading_delay: 3
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="ProductBasic_productTitle"]'
    description_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="ProductDetail_detailInner"]'
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="ProductBasic_finalPrice"]'
      replace_old: \xec\x9b\x90
      replace_new: KRW
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[class*="ProductImage_productVisualWrap"] div.swiper-slide>figure>img'
      attribute_name: src
