include: falabella.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://linio.falabella.com/linio-cl/search?Ntt={}
    poster_post_identifiers_retriever_module:
      regex: falabella.com/(.+)$
    post_identifiers_retriever_module:
      regex: falabella.com/(.+)$
    price_retriever_module:
      replace_old: \$
      replace_new: USD
  post_information_retriever_module:
    post_url_template: https://www.falabella.com/{}
    price_retriever_module:
      replace_old: \$
      replace_new: USD