include: mall.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.mall.hu/keres?s={}
    poster_post_identifiers_retriever_module:
      regex: mall.hu\/(.+)$
    post_identifiers_retriever_module:
      regex: mall.hu\/(.+)$
    price_retriever_module:
      replace_old: Ft
      replace_new: HUF
  post_information_retriever_module:
    post_url_template: https://www.mall.hu/{}
    price_retriever_module:
      replace_old: Ft
      replace_new: HUF