include: mall.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.mall.hr/trazenje?s={}
    poster_post_identifiers_retriever_module:
      regex: mall.hr\/(.+)$
    post_identifiers_retriever_module:
      regex: mall.hr\/(.+)$
    price_retriever_module:
      replace_old: \€
      replace_new: EUR
      exclude_children: true
  post_information_retriever_module:
    post_url_template: https://www.mall.hr/{}
    price_retriever_module:
      replace_old: \€
      replace_new: EUR