framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 5
    take_screenshots: true
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.marktplaats.nl/q/{}
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: li[class*="Listing--list-item"] a[class*="Listing-coverLink"]
      regex: marktplaats.nl\/v\/(.+)
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: li[class*="Listing--list-item"] a[class*="Listing-coverLink"]
      regex: marktplaats.nl\/v\/(.+)
    listing_container_css_selector: div[class*="main"]>ul>li[class*="Listing--list-item"]
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: a h3[class*="Listing-title"]
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: a span[class*="text-price-label"]
      replace_old: \€
      replace_new: EUR
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div span[class*="Listing-seller-name"]>a>span
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: a>figure img
      attribute_name: src
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: nav[class*="PaginationControls-pagination"]>a
    action_before_search_pages_browsing_module:
      - name: switch_to_iframe
        css_selector: iframe[id*="sp_message_iframe"]
      - name: click_action_module
        css_selector: button[aria-label="Accepteren"]
      - name: switch_out_iframe
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.marktplaats.nl/v/{}
    loading_delay: 2
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: .Listing-title
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: .Description-root
      attribute_name: textContent
    price_retriever_module:
      name: get_json_value
      css_selector: script[type="application/ld+json"]
      output_string: '{jsons[1]["offers"]["price"]} {jsons[1]["offers"]["priceCurrency"]}'
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .SellerInfo-name a
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .SellerInfo-name a
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: .Carousel-container,img[class="HeroImage-image"]
      clickable_css_selector_2: .Carousel-navigationContainer:last-child
      picture_css_selector: img[class*="dialogImage"]
      attribute_name: src
      regex: (.+)
      escape_popup_on_end: true
    action_before_retrieving_post_information_module:
      - name: switch_to_iframe
        css_selector: iframe[id*="sp_message_iframe"]
      - name: click_action_module
        css_selector: button[aria-label="Accepteren"]
      - name: switch_out_iframe
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    loading_delay: 3
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="TopSection-TitleWrap-Name"]
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      clickable_css_selector: '[role="tablist"]>li:first-child>span'
      loading_delay: 3
      css_selector: div.ProfileBody-content
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[class*="TopSection-image"]>img'
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      key_css_selectors:
        - div.Info-infoWrap div.Info-text , [class*="SellerHeaderInfo"]>div[class*="hz-SellerHeaderInfo-item"]
        - a[class*="TextLink"][href*="tel:"]
      value_css_selectors:
        - div.Info-infoWrap div.Info-text , [class*="SellerHeaderInfo"]>div[class*="hz-SellerHeaderInfo-item"]
        - a[class*="TextLink"][href*="tel:"]
      key_regex:
        - ' actief op Marktplaats'
        - tel
      value_regex:
        - (.+) actief
        - (.+)
      key_attributes:
        - textContent
        - href
      value_attributes:
        - textContent
        - textContent
    action_before_retrieving_post_information_module:
      - name: switch_to_iframe
        css_selector: iframe[id*="sp_message_iframe"]
      - name: click_action_module
        css_selector: button[aria-label="Accepteren"]
      - name: switch_out_iframe
