framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 2
    take_screenshots: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://mediamarkt.pt/pages/search-results-page?q={}
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: li.snize-product>a
      regex: mediamarkt.pt\/products\/(.+)
    listing_container_css_selector: li.snize-product
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .snize-title
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .snize-price>div:not(.old)>div:first-of-type
      regex: '[\d\.]+'
      replace_old: (.+)
      replace_new: \g<1> EUR
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .snize-thumbnail>img
      attribute_name: src
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: li>a.snize-pagination-next
      loading_delay: 4
    action_before_search_pages_browsing_module:
      - name: refresh_page
        after_pause_time: 3
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://mediamarkt.pt/products/{}
    loading_delay: 3
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: .main>.title
    description_retriever_module:
      name: get_multiple_text_content_and_concatenate
      css_selectors:
        - '[data-tab-id="description"].page-product-box p'
      has_multiple_items_in_same_selector: true
    price_retriever_module:
      name: get_attribute_value
      css_selector: '#AddToCartForm [itempsrop="price"]'
      attribute_name: content
      replace_old: (.+)
      replace_new: \g<1> EUR
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '#gallery-block a#image-zoom-src img'
      attribute_name: src
