include: mediamarkt.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.mediamarkt.nl/nl/search.html?query={}
    post_identifiers_retriever_module:
      regex: mediamarkt.nl\/nl\/product\/(.+).html
  post_information_retriever_module:
    post_url_template: https://www.mediamarkt.nl/nl/product/{}.html