include: mercadolibre.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://listado.mercadolibre.com.do/{}
    price_retriever_module:
      replace_old: \$
      replace_new: DOP