include: mercadolibre.yaml
framework:
  name: selenium_framework
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://listado.mercadolibre.com.uy/{}
    price_retriever_module:
      replace_old: \$
      replace_new: UYU