framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 3
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.n11.com/arama?q={}
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .list-ul>li div.pro>a
      regex: n11.com\/urun\/(.+)
      load_more_results_module:
        name: go_to_next_page_module
        css_selector: .pagination>a.next
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .list-ul>li div.pro>a
      regex: n11.com\/urun\/(.+)
    listing_container_css_selector: .list-ul>li>div
    title_retriever_module:
      name: get_attribute_value
      attribute_name: title
      css_selector: .pro>a
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: span.newPrice>ins
      replace_old: TL
      replace_new: ' TRY'
      trim_text: true
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .pro>a.plink img
      attribute_name: src
    load_more_results_module:
      name: load_more_by_scrolling_module
      fixed_scroll_to: 250
      scroll_range: 12
      scroll_pause_time: 2.5
      loading_delay: 3
    action_before_search_pages_browsing_module:
      - name: click_shadow_root_element
        css_selector: .efilli-layout-n11
        clickable_css_selector: div.banner__accept-button
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.n11.com/urun/{}
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: .productContainer div.proNameHolder
    description_retriever_module:
      name: get_attribute_value
      css_selector: .unf-info-desc
    price_retriever_module:
      name: get_attribute_value
      css_selector: .productContainer .priceContainer>.newPrice>ins
      replace_old: TL
      replace_new: TRY
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: a.unf-p-seller-name
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a.unf-p-seller-name
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: .unf-p-img-box div.imgObj>a
      clickable_css_selector_2: .unf-p-gallery-modal button.slick-next-main
      picture_css_selector: '.unf-p-gallery-modal #galleryMain div.slick-track>div.slick-slide.slick-active
        img:first-child'
      attribute_name: src
      regex: (.+)
      escape_popup_on_end: true
      loading_delay: 1
    action_before_retrieving_post_information_module:
      - name: click_shadow_root_element
        css_selector: .efilli-layout-n11
        clickable_css_selector: div.banner__accept-button
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .sellerDetail .sellerName
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .sellerAvatar>img
      attribute_name: src
    action_before_retrieving_post_information_module:
      - name: click_shadow_root_element
        css_selector: .efilli-layout-n11
        clickable_css_selector: div.banner__accept-button
