framework:
  name: selenium_framework
  proxies:
    - name: proxyrack
    - name: iproyal/us
    - name: iproyal/lithuania
    - name: 123proxy
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
    load_images: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    loading_delay: 4
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://search.shopping.naver.com/search/all?pagingIndex=1&pagingSize=80&productSet=window&query={}&sort=date&viewType=list
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      post_url_cleaning_module:
        skip_query_string_cleaning: true
      css_selector: '[class*="list_basis"]>div>div>div>div [class*="product_title"]>a'
    listing_container_css_selector: '[class*="list_basis"]>div>div>div>div'
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: '[class*="product_title"]>a'
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: '[class*="product_price"] span[class*="price_num"]'
      replace_old: \원
      replace_new: KRW
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="product_mall_title"]>a'
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: '[class*="product_mall_title"]>a'
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[class*="product_img_area"]>div>a>img'
      attribute_name: src
    load_more_results_module:
      name: load_more_by_scrolling_module
      css_selector: a[class*="pagination_next"]
      scroll_pause_time: 1
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '#content ul>li>div a.linkAnchor'
      listing_container_css_selector: '#content ._2fVvK2YMa1>ul>li>div>div'
      title_retriever_module:
        name: get_attribute_value
        attribute_name: textContent
        css_selector: p.e1bUyeKcqU
      price_retriever_module:
        name: get_attribute_value
        attribute_name: textContent
        css_selector: div._2bWpvzfZeH
        replace_old: \원
        replace_new: KRW
      pictures_retriever_module:
        name: get_pictures_from_attribute
        css_selector: div>div>img
        attribute_name: data-src
      load_more_results_module:
        name: load_more_by_scrolling_module
        scroll_pause_time: 8
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: '{}'
    loading_delay: 3
    title_retriever_module:
      name: get_attribute_url
      css_selector: meta[property="og:title"]
      attribute_name: content
    description_retriever_module:
      name: get_attribute_value
      css_selector: '#INTRODUCE'
      trim_text: true
    price_retriever_module:
      name: get_json_value
      css_selector: script[type="application/ld+json"]
      output_string: '{jsons[0]["offers"]["price"]} {jsons[0]["offers"]["priceCurrency"]}'
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: meta[property="og:description"]
      attribute_name: content
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: button.naver-splugin+a.linkAnchor
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_2: div#content button[class*="itm.more"]:last-child
      hover_before_click_css_selector: div#content>div>div>div div img._2RYeHZAP_4
      picture_css_selector: div#content>div>div>div div img._2RYeHZAP_4
      attribute_name: src
      regex: (.+)
      loading_delay: 2
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    loading_delay: 5
    take_screenshot: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: '#storeHomeMenu a[href*="/about"]'
        after_pause_time: 2
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: '#content div>h3'
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div#info>div>div>p
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div#info ul li img
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      clickable_css_selector: '#info a[role="button"]'
      key_css_selector: '#info a[role="button"]+div dt'
      value_css_selector: '#info a[role="button"]+div dd'
