framework:
  name: selenium_framework
  proxies:
    - name: proxyrack
    - name: iproyal/us
    - name: iproyal/lithuania
    - name: 123proxy
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
    start_maximized: true
    cloudflare_bypass: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.olx.co.za/items/q-{}?sorting=desc-creation
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: li.EIR5N > a
      regex: (?<=\/item\/)(.*)
    load_more_results_module:
      name: load_more_by_click
      css_selector: '[data-aut-id="btnLoadMore"]'
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: button#onetrust-accept-btn-handler
  post_information_retriever_module:
    name: post_information_retriever_with_creation_of_a_new_driver_for_each_post_module
    post_url_template: https://www.olx.co.za/item/{}
    take_screenshot: true
    driver_initialization_module:
      name: classic_selenium_initialization_module
      override_user_agent: true
      load_images: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: ._3rJ6e[data-aut-id="itemTitle"]
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: '[data-aut-id="itemDescriptionContent"]'
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: ._2xKfz[data-aut-id="itemPrice"]
      replace_old: R
      replace_new: ZAR
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: ._3oOe9
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a[href*="/profile/"]
      attribute_name: href
    ships_from_retriever_module:
      name: get_key_value_list
      key_css_selector: div[data-aut-id="itemLocation"]
      value_css_selector: div[data-aut-id="itemLocation"]
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: img[data-aut-id="defaultImg"]
      clickable_css_selector_2: span[class*="_3Dhfh"]
      picture_css_selector: ._2EnR3 img
      attribute_name: src
      regex: (.+)\;.*
  archiving_options:
    click_on_elements:
      - button#onetrust-accept-btn-handler
    height: 2000
    width: 1924
