include: qoo10.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.qoo10.my/s/?keyword={}
    post_identifiers_retriever_module:
      regex: qoo10.my\/item\/(.+)$
    price_retriever_module:
      replace_old: RM
      replace_new: MYR
    poster_post_identifiers_retriever_module:
      action_before_poster_post_identifiers_module:
      - name: click_action_module
        css_selector: a#btn_allitem
        after_pause_time: 3
      - name: click_action_module
        css_selector:
          - 'button#CommonShipLangCurrencyBtn'
          - 'button#CommonShipLangCurrencyBtn'
          - 'button#ShipToSelector'
          - '#div_layer_ship_to li[data-nation="MY"]'
          - '#ShipToLangCurrencySelector>button.btn'
        after_pause_time: 1
      price_retriever_module:
        replace_old: RM
        replace_new: MYR