framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    loading_delay: 5
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.rakuten.com.tw/search/{}/
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .results-grid .product-grid a[href*="/product/"]
      regex: (.+rakuten.com.tw.+)
    listing_container_css_selector: .results-grid .product-grid
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: h3.product-title
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: div.product-price
      replace_old: \$
      replace_new: TWD
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: a.merchant-icon>span
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a.merchant-icon
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div.product-image__overlay img
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: .paginate-bar button:last-child
      loading_delay: 8
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: button.fc-cta-consent
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: '{}'
    take_screenshot: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: button.fc-cta-consent
    title_retriever_module:
      name: get_attribute_value
      css_selector: '#item-purchase-section h1'
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: '#item-detail, .desc-tab-content, #react-tabs-1'
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: span.qa-product-actual-price, strong[class*="qa-product-actualPrice"]
      replace_old: \$
      replace_new: TWD
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: a.v7gU2c0tJRHwNjPF9ZwQ
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a.v7gU2c0tJRHwNjPF9ZwQ
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: 'img.magnifier-image, div[class*="product-main-image"] + div div.swiper-slide-active img'
      clickable_css_selector_2: '.rui-modal.is-active div.swiper-container+button'
      picture_css_selector: '.rui-modal.is-active div.swiper-container .swiper-slide-active>img , .rui-modal.is-active div.sZVEva4mbhH9Q9QVdwxD>img'
      attribute_name: src
      skip_video: true
      regex: (.+)
      close_button_css_selector: '.rui-modal.is-active div.gw0RBMTOhJCmVvo_Nyzr'
      loading_delay: 3
    videos_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: 'img.magnifier-image, div[class*="product-main-image"] + div div.swiper-slide-active img'
      clickable_css_selector_2: '.rui-modal.is-active div.swiper-container+button'
      picture_css_selector: .rui-modal.is-active iframe
      attribute_name: src
      regex: (.+)
      escape_popup_on_end: true
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    loading_delay: 5
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: 'div #auto_shop_info_name'
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img.b-shop-image
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: div#ShopOverview th
      value_css_selector: div#ShopOverview td
    description_retriever_module:
      name: get_attribute_value
      css_selector: div.b-mod-media
      attribute_name: textContent
    action_before_retrieving_post_information_module:
      - name: click_action_module
        before_pause_time: 2
        css_selector: a#auto_shop_information
