framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: .partner-menu li a[href*="/products"]:not([class="active"])
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.reebonz.co.kr/product_search?&search_section=keyword&keyword={}&order_by=latest
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .products-list .product a
      regex: reebonz.co.kr/products/(\d+)/
      listing_container_css_selector: .products-list .product
      title_retriever_module:
        name: get_attribute_value
        css_selector: '[class*="product-name"]'
      price_retriever_module:
        name: get_attribute_value
        css_selector: '[class="price"]'
        replace_old: (.+)
        replace_new: \1KRW
      pictures_retriever_module:
        name: get_pictures_from_attribute
        css_selector: '[class="img-box"] img'
        attribute_name: src
      load_more_results_module:
        name: go_to_next_page_module
        css_selector: ul.pagination li.active + li a
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: li.product-item a
      regex: reebonz.co.kr/products/(\d+)/
    listing_container_css_selector: li.product-item
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[class="product-name"]'
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[class="selling-price"]'
      regex: ([^\%]+)$
      replace_old: \xec\x9b\x90
      replace_new: KRW
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[class="image-wrap"] img'
      attribute_name: src
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: ul.pagination li.active + li a
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.reebonz.co.kr/products/{}
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[class="product-name"]'
    description_retriever_module:
      name: get_attribute_value
      css_selector: '[class="product-description"]'
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="price-wrap"] [class="value"]'
      regex: ([^\%]+)$
      replace_old: \xec\x9b\x90
      replace_new: KRW
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .partner-name > p
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a.partner-home-url
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: .swiper-slide-active img.swiper-lazy-loaded
      clickable_css_selector_2: .swiper-next
      picture_css_selector: .swiper-slide-active img.swiper-lazy-loaded
      regex: (.+)
      attribute_name: src
      close_button_css_selector: button.btn-close
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .partner-header h1
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: ul.statistics .card span.name
      value_css_selector: ul.statistics .card span.value
