framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 2
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.rueducommerce.fr/r/{}.html
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: a.item__image
      regex: rueducommerce.fr\/(.*)$
    listing_container_css_selector: article.item
    title_retriever_module:
      name: get_attribute_value
      css_selector: .item__title
      attribute_name: textContent
      trim_text: true
    price_retriever_module:
      name: get_multiple_text_content_and_concatenate
      css_selectors:
        - .item__price--new-box span
      attribute_name: textContent
      has_multiple_items_in_same_selector: true
      replace_old: \n\€
      replace_new: ' EUR'
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img.item__image
      attribute_name: src
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: a.item__image
      regex: rueducommerce.fr\/(.*)$
      action_before_poster_post_identifiers_module:
        - name: click_action_module
          css_selector: '#rgpd-btn-index-continue'
          loading_delay: 1
        - name: click_action_module
          css_selector: .page__market-infos a
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: '#rgpd-btn-index-continue'
        loading_delay: 1
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: .ScrollOfInfinity a
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.rueducommerce.fr/{}
    loading_delay: 3
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: meta[itemprop="name"]
      attribute_name: content
    description_retriever_module:
      name: get_attribute_value
      css_selector: div[itemprop="description"]
      attribute_name: textContent
    price_retriever_module:
      name: get_multiple_text_content_and_concatenate
      css_selectors:
        - .dyn_prod_price
        - .dyn_prod_money
      attribute_name: textContent
      replace_old: (\n[^\n]+)
      replace_new: ' EUR'
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="vendeur-nom"]'
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: '[class*="vendeur-nom"]'
      attribute_name: href
      regex: rueducommerce.fr/(.+)
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[id*="thumb-scroll"] img'
      attribute_name: src
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: '#rgpd-btn-index-continue'
        loading_delay: 1
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: https://www.rueducommerce.fr/{}
    loading_delay: 3
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .title h2
      attribute_name: textContent
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      key_css_selectors:
        - .page__market-contact h2.title
        - p.title-legal
        - .page__market-eval>div>div:nth-child(1) p strong
        - .page__market-eval>div>div:nth-child(2) p strong
        - .page__market-eval>div>div:nth-child(3) p strong
        - .page__market-eval>div>div:nth-child(4) p strong
      value_css_selectors:
        - .adress p
        - p.legal
        - .stars-rating svg use
        - .page__market-eval>div>div:nth-child(2) p:last-child
        - .page__market-eval>div>div:nth-child(3) p:last-child
        - .page__market-eval>div>div:nth-child(4) p:last-child
      key_regex:
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
        - (.+)
      value_regex:
        - (.+)
        - (.+)
        - (\d+-\d+)
        - (.+)
        - (.+)
        - (.+)
      key_attributes:
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
        - textContent
      value_attributes:
        - textContent
        - textContent
        - xlink:href
        - textContent
        - textContent
        - textContent
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: '#rgpd-btn-index-continue'
        loading_delay: 1
