include: craigslist.yaml
framework: 
    search_pages_browsing_module:
        search_page_urls_builder_module:
            search_page_url_templates:
                - 'https://buenosaires.craigslist.org/search/sss?query={}'
                - 'https://lapaz.craigslist.org/search/sss?query={}'
                - 'https://belohorizonte.craigslist.org/search/sss?query={}'
                - 'https://brasilia.craigslist.org/search/sss?query={}'
                - 'https://curitiba.craigslist.org/search/sss?query={}'
                - 'https://fortaleza.craigslist.org/search/sss?query={}'
                - 'https://portoalegre.craigslist.org/search/sss?query={}'
                - 'https://recife.craigslist.org/search/sss?query={}'
                - 'https://rio.craigslist.org/search/sss?query={}'
                - 'https://salvador.craigslist.org/search/sss?query={}'
                - 'https://saopaulo.craigslist.org/search/sss?query={}'
                - 'https://caribbean.craigslist.org/search/sss?query={}'
                - 'https://santiago.craigslist.org/search/sss?query={}'
                - 'https://colombia.craigslist.org/search/sss?query={}'
                - 'https://costarica.craigslist.org/search/sss?query={}'
                - 'https://santodomingo.craigslist.org/search/sss?query={}'
                - 'https://quito.craigslist.org/search/sss?query={}'
                - 'https://elsalvador.craigslist.org/search/sss?query={}'
                - 'https://guatemala.craigslist.org/search/sss?query={}'
                - 'https://acapulco.craigslist.org/search/sss?query={}'
                - 'https://bajasur.craigslist.org/search/sss?query={}'
                - 'https://chihuahua.craigslist.org/search/sss?query={}'
                - 'https://juarez.craigslist.org/search/sss?query={}'
                - 'https://guadalajara.craigslist.org/search/sss?query={}'
                - 'https://guanajuato.craigslist.org/search/sss?query={}'
                - 'https://hermosillo.craigslist.org/search/sss?query={}'
                - 'https://mazatlan.craigslist.org/search/sss?query={}'
                - 'https://mexicocity.craigslist.org/search/sss?query={}'
                - 'https://monterrey.craigslist.org/search/sss?query={}'
                - 'https://oaxaca.craigslist.org/search/sss?query={}'
                - 'https://puebla.craigslist.org/search/sss?query={}'
                - 'https://pv.craigslist.org/search/sss?query={}'
                - 'https://tijuana.craigslist.org/search/sss?query={}'
                - 'https://veracruz.craigslist.org/search/sss?query={}'
                - 'https://yucatan.craigslist.org/search/sss?query={}'
                - 'https://managua.craigslist.org/search/sss?query={}'
                - 'https://panama.craigslist.org/search/sss?query={}'
                - 'https://lima.craigslist.org/search/sss?query={}'
                - 'https://puertorico.craigslist.org/search/sss?query={}'
                - 'https://montevideo.craigslist.org/search/sss?query={}'
                - 'https://caracas.craigslist.org/search/sss?query={}'
                - 'https://virgin.craigslist.org/search/sss?query={}'
