framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://shafa.ua/clothes?search_text={}&sort=4
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .b-tile-item-name-product
      regex: shafa.ua\/(.*)$
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: ._3UtwolBEZ3HYTqKHZTAk>a , .b-tile-item-name-product
      regex: shafa.ua\/(.*)$
      load_more_results_module:
        name: click_on_next_page_module
        css_selector: ._24xi0K1MDzXM0WDdPDIh>a._2s8v13oEmXHrVGwHRqP4>button , .b-pagination__list
          li:last-child a
    listing_container_css_selector: li.b-catalog__item
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: a.b-tile-item-name-product
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: div.b-tile-item__price
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img.b-tile-item__image
      attribute_name: src
    load_more_results_module:
      name: go_to_next_page_module
      css_selector: .b-pagination__item_type_next>a
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://shafa.ua/{}
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: .b-product__title
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: '[class="b-product__description-text"]'
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: .b-product-price__current
      replace_old: \xd0\xb3\xd1\x80\xd0\xbd
      replace_new: UAH
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .b-product-seller__info-title
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a.b-product-seller__info-title
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .b-product-gallery__additional-item>a
      attribute_name: href
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    loading_delay: 5
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: h5
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      clickable_css_selector: a[href*="/about"]
      loading_delay: 1
      css_selector: .Sp_qgIt3xCASd_9ZEu5Y
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img[src*="avatars.shafa"]
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      key_css_selectors:
        - .VFmnFO_X3eMUYY0gvPiR
        - div:nth-child(3)>._2LHmeVRodep18gTAAy4B span
        - div:nth-child(4)>._2LHmeVRodep18gTAAy4B:nth-child(2)>span
        - div:nth-child(4)>._2LHmeVRodep18gTAAy4B:nth-child(3)>span
        - div:nth-child(4)>._2LHmeVRodep18gTAAy4B:nth-child(4)>span
      value_css_selectors:
        - .VFmnFO_X3eMUYY0gvPiR
        - div:nth-child(3)>._2LHmeVRodep18gTAAy4B span
        - div:nth-child(4)>._2LHmeVRodep18gTAAy4B:nth-child(2)>span
        - div:nth-child(4)>._2LHmeVRodep18gTAAy4B:nth-child(3)>span
        - div:nth-child(4)>._2LHmeVRodep18gTAAy4B:nth-child(4)>span
      key_regex:
        - \(\d+ (.+)\)
        - (.+)\d
        - \d+(.+)
        - \d+(.+)
        - (.+?)\d+
      value_regex:
        - \d\.\d
        - (\d+.+)
        - (\d+)
        - (\d+)
        - (\d+.+)
