include: shopee.yaml
framework:
  driver_initialization_module:
    undetected_driver: true
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://shopee.ph/search?keyword={}&sortBy=ctime
    poster_post_identifiers_retriever_module:
      regex: shopee.ph\/(.*)$
    post_identifiers_retriever_module:
      regex: shopee.ph\/(.*)$
    price_retriever_module:
      replace_old: \₱
      replace_new: PHP 
  post_information_retriever_module:
    post_url_template: https://shopee.ph/{}
    price_retriever_module:
      replace_old: \₱
      replace_new: PHP