include: shopee.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://shopee.sg/search?keyword={}&sortBy=ctime
    poster_post_identifiers_retriever_module:
      regex: shopee.sg\/(.*)$
    post_identifiers_retriever_module:
      regex: shopee.sg\/(.*)$
    price_retriever_module:
      replace_old: \$
      replace_new: SGD
  post_information_retriever_module:
    post_url_template: https://shopee.sg/{}
    price_retriever_module:
      replace_old: \$
      replace_new: SGD
