include: shopee.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://shopee.com.br/search?keyword={}&sortBy=ctime
    poster_post_identifiers_retriever_module:
      regex: shopee\.com\.br\/(.*)$
    post_identifiers_retriever_module:
      regex: shopee\.com\.br\/(.*)$
    price_retriever_module:
      replace_old: R\$
      replace_new: BRL
  post_information_retriever_module:
    post_url_template: https://shopee.com.br/{}
    price_retriever_module:
      replace_old: R\$
      replace_new: BRL