include: shopee.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://shopee.com.mx/search?keyword={}&sortBy=ctime
    poster_post_identifiers_retriever_module:
      regex: shopee\.com\.mx\/(.*)$
    post_identifiers_retriever_module:
      regex: shopee\.com\.mx\/(.*)$
    price_retriever_module:
      replace_old: \$
      replace_new: ''
  post_information_retriever_module:
    post_url_template: https://shopee.com.mx/{}
    price_retriever_module:
      replace_old: \$
      replace_new: ''