framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 2
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.snapdeal.com/search?keyword={}&sort=rec
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .product-tuple-image >a
      attribute_name: href
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .product-tuple-image >a
      attribute_name: href
    listing_container_css_selector: '#products>section>div'
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .product-title
    price_retriever_module:
      name: get_attribute_value
      css_selector: .product-price
      attribute_name: textContent
      replace_old: Rs.
      replace_new: INR
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: picture.picture-elem>img
      attribute_name: src
    load_more_results_module:
      name: load_more_by_scrolling_one_scroll_at_a_time
      css_selector: div#see-more-products
      scroll_pause_time: 1
      scroll_range: 3
      loading_delay: 2
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: '{}'
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: '#productOverview [itemprop=name]'
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: '[itemprop=description]'
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: span.pdp-final-price
      attribute_name: textContent
      replace_old: Rs.
      replace_new: INR
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div.sellerNameContainer a[href*="/seller/"]
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_value
      css_selector: div.sellerNameContainer a[href*="/seller/"]
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '[class*=carousel] li>img'
      attribute_name: src
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    loading_delay: 5
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .seller-name
      attribute_name: textContent
