framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 5
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.storenvy.com/shop/?q={}
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .search-results-page>.product.tile a.product-link
      regex: storenvy.com\/products\/(.+)$
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .search-results-page>.product.tile a.product-link
      regex: storenvy.com\/products\/(.+)$
    listing_container_css_selector: .search-results-page>.product.tile
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: a.product-link
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: span.price
      replace_old: \$
      replace_new: USD
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: a.product-store-name
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: a.product-store-name
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .image-link>a>img
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: a.next-page.pagination-link
      loading_delay: 4
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.storenvy.com/products/{}
    take_screenshot: true
    loading_delay: 3
    title_retriever_module:
      name: get_attribute_value
      css_selector: .product-info>.product-name
    description_retriever_module:
      name: get_attribute_value
      css_selector: .product-description>.desc-wrap
    price_retriever_module:
      name: get_attribute_value
      css_selector: .product-info .vprice
      replace_old: \$
      replace_new: USD
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .product-store a.product-store-name
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .product-store a.product-store-name
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      css_selector: li.fpZoomPic img
      clickable_css_selector_1: '.product-info #main-photo'
      clickable_css_selector_2: .fancybox-inner>a.fancybox-next
      picture_css_selector: .fancybox-inner>img.fancybox-image
      attribute_name: src
      regex: (.+)
      escape_popup_on_end: true
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .store.profile-header .profile-name , p.store-name
    description_retriever_module:
      name: get_attribute_value
      css_selector: .store.profile-description
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img.store-logo , .store.profile-avatar img
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: .store-order-info>span
      value_css_selector: .store-order-info>span
      key_css_selector_attribute_name: class
