framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  proxies:
    - name: iproyal/us
    - name: proxyrack
      country: BR
  search_pages_browsing_module:
    name: classic_page_browsing_module
    take_screenshots: true
    loading_delay: 3
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.submarino.com.br/busca/{}?brand=suba
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: div[class*="message-box"] button
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div[class*="src__GridItem"] div[class*="inStockCard__Wrapper"]
        a
      regex: submarino.com.br/produto/(.*)
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div[class*="src__GridItem"] div[class*="inStockCard__Wrapper"]
        a
      regex: submarino.com.br/produto/(.*)
    listing_container_css_selector: div[class*="src__GridItem"] div[class*="inStockCard__Wrapper"]
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: ul[class*="src__Items"] li:last-of-type
    title_retriever_module:
      name: get_attribute_value
      css_selector: h3[class*="product-name"]
    price_retriever_module:
      name: get_attribute_value
      css_selector: span[class*="price__PromotionalPrice"]
      replace_old: R\$
      replace_new: BRL
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: picture[class*="src__Picture"] img
      attribute_name: src
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://submarino.com.br/produto/{}
    take_screenshot: true
    loading_delay: 2
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: div[class*="message-box"] button
    title_retriever_module:
      name: get_attribute_value
      css_selector: h1[class*="Title"]
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: div[id="info-section"]
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="ProductOffer"] div[class*="BestPrice"]
      attribute_name: textContent
      replace_old: R\$
      replace_new: BRL
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="ProductOffer"] a[class*="components__Link"]
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: div[class*="ProductOffer"] a[class*="components__Link"]
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: div[class*="src__ProductInfo"] div[class*="image"]
        picture img
      clickable_css_selector_2: div[class*="pswp__scroll"] button[class*="arrow--right"]
      picture_css_selector: .pswp__item img
      attribute_name: src
      regex: (.+)
      escape_popup_on_end: true
      loading_delay: 2
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector:
          - div[class*="message-box"] button
          - div[class*="src__Wrapper"] picture img[alt="Ver todos"]
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="seller-about__Container"] img[class*="SellerImage"]
      attribute_name: alt
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div[class*="seller-about__Container"] img[class*="SellerImage"]
      attribute_name: src
    description_retriever_module:
      name: get_attribute_value
      css_selector: div[class*="seller-about__Container"] p[class*="Description"]
