framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
    start_maximized: true
    load_images: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 5

    # Keyword search not available for this domain
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - '{}'
    listing_container_css_selector: a[class*="normal_item"]
    title_retriever_module:
      name: get_attribute_value
      attribute_name: title
      css_selector: a[class*="normal_item"]>div.clear
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div.clear img:not([src*="data:image/png"])
      attribute_name: src
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: a[class*="normal_item"]
      attribute_name: 'data-href'
      post_url_cleaning_module:
        skip_query_string_cleaning: true
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: a[class*="normal_item"]
      attribute_name: 'data-href'
      post_url_cleaning_module:
        skip_query_string_cleaning: true
      regex: \/theme_detail\/(.+)
    load_more_results_module:
      name: load_more_by_scrolling_module
      scroll_pause_time: 3
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    take_screenshot: true
    post_url_template: https://www.szwego.com/static/index.html?#/album/details/commodity_detail/{}
    loading_delay: 3
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="title_"]>div:nth-of-type(1)>div'
      attribute_name: 'data-clipboard-text'
    description_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="index-module_title_font_"]'
      attribute_name: 'data-clipboard-text'
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="index-module_name"]'
      attribute_name: textContent
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '.swiper-slide>img'
      attribute_name: src
    videos_retriever_module:
      name: get_pictures_from_popup
      clickable_css_selector: .swiper-slide>img+div[class*="video_play_icon"]
      picture_css_selector: video.media-swiper-video
      attribute_name: src
      close_button_css_selector: .swiper-slide-active video
      regex: (.+)
      loading_delay: 2
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    loading_delay: 5
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: div.shopName
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: .signBoard_body>div>img
      attribute_name: src
