framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 1
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.target.com.au/search?sEngine=c&text={}
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: button#CookieUseAgreement-button
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: ul.listing-page>div>li .name-heading>a
      regex: target.com.au\/p\/(.+)$
    listing_container_css_selector: ul.listing-page>div>li
    title_retriever_module:
      name: get_attribute_value
      css_selector: .name-heading
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: .detail .price-regular
      attribute_name: textContent
      replace_old: \$
      replace_new: AUD
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: a.thumb img
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: button.RefineMenu-arrow.next
      loading_delay: 2
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.target.com.au/p/{}
    loading_delay: 3
    take_screenshot: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: button#CookieUseAgreement-button
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[data-component="productDetailPage"] .prod-heading>h1'
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: .ProductFeaturesPanel-heading--details+p
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[data-component="productDetailPage"] .price-regular>span.Price'
      replace_old: \$
      replace_new: AUD
    pictures_retriever_module:
      name: get_pictures_by_clicking_thumbnails
      clickable_css_selector: .GalleryList-thumbnails>ul>li>button
      picture_css_selector: .GalleryList-main>ul>li figure.is-loaded>img
      attribute_name: src
      regex: (.+)
      loading_delay: 2
