framework:
  name: selenium_framework
  proxies:
    - name: proxyrack
    - name: iproyal/us
    - name: iproyal/lithuania
    - name: 123proxy
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.trademe.co.nz/a/search?search_string={}&sort_order=expirydesc
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '[class*="search-results"] tg-col a[class*="card__detail"]'
      regex: trademe.co.nz/a/marketplace/(.+)
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: '[class*="search-results"] tg-col a[class*="card__detail"]'
      regex: trademe.co.nz/a/marketplace/(.+)
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: nav[role="navigation"] ul li:last-child a
    listing_container_css_selector: '[class*="search-results"] tg-col:has(a[class*="card__detail"])'
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[tmid="title"]'
    price_retriever_module:
      name: get_attribute_value
      css_selector: .tm-marketplace-search-card__price
      replace_old: \$
      replace_new: 'NZD '
      regex: ([^–]+)
    location_retriever_module:
      name: get_attribute_value
      css_selector: '[tmid="region"]'
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img.marketplace-summary-image-lazy-loader__full
      attribute_name: src
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.trademe.co.nz/a/marketplace/{}
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="listing_title"]'
    description_retriever_module:
      name: get_attribute_value
      css_selector: .tm-markdown
    price_retriever_module:
      name: get_attribute_value
      css_selector: '[class*="tm-listing-auction__box"] p.p-h1 strong, p.tm-buy-now-box__price.p-h1
        strong'
      replace_old: \$
      replace_new: 'NZD '
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: section.member-summary-box h3
    poster_link_retriever_module:
      name: get_attribute_value
      css_selector: a.tm-member-profile-image__link
      attribute_name: href
      regex: trademe.co.nz/(.+)
    ships_from_retriever_module:
      name: get_key_value_list
      key_css_selector: '#shipping-options tbody tr:last-child > td'
      value_css_selector: '#shipping-options tbody tr:last-child > td'
      key_regex: available from (.+)
      value_regex: available from (.+)
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_2: '[name="basic-arrow-right"]'
      picture_css_selector: tg-image-viewer-item.o-image-viewer__item--active tg-aspect-ratio
      regex: url\(\"(.+)\"
      attribute_name: style
      escape_popup_on_end: true
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: https://www.trademe.co.nz/{}
    take_screenshot: true
    loading_delay: 5
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: title
      replace_old: .+from
      replace_new: ''
      regex: '[^\|]+'
    description_retriever_module:
      name: click_then_get_attribute
      button_css_selector: a[href*="about-the-store"]
      css_selector: div#pageHtml
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img#StoreTitleControlWrapper_storeHeaderImage
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list_from_different_elements
      clickable_css_selectors:
        - a[href*="=feedback"]
      key_css_selectors:
        - a.tm-member-profile-banner__title span
        - div#mainContent table table tr:nth-of-type(1) td:nth-of-type(2)
        - div#mainContent table table tr:nth-of-type(2) td:nth-of-type(2)
        - div#mainContent table table tr:nth-of-type(3) td:nth-of-type(2)
      value_css_selectors:
        - a.tm-member-profile-banner__title
        - div#mainContent table table tr:nth-of-type(1) td:nth-of-type(2)
        - div#mainContent table table tr:nth-of-type(2) td:nth-of-type(2)
        - div#mainContent table table tr:nth-of-type(3) td:nth-of-type(2)
      key_regex:
        - stars
        - positive feedbacks
        - neutral feedbacks
        - negative feedbacks
      value_regex:
        - \(([^\)]+)
        - ([\d]+) positive feedbacks
        - ([\d]+) neutral feedbacks
        - ([\d]+) negative feedbacks
      key_attributes:
        - class
        - textContent
        - textContent
        - textContent
      value_attributes:
        - textContent
        - textContent
        - textContent
        - textContent
