include: carousell.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://tw.carousell.com/search/{}?sort_by=3
        - https://tw.carousell.com/search/{}
    post_identifiers_retriever_module:
      regex: tw\.carousell\.com\/p\/(.+)
    poster_post_identifiers_retriever_module:
      regex: tw\.carousell\.com\/p\/(.+)
  post_information_retriever_module:
    post_url_template: https://tw.carousell.com/p/{}
    vendor_retriever_module:
      regex: https://tw\.carousell\.com/u/(.+)/$
    price_retriever_module:
      replace_old: NT\$
      replace_new: TWD
  poster_information_retriever_module:
    description_retriever_module:
      css_selector: div h2 ~ div ~ div ~ div ~ div > p
