framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 12
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.ubuy.us/storeswap?store=uk&q={}
        - https://www.ubuy.us/storeswap?store=jp&q={}
        - https://www.ubuy.us/storeswap?store=ch&q={}
        - https://www.ubuy.us/storeswap?store=hk&q={}
        - https://www.ubuy.us/storeswap?store=kr&q={}
        - https://www.ubuy.us/storeswap?store=tr&q={}
        - https://www.u-buy.co.uk/storeswap?store=us&q={}
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: .notice-cookie-actions>button
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div.product-card>a.img-detail
    listing_container_css_selector: div.product-card
    title_retriever_module:
      name: get_attribute_value
      css_selector: .product-title
      attribute_name: textContent
    price_retriever_module:
      name: get_attribute_value
      css_selector: .product-price
      attribute_name: textContent
      exclude_children: true
      loading_timeout: 0.1
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: a.img-detail>.product-image>img
      attribute_name: src
    load_more_results_module:
      name: load_more_by_scrolling_one_scroll_at_a_time
      scroll_range: 2
      scroll_pause_time: 0.5
      loading_delay: 10
      css_selector: .pagination>li[title="Next"]>a
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: '{}'
    loading_delay: 6
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: .detail-page .title
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: .product-detail-section [itemprop="description"]
      attribute_name: textContent
      loading_timeout: 0.1
    price_retriever_module:
      name: get_attribute_value
      css_selector: .price-box .product-price
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .seller-info>a
      attribute_name: textContent
      loading_timeout: 0.1
    stock_retriever_module:
      name: get_attribute_value
      css_selector: .instock-items
    pictures_retriever_module:
      name: get_pictures_from_popup_with_multi_selectors
      clickable_css_selector_1: .slider-for .slick-track>.slick-active>div
      clickable_css_selector_2: button.fancybox-button[title="Next"]
      picture_css_selector: .fancybox-slide--current>div>img
      attribute_name: src
      loading_delay: 2
      regex: (.+)
      escape_popup_on_end: true
      skip_video: true
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: .modal-footer>.btn-primary
        after_pause_time: 12
