framework:
  name: selenium_framework
  proxies:
    - name: iproyal/us
    - name: iproyal/lithuania
    - name: horcon
  driver_initialization_module:
    name: classic_selenium_initialization_module
    override_user_agent: true
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 2
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://unit808.com/shop/search.php?search_text={}&orderby=regdate2
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      post_url_cleaning_module:
        skip_query_string_cleaning: true
      css_selector: .goods_list_new>ul>li>dl>dt>a
      regex: shop\/goods_view.php\?id\=(.+)$
    listing_container_css_selector: .goods_list_new>ul>li>dl
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .goods_name
    price_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: .goods_price>span
      replace_old: \원
      replace_new: KRW
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: dt>a>img
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: .paging>div>span.on+*
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://unit808.com/shop/goods_view.php?id={}
    loading_delay: 3
    title_retriever_module:
      name: get_attribute_value
      css_selector: .goods_name_new
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      iframe_css_selector: .iframe_detail_class>iframe
      css_selector: '#minicontent'
    price_retriever_module:
      name: get_attribute_value
      css_selector: .c_price_class>span:first-child
      replace_old: \원
      replace_new: KRW
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .minishop-table tr:first-child>td
    ships_from_retriever_module:
      name: get_key_value_list
      key_css_selector: .goods_view .country
      value_css_selector: .goods_view .country
    pictures_retriever_module:
      name: get_pictures_by_clicking_thumbnails
      clickable_css_selector: .goods_info_box .Jhslider_common>div>div>img
      picture_css_selector: .goods_info_box .goods_img>img
      attribute_name: src
      regex: (.+)
      loading_delay: 2
