include: vinted.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.vinted.cz/vetements?search_text={}&order=newest_first
    post_identifiers_retriever_module:
      regex: vinted.cz\/(.*)$
    poster_post_identifiers_retriever_module:
      regex: vinted.cz\/(.*)$
    price_retriever_module:
      replace_old: K\č
      replace_new: CZK
  post_information_retriever_module:
    post_url_template: https://www.vinted.cz/{}
    location_retriever_module:
      title_column_name: LOKACE
    price_retriever_module:
      replace_old: K\č
      replace_new: CZK