include: vinted.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.vinted.co.uk/vetements?search_text={}&order=newest_first
    post_identifiers_retriever_module:
      regex: vinted.co.uk\/(.*)$
    poster_post_identifiers_retriever_module:
      regex: vinted.co.uk\/(.*)$
    price_retriever_module:
      replace_old: \£
      replace_new: GBP
  post_information_retriever_module:
    post_url_template: https://www.vinted.co.uk/{}
    location_retriever_module:
      title_column_name: LOCATION
    price_retriever_module:
      replace_old: \£
      replace_new: GBP