include: vinted.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.vinted.com/vetements?search_text={}&order=newest_first
    post_identifiers_retriever_module:
      regex: vinted.com\/(.*)$
    poster_post_identifiers_retriever_module:
      regex: vinted.com\/(.*)$
    price_retriever_module:
      replace_old: \$
      replace_new: USD
  post_information_retriever_module:
    post_url_template: https://www.vinted.com/{}
    location_retriever_module:
      title_column_name: Location
    price_retriever_module:
      replace_old: \$
      replace_new: USD