framework:
  name: selenium_framework
  proxies:
    - name: iproyal/us
    - name: 123proxy
    - name: proxyrack
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.walmart.ca/search?q={}
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div[data-automation="product-results"] div[data-automation="product"]
        a
      attribute_name: href
      regex: walmart.ca\/(.*)
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div[data-automation="product-results"] div[data-automation="product"]
        a
      attribute_name: href
      regex: walmart.ca\/(.*)
    listing_container_css_selector: div[data-automation="product"]
    title_retriever_module:
      name: get_attribute_value
      css_selector: p[data-automation="name"]
    price_retriever_module:
      name: get_attribute_value
      css_selector: span[data-automation*="current-price"]
      replace_old: \$
      replace_new: 'CAD '
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img[data-automation="image"]
      attribute_name: src
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: a[data-automation="pagination-next-button"]
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: button[id="accept-privacy-policies"] , [data-testid="privacy-banner"]>button
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.walmart.ca/{}
    take_screenshot: true
    loading_delay: 3
    title_retriever_module:
      name: get_attribute_value
      css_selector: 'h1[data-automation="product-title"] , #main-title'
    description_retriever_module:
      name: get_attribute_value
      css_selector: div[data-automation="long-description"] , [data-testid="product-description-content"]
    price_retriever_module:
      name: get_attribute_value
      css_selector: span[data-automation="buybox-price"]
      replace_old: \$
      replace_new: 'CAD '
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: button[data-automation="vendor-link"]
    poster_link_retriever_module:
      name: click_then_get_attribute
      button_css_selector: button[data-automation="vendor-link"]
      css_selector: meta[property="og:url"]
      attribute_name: content
      click_opens_new_tab: true
      loading_delay: 1
    pictures_retriever_module:
      name: get_pictures_by_clicking_thumbnails
      clickable_css_selector: div[data-automation="image-banner"] ~ div div[data-automation="thumb-gallery-image"]
        a , [data-testid="vertical-carousel-container"] [data-testid="media-thumbnail"]
      picture_css_selector: '[data-automation="image-banner"]+div div[style*="transform:
        translate(0px, 0px)"]>div>div>div>img#main-image , [data-testid="hero-image-container"]>div>img'
      regex: (.+)
      attribute_name: src
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: button[id="accept-privacy-policies"] , [data-testid="privacy-banner"]>button
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: h1[data-automation="primary-heading"]
