include: worten.yaml
framework:
  proxies:
    - name: proxyrack
      country: PT
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.worten.pt/search?query={}
    post_identifiers_retriever_module:
      regex: worten.pt\/produtos\/(.+)
  post_information_retriever_module:
    post_url_template: https://www.worten.pt/produtos/{}
  poster_information_retriever_module:
    poster_url_template: 'https://www.worten.pt/marketplace-seller?seller_id={}'