framework:
  name: selenium_framework
  proxies:
    - name: iproyal/us
    - name: iproyal/lithuania
    - name: horcon
  driver_initialization_module:
    name: classic_selenium_initialization_module
    start_maximized: true
  search_pages_browsing_module:
    name: classic_page_browsing_module
    loading_delay: 4
    action_before_search_pages_browsing_module:
      name: refresh_page
      after_pause_time: 12
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - only support poster search and post retrieval for this config
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .feeds-container>.note-item>a:first-child
      regex: xiaohongshu.com\/explore\/(.*)
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: .feeds-container>.note-item>a:first-child
      regex: xiaohongshu.com\/explore\/(.*)
    listing_container_css_selector: .feeds-container>.note-item
    title_retriever_module:
      name: get_attribute_value
      attribute_name: textContent
      css_selector: div>a.title>span
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div>div>a.author
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: div>div>a.author
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: a.cover
      attribute_name: style
      regex: \(\"(.+)\"\)
    load_more_results_module:
      name: load_more_by_scrolling_one_scroll_at_a_time
      scroll_pause_time: 1
      scroll_range: 1
      loading_delay: 5
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.xiaohongshu.com/explore/{}
    take_screenshot: true
    loading_delay: 3
    action_before_retrieving_post_information_module:
      name: refresh_page
      after_pause_time: 12
    title_retriever_module:
      name: get_attribute_value
      css_selector: .interaction-container .title
      attribute_name: textContent
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: .author>.info>a.name
      attribute_name: textContent
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: .author>.info>a.name
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '#videoPlayer>.xgplayer-poster , .swiper-wrapper>div.swiper-slide:not(.swiper-slide-duplicate)'
      attribute_name: style
      regex: \(\"(.+)\"\)
    videos_retriever_module:
      name: get_pictures_from_attribute
      css_selector: '#videoPlayer>video'
      attribute_name: src
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    loading_delay: 3
    take_screenshot: true
    action_before_retrieving_post_information_module:
      name: refresh_page
      after_pause_time: 12
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: .user-name
      attribute_name: textContent
    description_retriever_module:
      name: get_attribute_value
      css_selector: .user-desc
      attribute_name: textContent
    picture_retriever_module:
      name: get_pictures_from_attribute
      css_selector: img.user-images
      attribute_name: src
    payload_retriever_module:
      name: get_key_value_list
      key_css_selector: .user-interactions>div>span:last-child
      value_css_selector: .user-interactions>div>span:first-child
