framework:
  name: selenium_framework
  driver_initialization_module:
    name: classic_selenium_initialization_module
  search_pages_browsing_module:
    name: classic_page_browsing_module
    scroll_down_after_get_new_page: true
    search_page_urls_builder_module:
      name: classic_search_page_urls_builder_module
      search_page_url_templates:
        - https://www.yatego.com/suche/{}
    action_before_search_pages_browsing_module:
      - name: click_action_module
        css_selector: button.cookie-wall-button
    poster_post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div.search-results a
      regex: yatego.com\/p\/(.+)
      listing_container_css_selector: div.search-results a
      title_retriever_module:
        name: get_attribute_value
        css_selector: .details .title
        attribute_name: title
      price_retriever_module:
        name: get_attribute_value
        css_selector: div.price span
        regex: \€.*
        replace_old: \€
        replace_new: EUR
      pictures_retriever_module:
        name: get_pictures_from_attribute
        css_selector: div.image img
        attribute_name: src
      load_more_results_module:
        name: click_on_next_page_module
        css_selector: div.search-pagination div.next
    post_identifiers_retriever_module:
      name: classic_post_identifiers_retriever_module
      css_selector: div.search-result-view .search-grid .results a
      regex: yatego.com\/p\/(.+)
    load_more_results_module:
      name: click_on_next_page_module
      css_selector: div.pagination div.next
    listing_container_css_selector: div.search-result-view .search-grid .results a
    title_retriever_module:
      name: get_attribute_value
      css_selector: div.title
      attribute_name: title
    price_retriever_module:
      name: get_attribute_value
      css_selector: div.price > span
      regex: \€.*
      replace_old: \€
      replace_new: EUR
    pictures_retriever_module:
      name: get_pictures_from_attribute
      css_selector: div.image img
      attribute_name: src
  post_information_retriever_module:
    name: classic_post_information_retriever_module
    post_url_template: https://www.yatego.com/p/{}
    take_screenshot: true
    title_retriever_module:
      name: get_attribute_value
      css_selector: meta[itemprop="name"]
      attribute_name: content
    description_retriever_module:
      name: get_attribute_value
      css_selector: div[itemprop="description"]
    price_retriever_module:
      name: get_attribute_value
      css_selector: span[itemprop="price"]
      replace_old: (.*)
      replace_new: \g<1> EUR
    vendor_retriever_module:
      name: get_attribute_value
      css_selector: div[itemprop="seller"] a[itemprop="name"]
    poster_link_retriever_module:
      name: get_attribute_url
      css_selector: div[itemprop="seller"] a[itemprop="name"]
      attribute_name: href
    pictures_retriever_module:
      name: get_pictures_by_clicking_thumbnails
      clickable_css_selector: div.image-gallery div.list .item img
      picture_css_selector: div.image-gallery div.image picture source[srcset]:first-child
      regex: (.+?)\s
      attribute_name: srcset
      loading_delay: 4
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: button.cookie-wall-button
  poster_information_retriever_module:
    name: classic_poster_information_retriever_module
    poster_url_template: '{}'
    take_screenshot: true
    poster_name_retriever_module:
      name: get_attribute_value
      css_selector: div.details h1
    description_retriever_module:
      name: get_attribute_value
      css_selector: div.description
    action_before_retrieving_post_information_module:
      - name: click_action_module
        css_selector: button.cookie-wall-button
