"""Add post.scraping_status

Revision ID: 04c754f05cf7
Revises: 87ddaf02e4b4
Create Date: 2023-06-29 16:05:15.807864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "04c754f05cf7"
down_revision = "87ddaf02e4b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    scrapingstatus = postgresql.ENUM(
        "SEARCHED", "SCRAPED", "FILTERED_IN", "FILTERED_OUT", "SENT", name="scrapingstatus"
    )
    scrapingstatus.create(op.get_bind())
    op.add_column(
        "posts",
        sa.Column(
            "scraping_status",
            sa.Enum("SEARCHED", "SCRAPED", "FILTERED_IN", "FILTERED_OUT", "SENT", name="scrapingstatus"),
            nullable=True,
        ),
    )
    op.create_index(op.f("ix_posts_scraping_status"), "posts", ["scraping_status"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "scraping_status")
    op.drop_index(op.f("ix_posts_scraping_status"), table_name="posts")
    # ### end Alembic commands ###
