"""Save post task id

Revision ID: 0e2f89725805
Revises: c8cab2a5290b
Create Date: 2023-02-14 11:04:12.058777

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0e2f89725805"
down_revision = "3c957406938a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("task_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "posts", "tasks", ["task_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_task_id"), table_name="posts")
    op.drop_column("posts", "task_id")
    # ### end Alembic commands ###
