"""Scraping attempts index

Revision ID: 263329eaea8d
Revises: ba1fbab382df
Create Date: 2023-09-06 14:38:44.811851

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "263329eaea8d"
down_revision = "ba1fbab382df"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_scraping_attempts_website_id_time", "scraping_attempts", ["website_id", "time"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_scraping_attempts_website_id_time", table_name="scraping_attempts")
    # ### end Alembic commands ###
