"""Add tasks_logs.number_of_filtered_results_found

Revision ID: 352c47ae15ab
Revises: 04c754f05cf7
Create Date: 2023-07-12 17:41:49.547556

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "352c47ae15ab"
down_revision = "04c754f05cf7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks_logs", sa.Column("number_of_filtered_results_found", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks_logs", "number_of_filtered_results_found")
    # ### end Alembic commands ###
