"""Add exclude keywords

Revision ID: 3a2f2f590a33
Revises: 890976f09e86
Create Date: 2023-04-20 11:40:46.750177

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3a2f2f590a33"
down_revision = "890976f09e86"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organisations", sa.Column("exclude_keywords", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organisations", "exclude_keywords")
    # ### end Alembic commands ###
