"""Add search_query_logs

Revision ID: 5186b35d2a53
Revises: 352c47ae15ab
Create Date: 2023-08-09 16:55:43.610848

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "5186b35d2a53"
down_revision = "352c47ae15ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_query_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("search_query", sa.String(), nullable=False),
        sa.Column("search_url", sa.String(), nullable=False),
        sa.Column("task_log_id", sa.Integer(), nullable=True),
        sa.Column("start_date_time", sa.DateTime(), nullable=False),
        sa.Column("end_date_time", sa.DateTime(), nullable=True),
        sa.Column("number_of_posts_with_search_info", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_log_id"],
            ["tasks_logs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_search_query_logs_search_query"), "search_query_logs", ["search_query"], unique=False)
    op.create_index(op.f("ix_search_query_logs_search_url"), "search_query_logs", ["search_url"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_search_query_logs_search_url"), table_name="search_query_logs")
    op.drop_index(op.f("ix_search_query_logs_search_query"), table_name="search_query_logs")
    op.drop_table("search_query_logs")
    # ### end Alembic commands ###
