"""Add new log fields

Revision ID: 55aa38d69157
Revises: a7b77fa203b8
Create Date: 2023-09-25 17:05:55.602917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "55aa38d69157"
down_revision = "a7b77fa203b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ##
    op.add_column("tasks_logs", sa.Column("website_id", sa.Integer(), nullable=True))
    op.add_column(
        "tasks_logs", sa.Column("light_posts_extraction_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column(
        "tasks_logs", sa.Column("poster_extraction_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.create_foreign_key(None, "tasks_logs", "websites", ["website_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks_logs", "poster_extraction_info")
    op.drop_column("tasks_logs", "light_posts_extraction_info")
    op.drop_column("tasks_logs", "website_id")
    # ### end Alembic commands ###
