"""add columns for poster's counter

Revision ID: 7082da5bd5c0
Revises: 55aa38d69157
Create Date: 2023-09-28 22:23:32.179118

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "7082da5bd5c0"
down_revision = "55aa38d69157"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks_logs", sa.Column("number_of_posters_discovered", sa.Integer(), nullable=True))
    op.add_column("tasks_logs", sa.Column("number_of_posters_scraped", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks_logs", "number_of_posters_scraped")
    op.drop_column("tasks_logs", "number_of_posters_discovered")
    # ### end Alembic commands ###
