"""Update Logs

Revision ID: 75954bf63815
Revises: 59761382cad1
Create Date: 2023-08-22 12:20:21.815495

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "75954bf63815"
down_revision = "59761382cad1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_index(
        "ix_scraping_attempts_proxy_provider_request_result_time",
        "scraping_attempts",
        ["proxy_provider", "request_result", "time"],
        unique=False,
    )
    op.create_index(
        "ix_scraping_attempts_dashboard3",
        "scraping_attempts",
        ["proxy_provider", "time", "website_id", "request_result"],
        unique=False,
    )
    op.create_index(
        "ix_scraping_attempts_dashboard2",
        "scraping_attempts",
        ["proxy_provider", "website_id", "request_result", "time"],
        unique=False,
    )
    op.create_index(
        "ix_scraping_attempts_dashboard1",
        "scraping_attempts",
        ["proxy_provider", "request_result", "website_id", "time"],
        unique=False,
    )

    op.add_column("search_query_logs", sa.Column("max_posts_to_browse", sa.Integer(), nullable=True))
    op.add_column("search_query_logs", sa.Column("max_posts_to_discover", sa.Integer(), nullable=True))
    op.add_column("search_query_logs", sa.Column("number_of_posts_discovered", sa.Integer(), nullable=True))

    op.add_column("tasks", sa.Column("max_posts_to_discover", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_scraping_attempts_dashboard1", table_name="scraping_attempts")
    op.drop_index("ix_scraping_attempts_dashboard2", table_name="scraping_attempts")
    op.drop_index("ix_scraping_attempts_dashboard3", table_name="scraping_attempts")
    op.drop_index("ix_scraping_attempts_proxy_provider_request_result_time", table_name="scraping_attempts")

    op.drop_column("tasks", "max_posts_to_discover")

    op.drop_column("search_query_logs", "number_of_posts_discovered")
    op.drop_column("search_query_logs", "max_posts_to_discover")
    op.drop_column("search_query_logs", "max_posts_to_browse")

    # ### end Alembic commands ###
