"""Add organisation.activate_filtering

Revision ID: 890976f09e86
Revises: c8cab2a5290b
Create Date: 2023-04-17 12:40:03.192554

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "890976f09e86"
down_revision = "c8cab2a5290b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organisations", sa.Column("activate_filtering", sa.Boolean(), nullable=False, server_default="false")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organisations", "activate_filtering")
    # ### end Alembic commands ###
