"""add an index in posts table

Revision ID: 921fea7a1d54
Revises: 263329eaea8d
Create Date: 2023-09-14 16:06:56.139915

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "921fea7a1d54"
down_revision = "263329eaea8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_posts_org_id_id_website_id_scraping_status_risk_score",
        "posts",
        ["organisation_id", "id", "website_id", "scraping_status", "risk_score"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_posts_org_id_id_website_id_scraping_status_risk_score", table_name="posts")
    # ### end Alembic commands ###
