"""first-db-difference

Revision ID: 9ae3f5f59c3e
Revises:
Create Date: 2022-11-28 11:49:40.049387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9ae3f5f59c3e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("max_posts_to_browse", sa.Integer(), nullable=True))
    op.alter_column("tasks", "organisation_id", existing_type=sa.INTEGER(), nullable=True)
    op.add_column("tasks_logs", sa.Column("name", sa.String(), nullable=True))
    op.add_column(
        "tasks_logs",
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.alter_column("tasks_logs", "task_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "tasks_logs",
        "start_date_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks_logs",
        "start_date_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column("tasks_logs", "task_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("tasks_logs", "payload")
    op.drop_column("tasks_logs", "name")
    op.alter_column("tasks", "organisation_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("tasks", "max_posts_to_browse")
    op.drop_index(op.f("ix_posts_platform_id"), table_name="posts")

    # ### end Alembic commands ###
