"""add new columns for counters

Revision ID: a7b77fa203b8
Revises: 921fea7a1d54
Create Date: 2023-09-21 16:09:36.524965

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a7b77fa203b8"
down_revision = "921fea7a1d54"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("search_query_logs", sa.Column("number_of_posts_browse_attempts", sa.Integer(), nullable=True))
    op.add_column("search_query_logs", sa.Column("number_of_new_posts_found", sa.Integer(), nullable=True))
    op.add_column("search_query_logs", sa.Column("number_of_posts_after_prefiltering", sa.Integer(), nullable=True))
    op.add_column("search_query_logs", sa.Column("number_of_posts_scraped", sa.Integer(), nullable=True))
    op.add_column("search_query_logs", sa.Column("number_of_posts_sent", sa.Integer(), nullable=True))
    op.add_column("tasks_logs", sa.Column("number_of_posts_discovered", sa.Integer(), nullable=True))
    op.add_column("tasks_logs", sa.Column("number_of_posts_browse_attempts", sa.Integer(), nullable=True))
    op.add_column("tasks_logs", sa.Column("number_of_posts_sent", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks_logs", "number_of_posts_sent")
    op.drop_column("tasks_logs", "number_of_posts_browse_attempts")
    op.drop_column("tasks_logs", "number_of_posts_discovered")
    op.drop_column("search_query_logs", "number_of_posts_sent")
    op.drop_column("search_query_logs", "number_of_posts_scraped")
    op.drop_column("search_query_logs", "number_of_posts_after_prefiltering")
    op.drop_column("search_query_logs", "number_of_new_posts_found")
    op.drop_column("search_query_logs", "number_of_posts_browse_attempts")
    # ### end Alembic commands ###
