"""Add Image Search Tasks

Revision ID: b128505a0df1
Revises: 7082da5bd5c0
Create Date: 2023-10-10 12:58:18.998503

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b128505a0df1"
down_revision = "7082da5bd5c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("search_image_urls", sa.ARRAY(sa.String()), nullable=True))
    op.add_column(
        "tasks",
        sa.Column(
            "scraping_type",
            sa.Enum(
                "POST_SEARCH_COMPLETE",
                "POST_SEARCH_COUNT_ONLY",
                "POST_SEARCH_RADARLY",
                "POST_SCRAPE_FROM_LIST",
                "POSTER_SEARCH",
                "POST_IMAGE_SEARCH_COMPLETE",
                name="scrapingtype",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "scraping_type")
    op.drop_column("tasks", "search_image_urls")
    # ### end Alembic commands ###
