"""Monitoring Dashboard Index

Revision ID: ba1fbab382df
Revises: c04aa707b32c
Create Date: 2023-09-06 13:10:43.264979

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "ba1fbab382df"
down_revision = "c04aa707b32c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_light_post_logs_website_id_organisation_id_time",
        "light_post_logs",
        ["website_id", "time", "organisation_id"],
        unique=False,
    )
    op.create_index("ix_light_post_logs_website_id_time", "light_post_logs", ["website_id", "time"], unique=False)

    # Old ones added by Dana to imporve querying
    op.create_index(
        "ix_posts_website_id_scraping_status_scraping_time_platform_id",
        "posts",
        ["website_id", "scraping_status", "scraping_time", "platform_id"],
        unique=False,
    )
    op.create_index("ix_posts_website_id", "posts", ["website_id"], unique=False)
    op.create_index(
        "ix_posts_web_id_scraping_stats_scraping_time_platform_id_org_id",
        "posts",
        ["website_id", "scraping_status", "scraping_time", "platform_id", "organisation_id"],
        unique=False,
    )

    # Old one added by Alexey
    op.create_index(
        "ix_scraping_attempts_time_proxy_provider_request_result_website",
        "scraping_attempts",
        ["time", "proxy_provider", "request_result", "website_id"],
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_light_post_logs_website_id_time", table_name="light_post_logs")
    op.drop_index("ix_light_post_logs_website_id_organisation_id_time", table_name="light_post_logs")
    op.drop_index("ix_posts_web_id_scraping_stats_scraping_time_platform_id_org_id", table_name="posts")
    op.drop_index("ix_posts_website_id", table_name="posts")
    op.drop_index("ix_posts_website_id_scraping_status_scraping_time_platform_id", table_name="posts")
    op.drop_index("ix_scraping_attempts_time_proxy_provider_request_result_website", table_name="scraping_attempts")
    # ### end Alembic commands ###
