"""Rename Search Query Logs

Revision ID: c04aa707b32c
Revises: 75954bf63815
Create Date: 2023-08-22 17:36:28.681777

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "c04aa707b32c"
down_revision = "75954bf63815"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("search_query_logs", sa.Column("max_posts_to_browse", sa.Integer(), nullable=True))
    op.add_column("search_query_logs", sa.Column("number_of_posts_browsed", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("search_query_logs", "number_of_posts_browsed")
    op.drop_column("search_query_logs", "max_posts_to_browse")
    # ### end Alembic commands ###
