"""Post index

Revision ID: c8cab2a5290b
Revises: 3c957406938a
Create Date: 2023-01-17 16:28:39.079555

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "c8cab2a5290b"
down_revision = "0e2f89725805"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_posts_website_id_patform_id_sent_to_counterfeit_platform_org",
        "posts",
        ["website_id", "platform_id", "sent_to_counterfeit_platform", "organisation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_posts_website_id_patform_id_sent_to_counterfeit_platform_org", table_name="posts")
    # ### end Alembic commands ###
