"""stock count

Revision ID: ce8e03f6cdfb
Revises: 38e9fd715c1e
Create Date: 2023-04-27 10:56:53.127978

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ce8e03f6cdfb"
down_revision = "38e9fd715c1e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("stock_count", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "stock_count")
    # ### end Alembic commands ###
