""" Support Videos

Revision ID: f6b5475e3ee4
Revises: c8cab2a5290b
Create Date: 2023-04-14 16:39:12.287022

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f6b5475e3ee4"
down_revision = "c8cab2a5290b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("videos", sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "videos")
    # ### end Alembic commands ###
