LABEL_TO_PREDICTION = {
    "Counterfeit": 1,
    "Infringement": 1,
    "Legitimate": 0,
    "Counterfeit Non-Commercial": 1,
    "Suspicious": 1,
    "Irrelevant": 0,
    "Grey Market": 0,
    "Branded Packaging": 1,
    "Fan Content": 0,
    "Parasitism": 0,
    "Branded Elements": 0,
    "Actionable TMI": 1,
    "Tester": 1,
    "Collaboration": 0,
    "Other": 0,
    "Non-Collaboration": 0,
    "Copyright": 1,
    "Bakery": 1,
    "Recycling": 0,
    "Copyright Infringement": 1,
    "Design Infringement": 1,
}


Jan19 = "2023-01-19"
Feb8 = "2023-02-08"
Feb10 = "2023-02-10"
Feb13 = "2023-02-13"
Mar3 = "2023-03-03"
Jan17 = "2023-01-17"
Jan24 = "2023-01-24"
Jan29 = "2023-01-29"


LIGHT_POST_IMPLEMENTATION_DATE_PER_DOMAIN_NAMES = {
    "vinted.fr": Feb8,
    "rarible.com": Jan29,
    "mercadolibre.com.hn": Jan19,
    "ebay.ie": Jan19,
    "mercadolibre.com.ve": Jan19,
    "shopee.com.mx": Jan17,
    "carousell.com.my": Jan19,
    "mercadolibre.com.bo": Jan19,
    "shopee.vn": Jan17,
    "vinted.com": Feb8,
    "vinted.co.uk": Feb8,
    "carousell.ph": Jan19,
    "mercadolibre.com.co": Jan19,
    "shopee.sg": Jan17,
    "lazada.co.id": Mar3,
    "mercadolivre.com.br": Jan19,
    "vinted.de": Feb8,
    "ca.carousell.com": Jan19,
    "shopee.ph": Jan17,
    "mercadolibre.com.ni": Jan19,
    "tw.carousell.com": Jan19,
    "aliexpress.com": Jan24,
    "mercadolibre.com.sv": Jan19,
    "lazada.co.th": Mar3,
    "ebay.ph": Jan19,
    "ebay.ca": Jan19,
    "vinted.cz": Feb8,
    "mercadolibre.com.pa": Jan19,
    "carousell.com.hk": Jan19,
    "220.lv": Feb10,
    "vinted.lt": Feb8,
    "nz.carousell.com": Jan19,
    "lazada.sg": Mar3,
    "vinted.pl": Feb8,
    "mercadolibre.com.do": Jan19,
    "ebay.fr": Jan19,
    "shopee.cl": Jan17,
    "ebay.it": Jan19,
    "mercadolibre.com.uy": Jan19,
    "shopee.fr": Jan17,
    "lazada.vn": Mar3,
    "lazada.com.my": Mar3,
    "shopee.co.id": Jan17,
    "id.carousell.com": Jan19,
    "shopee.tw": Jan17,
    "lazada.com.ph": Mar3,
    "shopee.pl": Jan17,
    "shopee.co.th": Jan17,
    "ebay.com.my": Jan19,
    "mercadolibre.com.mx": Jan19,
    "carousell.sg": Jan19,
    "ebay.nl": Jan19,
    "ebay.pl": Jan19,
    "11st.co.kr": Feb13,
    "shopee.es": Jan17,
    "mercadolibre.cl": Jan19,
    "ebay.co.uk": Jan19,
    "ebay.at": Jan19,
    "ebay.com.hk": Jan19,
    "au.carousell.com": Jan19,
    "alibaba.com": Jan24,
    "shopee.com.my": Jan17,
    "ebay.com": Jan19,
    "mercadolibre.com.ar": Jan19,
    "ebay.com.au": Jan19,
    "mercadolibre.com.py": Jan19,
    "vinted.it": Feb8,
    "shopee.com.br": Jan17,
    "mercadolibre.com.gt": Jan19,
    "mercadolibre.com.ec": Jan19,
    "ebay.es": Jan19,
    "ebay.ch": Jan19,
    "mercadolibre.com.pe": Jan19,
    "mercadolibre.co.cr": Jan19,
}
