proxies:
  # - name: netnut
  #   default_country: any
  #   credentials:
  #     host: gw.ntnt.io
  #     port: 5959
  #     username: Navee1-res-{country}-sid-{sid}
  #     password: Gv1ARjj[!d9b

  # - name: KooKeey
  #   default_country: global
  #   credentials:
  #     host: gate-eu.kookeey.info
  #     port: 1000
  #     username: fe457969
      # password: dd50d0b3-{country}-{sid}

  # - name: smartproxy
  #   default_country: gate
  #   credentials:
  #     host: '{country}.smartproxy.com'
  #     port: 7000
  #     username: sp89652wy7
  #     password: nidim3c7ku3w4GNKRd

  - name: proxyrack
    default_country: ''
    credentials:
      host: private.residential.proxyrack.net
      port_range: 10000-10019
      username: navee;refreshSeconds-180;country={country}
      password: ac17a8-a3133e-61e51f-7af3a6-8ade88

  # salmin: paid for 30 days on 2023-09-22
  # New York, AT&T
  - name: proxys.io/mobile/shared/us
    default_country: ''
    credentials:
      host: 195.201.161.7
      port: 1033
      username: ZhRumNydNX
      password: UlJQdnOksB

  # salmin: paid for 1 day on 2023-09-22
  # quick test
  # Romania, Bucharest, Vodafone
  - name: proxys.io/mobile/dedicated/ro
    default_country: ''
    credentials:
      host: 37.139.34.51
      port: 13444
      username: efMYsE
      password: ufbeqABAPANT

  # salmin: paid for 30 days on 2023-09-22
  # Moscow, MTS
  - name: proxys.io/mobile/dedicated/ru
    default_country: ''
    credentials:
      host: 95.31.211.120
      port: 40024
      username: 0cb8fb3b5d
      password: dc55968bbf

  # salmin: paid for 30 days on 2023-08-20
  # Bangkok, DTAC
  #- name: proxys.io/mobile/shared/th
  #  default_country: ''
  #  credentials:
  #    host: 195.201.161.3
  #    port: 27001
  #    username: nBiJNp9mlVYa
  #    password: 1jzz5aNJiD

  # salmin: paid for 30 days on 2023-08-20
  # Moscow, MTS
  #- name: proxys.io/mobile/dedicated/ru
  #  default_country: ''
  #  credentials:
  #    host: 95.31.211.120
  #    port: 30429
  #    username: 080826f0d4
  #    password: 07e8206280

  # salmin: paid for 30 days on 2023-09-22
  # Bangkok, AIS
  - name: proxys.io/mobile/dedicated/th
    default_country: ''
    credentials:
      host: 89.208.231.46
      port: 10730
      username: bEy1rA
      password: RAU5eHAVYv6m

  # Paid By GB to Avoid using - testing it for fb marketplace
  - name: iproyal_residential
    default_country: ''
    credentials:
      host: fra8.hypeproxy.host
      port: 7486
      username: hpfdbfaf14
      password: 32ecb84e7da94231

  # hugo: paid for 90 days on 2023-07-02 - US
  - name: iproyal/us
    default_country: ''
    switch_ip_url: 'https://dashboard.iproyal.com/api/4g-mobile-proxies/rotate-ip/kvjpZMILPh'
    credentials:
      host: us2.4g.iproyal.com
      port: 7077
      username: OuCMK8u
      password: XRviCdIvBYF5ZEa

  # hugo: paid for 90 days on 2023-08-16 - LT / key change on 2023-09-08
  - name: iproyal/lithuania
    default_country: ''
    switch_ip_url: 'https://dashboard.iproyal.com/api/4g-mobile-proxies/rotate-ip/4gSVhOscwM'
    credentials:
      host: lt.4g.iproyal.com
      port: 6048
      username: 4WfRo93
      password: g1uExj6M27L8Unx

  # dana: renewed for 3 months on 2023-09-08 expiry on December 08, 2023
  - name: 123proxy
    default_country: ''
    credentials:
      host: 185.165.190.32
      port_range: 10447-10461
      username: u1372703987980543
      password: sXGgfyvnuNgL


  # dana: paid for 3 months on 2023-09-08
  - name: horocn
    default_country: ''  # In China
    credentials:
      host: dyn.horocn.com
      port: 50000
      username: CCNN1776474149512142
      password: LnoPirh1vcw4
