INFRINGING_KEYWORDS = [
    "1:1",
    "aaa",
    "aaaaa",
    "copy",
    "outlet",
    "discount",
    "limited edition",
    "wholesale",
    "inspired",
    "cheap",
    "replica",
    "sales",
    "fake",
    "5 stars",
    "7 stars",
    "clearance",
    "copycat",
    "counterfeit",
    "counterfeits",
    "deal",
    "designer inspired",
    "discounted",
    "drop shipping",
    "dropshipping",
    "fakes",
    "imitate",
    "imitation",
    "inspired by",
    "knock off",
    "knockoff",
    "look alike",
    "look like",
    "lookalike",
    "looks like",
    "miror image",
    "mirror image",
    "non genuine",
    "non original",
    "not genuine",
    "not original",
    "not originale",
    "not real",
    "not the real",
    "repica",
    "repicas",
    "replicas",
    "reproduction",
    "repurposed",
    "rip off",
    "upcycled",
    "whole sale",
]

ORGANISATIONS = [
    "Deckers",
    "Philips",
    "Brunello_Cucinelli",
    "Hugo_Boss",
    "New_Guards",
    "Yves_Rocher",
    "Fendi",
    "Dolce_Gabbana",
    "Hublot",
    "Trustee",
    "Gucci",
    "Garnier",
    "Tiffany",
    "Tory_Burch",
    "Hermes",
    "Armani",
    "La_Roche_Posay",
    "Wella",
    "Bolton_Group",
    "Stella_McCartney",
    "Rimowa",
    "Dior",
    "Virbac",
    "Chanel",
    "Servier",
    "Unilever",
    "Louis_Vuitton",
    "Sergio_Rossi",
    "Brown_Forman",
    "Celine",
    "Kenzo",
    "Vibram",
    "Fred",
]

# TODO: implement related features
ORGANISATIONS_KEYWORDS = {
    "Deckers": [],
    "Philips": [],
    "Brunello_Cucinelli": [],
    "Hugo_Boss": [],
    "New_Guards": [],
    "Yves_Rocher": [],
    "Fendi": [],
    "Dolce_Gabbana": [],
    "Hublot": [],
    "Trustee": [],
    "Gucci": [],
    "Garnier": [],
    "Tiffany": [],
    "Tory_Burch": [],
    "Hermes": [],
    "Armani": [],
    "La_Roche_Posay": [],
    "Wella": [],
    "Bolton_Group": [],
    "Stella_McCartney": [],
    "Rimowa": [],
    "Dior": [],
    "Virbac": [],
    "Chanel": [],
    "Servier": [],
    "Unilever": [],
    "Louis_Vuitton": [],
    "Sergio_Rossi": [],
    "Brown_Forman": [],
    "Celine": [],
    "Kenzo": [],
    "Vibram": [],
    "Fred": ["force10"],
}
